import { fraction } from '../../features/unit-v2/math/fraction.ts'
import type { ChallengeItem, DiagnosticQuestion, ExerciseItem, LocalizedText, PracticeItem } from '../../features/unit-v2/types.ts'
import { storyGraphs, type GraphSpec, type Point } from './functions.ts'

/* ==========================================================================
   Funtzioak · 2. DBH — diagnostic, guided practice, exercise bank and
   challenges from Santillana 2.º ESO unit 13 and Anaya 2.º ESO unit 13.
   Every closed answer is a single number (the value asked for). Exercises
   that read a graph carry it as a GraphSpec: index.tsx draws it under the
   prompt and the tests check the answer against the same data.
   ========================================================================== */

type WithGraph = { graph?: GraphSpec; solutionGraph?: GraphSpec }
export type FunctionsDiagnosticQuestion = DiagnosticQuestion & WithGraph
export type FunctionsPracticeItem = PracticeItem & WithGraph
export type FunctionsChallengeItem = ChallengeItem & WithGraph
export type FunctionsExerciseItem = ExerciseItem & WithGraph
export interface FunctionsExerciseSection {
    id: string
    title: LocalizedText
    items: FunctionsExerciseItem[]
}

/** One of the lab's story graphs, with its axes, as an exercise graph */
function story(id: string): GraphSpec {
    const graph = storyGraphs.find((item) => item.id === id)!
    const xs = graph.points.map((point) => point[0])
    const ys = graph.points.map((point) => point[1])
    return {
        box: { xMin: Math.min(0, ...xs), xMax: Math.max(...xs), yMin: Math.min(0, ...ys), yMax: Math.max(...ys) + 1 },
        xTitle: graph.xLabel,
        yTitle: graph.yLabel,
        curves: [{ points: graph.points }]
    }
}

/** A curve y = f(x) sampled finely between two x, always through the whole x */
function sampled(fn: (x: number) => number, from: number, to: number): Point[] {
    const points: Point[] = []
    for (let x = from; x <= to + 1e-9; x += 0.1) points.push([Math.round(x * 10) / 10, Math.round(fn(Math.round(x * 10) / 10) * 1000) / 1000])
    return points
}

/** Arabic writes the decimal point instead of the comma, so {,} becomes . there */
const say = (eu: string, es: string, ar: string): LocalizedText => ({ eu, es, ar: ar.replace(/\{,\}/g, '.') })
/** Same formula everywhere, decimal point in Arabic */
const same = (value: string): LocalizedText => ({ eu: value, es: value, ar: value.replace(/\{,\}/g, '.') })

/** A table of values as LaTeX */
const table = (xs: number[], ys: number[]) => `\\begin{array}{c|${'c'.repeat(xs.length)}}x&${xs.join('&')}\\\\ \\hline y&${ys.join('&')}\\end{array}`

const tableBlock = (xs: number[], ys: number[]) => `$${table(xs, ys)}$`

export const functionsDiagnostic: FunctionsDiagnosticQuestion[] = [
    {
        id: 3001,
        prompt: say('Zein dira $P$ puntuaren koordenatuak?', '¿Cuáles son las coordenadas del punto $P$?', 'ما إحداثيا النقطة $P$؟'),
        options: [same('$(2,\\,-4)$'), same('$(-4,\\,2)$'), same('$(4,\\,2)$')],
        correctIndex: 1,
        explanation: say('Lehenik $x$: 4 unitate ezkerrera, $x=-4$. Gero $y$: 2 gora, $y=2$. $(2,\\,-4)$ ordena aldatzean ateratzen da.', 'Primero $x$: 4 unidades a la izquierda, $x=-4$. Después $y$: 2 hacia arriba, $y=2$. $(2,\\,-4)$ sale al cambiar el orden.', 'أولًا $x$: 4 وحدات إلى اليسار، $x=-4$. ثم $y$: وحدتان إلى أعلى، $y=2$. ينتج $(2,\\,-4)$ عند عكس الترتيب.'),
        topic: 'coordinates',
        graph: { box: { xMin: -5, xMax: 5, yMin: -4, yMax: 4 }, cell: 30, points: [{ at: [-4, 2], name: 'P' }] }
    },
    {
        id: 3002,
        prompt: say('Zein erlazio ez da funtzioa? A: $1\\to 3,\\ 2\\to 3,\\ 3\\to 3$. B: $1\\to 0,\\ 2\\to 1,\\ 2\\to 4$. C: $0\\to 5,\\ 1\\to 6,\\ 2\\to 7$.', '¿Qué relación no es función? A: $1\\to 3,\\ 2\\to 3,\\ 3\\to 3$. B: $1\\to 0,\\ 2\\to 1,\\ 2\\to 4$. C: $0\\to 5,\\ 1\\to 6,\\ 2\\to 7$.', 'أي علاقة ليست دالة؟ A: $1\\to 3,\\ 2\\to 3,\\ 3\\to 3$. B: $1\\to 0,\\ 2\\to 1,\\ 2\\to 4$. C: $0\\to 5,\\ 1\\to 6,\\ 2\\to 7$.'),
        options: [say('A', 'A', 'A'), say('B', 'B', 'B'), say('C', 'C', 'C')],
        correctIndex: 1,
        explanation: say('B-n, 2 sarrerak bi irteera ditu (1 eta 4). A-n irteera errepikatzea onargarria da.', 'En B, la entrada 2 tiene dos salidas (1 y 4). En A repetir la salida no importa.', 'في B للمدخل 2 مخرجان (1 و4). في A لا يهم تكرار المخرج.'),
        topic: 'function'
    },
    {
        id: 3003,
        prompt: say('Autoaren gasolina-litroak ordaindu beharreko dirua zehazten du. Zein da aldagai askea?', 'Los litros de gasolina determinan el dinero que hay que pagar. ¿Cuál es la variable independiente?', 'تحدد لترات البنزين المبلغ المطلوب دفعه. ما المتغير المستقل؟'),
        options: [say('Litroak', 'Los litros', 'اللترات'), say('Ordaindu beharreko dirua', 'El dinero a pagar', 'المبلغ المطلوب دفعه'), say('Gasolina-prezioa', 'El precio de la gasolina', 'سعر البنزين')],
        correctIndex: 0,
        explanation: say('Litroak aukeratzen dira ($x$) eta prezioa horien araberakoa da ($y$).', 'Se eligen los litros ($x$) y el precio depende de ellos ($y$).', 'نختار اللترات ($x$) ويعتمد السعر عليها ($y$).'),
        topic: 'variables'
    },
    {
        id: 3004,
        prompt: say('$f(x)=3x-2$ bada, zenbat da $f(-1)$?', 'Si $f(x)=3x-2$, ¿cuánto vale $f(-1)$?', 'إذا كانت $f(x)=3x-2$ فكم تساوي $f(-1)$؟'),
        options: [same('$-5$'), same('$-1$'), same('$1$')],
        correctIndex: 0,
        explanation: same('$f(-1)=3\\cdot(-1)-2=-3-2=-5$'),
        topic: 'formula'
    },
    {
        id: 3005,
        prompt: say('Grafikoak goiz bateko tenperatura erakusten du. Zein tartetan da konstantea?', 'La gráfica muestra la temperatura de una mañana. ¿En qué tramo es constante?', 'يبيّن الرسم درجة الحرارة في صباح ما. في أي فترة تكون ثابتة؟'),
        options: [same('$(0,\\,1)$'), same('$(1,\\,2)$'), same('$(2,\\,3)$')],
        correctIndex: 1,
        explanation: say('$x=1$ eta $x=2$ artean marra horizontala da: tenperatura 3 °C-an geratzen da.', 'Entre $x=1$ y $x=2$ la línea es horizontal: la temperatura se queda en 3 °C.', 'بين $x=1$ و$x=2$ الخط أفقي: تبقى الحرارة 3 °م.'),
        topic: 'variation',
        graph: {
            box: { xMin: 0, xMax: 4, yMin: 0, yMax: 9 },
            cell: 30,
            xTitle: say('ordua (h)', 'hora (h)', 'الساعة (س)'),
            yTitle: say('tenperatura (°C)', 'temperatura (°C)', 'الحرارة (°م)'),
            curves: [{ points: [[0, 5], [1, 3], [2, 3], [3, 6], [4, 8]] }]
        }
    },
    {
        id: 3006,
        prompt: say('Non ebakitzen du $y=2x-8$ zuzenak X ardatza?', '¿Dónde corta la recta $y=2x-8$ al eje X?', 'أين يقطع الخط $y=2x-8$ محور X؟'),
        options: [same('$(-8,\\,0)$'), same('$(4,\\,0)$'), same('$(0,\\,-8)$')],
        correctIndex: 1,
        explanation: say('$y=0$ jarrita: $0=2x-8\\ \\to\\ x=4$. $(0,\\,-8)$ Y ardatzeko ebakidura da.', 'Con $y=0$: $0=2x-8\\ \\to\\ x=4$. $(0,\\,-8)$ es el corte con el eje Y.', 'بوضع $y=0$: $0=2x-8\\ \\to\\ x=4$. أما $(0,\\,-8)$ فهو تقاطع محور Y.'),
        topic: 'intercepts'
    },
    {
        id: 3007,
        prompt: say('Zein da $A(1,\\,3)$ eta $B(3,\\,9)$ puntuetatik pasatzen den zuzenaren malda?', '¿Cuál es la pendiente de la recta que pasa por $A(1,\\,3)$ y $B(3,\\,9)$?', 'ما ميل الخط المار بالنقطتين $A(1,\\,3)$ و$B(3,\\,9)$؟'),
        options: [same('$2$'), same('$3$'), same('$6$')],
        correctIndex: 1,
        explanation: same('$m=\\frac{9-3}{3-1}=\\frac{6}{2}=3$'),
        topic: 'slope'
    },
    {
        id: 3008,
        prompt: say('Zein da zuzen honen ekuazioa?', '¿Cuál es la ecuación de esta recta?', 'ما معادلة هذا الخط؟'),
        options: [same('$y=x+3$'), same('$y=-x+3$'), same('$y=3x-1$')],
        correctIndex: 1,
        explanation: say('Y ardatza $(0,\\,3)$ puntuan ebakitzen du: $n=3$. Eskuinera 1 joatean 1 jaisten da: $m=-1$.', 'Corta al eje Y en $(0,\\,3)$: $n=3$. Al avanzar 1 a la derecha baja 1: $m=-1$.', 'يقطع محور Y في $(0,\\,3)$: $n=3$. عند التقدم وحدة إلى اليمين ينزل وحدة: $m=-1$.'),
        topic: 'affine',
        graph: { box: { xMin: -2, xMax: 5, yMin: -2, yMax: 5 }, cell: 32, lines: [{ m: -1, n: 3 }], points: [{ at: [0, 3], color: 'ink' }, { at: [3, 0], color: 'ink' }] }
    }
]

const temperatureGraph = story('temperature')
const altitudeGraph = story('plane')

export const functionsPractice: FunctionsPracticeItem[] = [
    { id: 1, stage: 'idea', prompt: say('Zein koadrantetan dago $C(-2,\\,-7)$ puntua? Idatzi koadrantearen zenbakia (1, 2, 3 edo 4).', '¿En qué cuadrante está el punto $C(-2,\\,-7)$? Escribe el número del cuadrante (1, 2, 3 o 4).', 'في أي ربع تقع النقطة $C(-2,\\,-7)$؟ اكتب رقم الربع (1 أو 2 أو 3 أو 4).'), expected: fraction(3), hint: say('Begiratu bi koordenatuen zeinuak.', 'Mira los signos de las dos coordenadas.', 'انظر إلى إشارتي الإحداثيين.'), explanation: say('Zeinuak $(-,\\,-)$: III. koadrantea, hau da, 3.', 'Signos $(-,\\,-)$: tercer cuadrante, es decir, 3.', 'الإشارتان $(-,\\,-)$: الربع الثالث أي 3.') },
    { id: 2, stage: 'idea', prompt: say('Karratu baten hiru erpin $A(1,\\,1)$, $B(5,\\,1)$ eta $C(5,\\,5)$ dira. Zein da laugarren erpinaren ordenatua, $D(1,\\,y)$?', 'Tres vértices de un cuadrado son $A(1,\\,1)$, $B(5,\\,1)$ y $C(5,\\,5)$. ¿Cuál es la ordenada del cuarto vértice, $D(1,\\,y)$?', 'ثلاثة رؤوس مربع هي $A(1,\\,1)$ و$B(5,\\,1)$ و$C(5,\\,5)$. ما ترتيبة الرأس الرابع $D(1,\\,y)$؟'), expected: fraction(5), hint: say('Aldea $5-1=4$ unitate da.', 'El lado mide $5-1=4$ unidades.', 'طول الضلع $5-1=4$ وحدات.'), explanation: same('$5-1=4\\ \\to\\ D=(1,\\,1+4)=(1,\\,5)$'), graph: { box: { xMin: 0, xMax: 6, yMin: 0, yMax: 6 }, cell: 32, points: [{ at: [1, 1], name: 'A', below: true, left: true }, { at: [5, 1], name: 'B', below: true }, { at: [5, 5], name: 'C' }] } },
    { id: 3, stage: 'idea', prompt: say('$(1,\\,4),\\ (2,\\,4),\\ (3,\\,9),\\ (3,\\,k)$ erlazioa funtzioa izan dadin, zenbat izan behar du $k$-k?', 'Para que la relación $(1,\\,4),\\ (2,\\,4),\\ (3,\\,9),\\ (3,\\,k)$ sea una función, ¿cuánto debe valer $k$?', 'لتكون العلاقة $(1,\\,4),\\ (2,\\,4),\\ (3,\\,9),\\ (3,\\,k)$ دالة، كم يجب أن تكون $k$؟'), expected: fraction(9), hint: say('$x=3$ sarrerak irteera bakarra izan behar du.', 'La entrada $x=3$ debe tener una sola salida.', 'يجب أن يكون للمدخل $x=3$ مخرج واحد فقط.'), explanation: say('$x=3$-ri $y=9$ dagokio; $x=3$-k irteera bakarra izateko, $k=9$.', 'A $x=3$ le corresponde $y=9$; para que tenga una sola salida, $k=9$.', 'يقابل $x=3$ القيمة $y=9$؛ ولكي يكون له مخرج واحد يجب $k=9$.') },
    { id: 4, stage: 'idea', prompt: say('$A(-3,\\,2)$ puntuaren simetrikoa Y ardatzarekiko $A\'(a,\\,2)$ da. Zenbat da $a$?', 'El simétrico de $A(-3,\\,2)$ respecto al eje Y es $A\'(a,\\,2)$. ¿Cuánto vale $a$?', 'نظير $A(-3,\\,2)$ بالنسبة لمحور Y هو $A\'(a,\\,2)$. كم تساوي $a$؟'), expected: fraction(3), hint: say('Y ardatzak ezker-eskuin islatzen du: abzisaren zeinua aldatzen da.', 'El eje Y refleja de izquierda a derecha: cambia el signo de la abscisa.', 'يعكس محور Y من اليسار إلى اليمين: تتغير إشارة الفاصلة.'), explanation: say('$-3$ bera da baina zeinu aldatuta: $a=3$.', 'Es $-3$ con el signo cambiado: $a=3$.', 'هي $-3$ بإشارة معكوسة: $a=3$.') },
    { id: 5, stage: 'representations', prompt: say('$y=3x-2$ funtzioan, zenbat da $y$ $x=4$ denean?', 'En la función $y=3x-2$, ¿cuánto vale $y$ cuando $x=4$?', 'في الدالة $y=3x-2$ كم تساوي $y$ عندما $x=4$؟'), expected: fraction(10), hint: say('Ordeztu $x$ 4rekin.', 'Sustituye $x$ por 4.', 'عوّض $x$ بـ 4.'), explanation: same('$3\\cdot 4-2=12-2=10$') },
    { id: 6, stage: 'representations', prompt: say('$f(x)=x^{2}-5$ bada, kalkulatu $f(-3)$.', 'Si $f(x)=x^{2}-5$, calcula $f(-3)$.', 'إذا كانت $f(x)=x^{2}-5$ فاحسب $f(-3)$.'), expected: fraction(4), hint: say('Parentesiak: $(-3)^{2}$ positiboa da.', 'Paréntesis: $(-3)^{2}$ es positivo.', 'الأقواس: $(-3)^{2}$ موجب.'), explanation: same('$f(-3)=(-3)^{2}-5=9-5=4$') },
    { id: 7, stage: 'representations', prompt: say('$f(x)=2x+1$ funtzioaren grafikoak $(a,\\,9)$ puntua dauka. Zenbat da $a$?', 'La gráfica de $f(x)=2x+1$ contiene el punto $(a,\\,9)$. ¿Cuánto vale $a$?', 'رسم $f(x)=2x+1$ يحوي النقطة $(a,\\,9)$. كم تساوي $a$؟'), expected: fraction(4), hint: say('$f(a)=9$ da: $2a+1=9$.', 'Se cumple $f(a)=9$: $2a+1=9$.', 'يتحقق $f(a)=9$: $2a+1=9$.'), explanation: same('$2a+1=9\\ \\to\\ 2a=8\\ \\to\\ a=4$') },
    { id: 8, stage: 'representations', prompt: say(`${tableBlock([1, 2, 3, 4], [7, 9, 11, 13])} taulak $y=2x+b$ funtzioa adierazten du. Zenbat da $b$?`, `${tableBlock([1, 2, 3, 4], [7, 9, 11, 13])} La tabla corresponde a $y=2x+b$. ¿Cuánto vale $b$?`, `${tableBlock([1, 2, 3, 4], [7, 9, 11, 13])} يمثل الجدول الدالة $y=2x+b$. كم تساوي $b$؟`), expected: fraction(5), hint: say('Ordeztu lehen zutabea: $x=1$, $y=7$.', 'Sustituye la primera columna: $x=1$, $y=7$.', 'عوّض العمود الأول: $x=1$، $y=7$.'), explanation: same('$7=2\\cdot 1+b\\ \\to\\ b=7-2=5$') },
    { id: 9, stage: 'reading', prompt: say('Grafikoak egun bateko tenperatura erakusten du. Zein ordutan da tenperatura minimoa?', 'La gráfica muestra la temperatura de un día. ¿A qué hora es mínima la temperatura?', 'يبيّن الرسم درجة الحرارة في يوم ما. في أي ساعة تكون الحرارة أدنى ما يمكن؟'), expected: fraction(2), hint: say('Bilatu grafikoaren punturik baxuena eta jaitsi X ardatzera.', 'Busca el punto más bajo de la gráfica y baja al eje X.', 'ابحث عن أدنى نقطة في الرسم وانزل إلى محور X.'), explanation: say('Punturik baxuena $(2,\\,1)$ da: 2etan, 1 °C.', 'El punto más bajo es $(2,\\,1)$: a las 2, con 1 °C.', 'أدنى نقطة هي $(2,\\,1)$: عند الساعة 2 بدرجة 1 °م.'), graph: temperatureGraph },
    { id: 10, stage: 'reading', prompt: say('Grafiko berean: zenbat gradu igotzen da tenperatura 3etatik 6etara?', 'En la misma gráfica: ¿cuántos grados sube la temperatura de las 3 a las 6?', 'في الرسم نفسه: كم درجة ترتفع الحرارة من الساعة 3 إلى الساعة 6؟'), expected: fraction(8), hint: say('Irakurri $f(3)$ eta $f(6)$, eta kendu.', 'Lee $f(3)$ y $f(6)$ y réstalos.', 'اقرأ $f(3)$ و$f(6)$ ثم اطرحهما.'), explanation: same('$f(6)-f(3)=12-4=8$'), graph: temperatureGraph },
    { id: 11, stage: 'reading', prompt: say('$y=2x-6$ zuzenak X ardatza non ebakitzen du? Idatzi $x$-ren balioa.', '¿Dónde corta la recta $y=2x-6$ al eje X? Escribe el valor de $x$.', 'أين يقطع الخط $y=2x-6$ محور X؟ اكتب قيمة $x$.'), expected: fraction(3), hint: say('X ardatzean $y=0$.', 'En el eje X, $y=0$.', 'على محور X تكون $y=0$.'), explanation: same('$0=2x-6\\ \\to\\ 2x=6\\ \\to\\ x=3$') },
    { id: 12, stage: 'reading', prompt: say('Grafikoak hegazkin baten altuera erakusten du. Zenbat km-ra iritsi da gehienez?', 'La gráfica muestra la altura de una avioneta. ¿A cuántos km ha llegado como máximo?', 'يبيّن الرسم ارتفاع طائرة صغيرة. ما أقصى ارتفاع بلغته بالكيلومتر؟'), expected: fraction(6), hint: say('Maximo absolutua: grafiko osoko punturik altuena.', 'El máximo absoluto: el punto más alto de toda la gráfica.', 'العظمى المطلقة: أعلى نقطة في الرسم كله.'), explanation: say('Punturik altuena $(5,\\,6)$ da: 6 km, 5. orduan. $(2,\\,4)$-tik $(4,\\,4)$-ra konstante dago.', 'El punto más alto es $(5,\\,6)$: 6 km, en la hora 5. De $(2,\\,4)$ a $(4,\\,4)$ se mantiene constante.', 'أعلى نقطة $(5,\\,6)$: 6 كم عند الساعة 5. ومن $(2,\\,4)$ إلى $(4,\\,4)$ يبقى ثابتًا.'), graph: altitudeGraph },
    { id: 13, stage: 'proportional', prompt: say('$y=mx$ funtzioaren grafikoa $(4,\\,10)$ puntutik pasatzen da. Zenbat da $m$?', 'La gráfica de $y=mx$ pasa por $(4,\\,10)$. ¿Cuánto vale $m$?', 'رسم $y=mx$ يمر بالنقطة $(4,\\,10)$. كم تساوي $m$؟'), expected: fraction(5, 2), hint: say('$m=y\\mathbin{:}x$.', '$m=y\\mathbin{:}x$.', '$m=y\\mathbin{:}x$.'), explanation: same('$10=m\\cdot 4\\ \\to\\ m=\\frac{10}{4}=\\frac{5}{2}=2{,}5$') },
    { id: 14, stage: 'proportional', prompt: say('Zein da $A(2,\\,-1)$ eta $B(6,\\,7)$ puntuetatik pasatzen den zuzenaren malda?', '¿Cuál es la pendiente de la recta que pasa por $A(2,\\,-1)$ y $B(6,\\,7)$?', 'ما ميل الخط المار بالنقطتين $A(2,\\,-1)$ و$B(6,\\,7)$؟'), expected: fraction(2), hint: say('Kendu koordenatuak ordena berean.', 'Resta las coordenadas en el mismo orden.', 'اطرح الإحداثيات بالترتيب نفسه.'), explanation: same('$m=\\frac{7-(-1)}{6-2}=\\frac{8}{4}=2$') },
    { id: 15, stage: 'proportional', prompt: say('$y=-3x$ funtzioan, zenbat da $y$ $x=-4$ denean?', 'En la función $y=-3x$, ¿cuánto vale $y$ cuando $x=-4$?', 'في الدالة $y=-3x$ كم تساوي $y$ عندما $x=-4$؟'), expected: fraction(12), hint: say('Zeinuen araua: $-\\cdot -=+$.', 'Regla de los signos: $-\\cdot -=+$.', 'قاعدة الإشارات: $-\\cdot -=+$.'), explanation: same('$y=-3\\cdot(-4)=12$') },
    { id: 16, stage: 'proportional', prompt: say('Autobus bat 40 km/h-ko abiaduran doa: $y=40x$ ($x$ orduak, $y$ km). Zenbat ordutan egiten ditu 150 km?', 'Un autobús va a 40 km/h: $y=40x$ ($x$ horas, $y$ km). ¿Cuántas horas tarda en hacer 150 km?', 'حافلة تسير بسرعة 40 كم/س: $y=40x$ ($x$ ساعات و$y$ كم). كم ساعة تحتاج لقطع 150 كم؟'), expected: fraction(15, 4), hint: say('Ordeztu $y=150$ eta askatu $x$.', 'Sustituye $y=150$ y despeja $x$.', 'عوّض $y=150$ واعزل $x$.'), explanation: same('$150=40x\\ \\to\\ x=\\frac{150}{40}=3{,}75$') },
    { id: 17, stage: 'lines', prompt: say('$y=-2x+8$ zuzenak X ardatza non ebakitzen du? Idatzi $x$-ren balioa.', '¿Dónde corta la recta $y=-2x+8$ al eje X? Escribe el valor de $x$.', 'أين يقطع الخط $y=-2x+8$ محور X؟ اكتب قيمة $x$.'), expected: fraction(4), hint: say('Ipini $y=0$.', 'Pon $y=0$.', 'ضع $y=0$.'), explanation: same('$0=-2x+8\\ \\to\\ 2x=8\\ \\to\\ x=4$') },
    { id: 18, stage: 'lines', prompt: say('Irakurri bi puntu markatuen koordenatuak. Zenbat da zuzenaren malda, $m$?', 'Lee las coordenadas de los dos puntos marcados. ¿Cuánto vale la pendiente $m$ de la recta?', 'اقرأ إحداثيي النقطتين المحددتين. كم يساوي ميل الخط $m$؟'), expected: fraction(2), hint: say('Puntuak $(0,\\,3)$ eta $(2,\\,7)$ dira: $m=\\Delta y\\mathbin{:}\\Delta x$.', 'Los puntos son $(0,\\,3)$ y $(2,\\,7)$: $m=\\Delta y\\mathbin{:}\\Delta x$.', 'النقطتان $(0,\\,3)$ و$(2,\\,7)$: $m=\\Delta y\\mathbin{:}\\Delta x$.'), explanation: same('$m=\\frac{7-3}{2-0}=\\frac{4}{2}=2$'), graph: { box: { xMin: -2, xMax: 4, yMin: -1, yMax: 9 }, cell: 30, lines: [{ m: 2, n: 3 }], points: [{ at: [0, 3], color: 'ink' }, { at: [2, 7], color: 'ink' }] } },
    { id: 19, stage: 'lines', prompt: say('Zuzen bat $(1,\\,4)$ eta $(3,\\,10)$ puntuetatik pasatzen da. Zenbat da $n$ ($y=mx+n$ formulan)?', 'Una recta pasa por $(1,\\,4)$ y $(3,\\,10)$. ¿Cuánto vale $n$ (en $y=mx+n$)?', 'خط يمر بالنقطتين $(1,\\,4)$ و$(3,\\,10)$. كم تساوي $n$ (في $y=mx+n$)؟'), expected: fraction(1), hint: say('Lehenik $m$, gero ordeztu puntu bat.', 'Primero $m$; después sustituye un punto.', 'أولًا $m$ ثم عوّض نقطة.'), explanation: same('$m=\\frac{10-4}{3-1}=3\\qquad 4=3\\cdot 1+n\\ \\to\\ n=1$') },
    { id: 20, stage: 'lines', prompt: say('Aparkaleku batean 2 € ordaintzen dira sartzean eta 0,75 € orduko: $y=0{,}75x+2$. Zenbat € ordaindu behar dira 6 ordutan?', 'En un parking se pagan 2 € al entrar y 0,75 € por hora: $y=0{,}75x+2$. ¿Cuántos € se pagan por 6 horas?', 'في موقف سيارات يُدفع 2 € عند الدخول و0.75 € للساعة: $y=0{,}75x+2$. كم € يُدفع عن 6 ساعات؟'), expected: fraction(13, 2), hint: say('Ordeztu $x=6$.', 'Sustituye $x=6$.', 'عوّض $x=6$.'), explanation: same('$y=0{,}75\\cdot 6+2=4{,}5+2=6{,}5$') }
]

export const functionsChallenges: FunctionsChallengeItem[] = [
    { id: 101, stage: 'idea', context: 'starter', points: 10, prompt: say('Karratu baten hiru erpin $A(-2,\\,-1)$, $B(3,\\,-1)$ eta $C(3,\\,4)$ dira. Zenbat da karratuaren azalera?', 'Tres vértices de un cuadrado son $A(-2,\\,-1)$, $B(3,\\,-1)$ y $C(3,\\,4)$. ¿Cuánto mide su área?', 'ثلاثة رؤوس مربع هي $A(-2,\\,-1)$ و$B(3,\\,-1)$ و$C(3,\\,4)$. كم مساحته؟'), expected: fraction(25), hint: say('Aldea: $3-(-2)$.', 'El lado: $3-(-2)$.', 'الضلع: $3-(-2)$.'), explanation: same('$3-(-2)=5\\ \\to\\ 5\\cdot 5=25$') },
    { id: 102, stage: 'idea', context: 'advanced', points: 20, prompt: say('$(1,\\,a),\\ (2,\\,5),\\ (1,\\,3),\\ (4,\\,0)$ erlazioa funtzioa da. Zenbat da $a$?', 'La relación $(1,\\,a),\\ (2,\\,5),\\ (1,\\,3),\\ (4,\\,0)$ es una función. ¿Cuánto vale $a$?', 'العلاقة $(1,\\,a),\\ (2,\\,5),\\ (1,\\,3),\\ (4,\\,0)$ دالة. كم تساوي $a$؟'), expected: fraction(3), hint: say('$x=1$-ek irteera bakarra du.', '$x=1$ tiene una sola salida.', 'للمدخل $x=1$ مخرج واحد.'), explanation: say('$x=1$-ri $y=3$ dagokio; beraz $a=3$.', 'A $x=1$ le corresponde $y=3$; luego $a=3$.', 'يقابل $x=1$ القيمة $y=3$؛ إذن $a=3$.') },
    { id: 103, stage: 'representations', context: 'starter', points: 10, prompt: say('$f(x)=-2x+5$ bada, zenbat da $f(4)$?', 'Si $f(x)=-2x+5$, ¿cuánto vale $f(4)$?', 'إذا كانت $f(x)=-2x+5$ فكم تساوي $f(4)$؟'), expected: fraction(-3), hint: say('$-2\\cdot 4+5$', '$-2\\cdot 4+5$', '$-2\\cdot 4+5$'), explanation: same('$f(4)=-2\\cdot 4+5=-8+5=-3$') },
    { id: 104, stage: 'representations', context: 'advanced', points: 20, prompt: say('$f(x)=x^{2}-3x$ bada, zenbat da $f(-2)$?', 'Si $f(x)=x^{2}-3x$, ¿cuánto vale $f(-2)$?', 'إذا كانت $f(x)=x^{2}-3x$ فكم تساوي $f(-2)$؟'), expected: fraction(10), hint: say('Kontuz zeinuekin: $(-2)^{2}$ eta $-3\\cdot(-2)$.', 'Cuidado con los signos: $(-2)^{2}$ y $-3\\cdot(-2)$.', 'انتبه للإشارات: $(-2)^{2}$ و$-3\\cdot(-2)$.'), explanation: same('$f(-2)=(-2)^{2}-3\\cdot(-2)=4+6=10$') },
    { id: 105, stage: 'reading', context: 'starter', points: 10, prompt: say('Grafikoak auto baten bidaia erakusten du (lauki bakoitza 20 km). Zenbat km egin ditu 2. eta 3. orduen artean?', 'La gráfica muestra el viaje de un coche (cada cuadro son 20 km). ¿Cuántos km recorre entre la hora 2 y la hora 3?', 'يبيّن الرسم رحلة سيارة (كل مربع 20 كم). كم كيلومترًا تقطع بين الساعة 2 والساعة 3؟'), expected: fraction(60), hint: say('Irakurri $f(2)$ eta $f(3)$ ardatz bertikalean, eta kendu.', 'Lee $f(2)$ y $f(3)$ en el eje vertical y réstalos.', 'اقرأ $f(2)$ و$f(3)$ على المحور الرأسي ثم اطرحهما.'), explanation: say('$f(2)=40$ eta $f(3)=100$: $100-40=60$ km. 1etik 2ra geldirik egon da.', '$f(2)=40$ y $f(3)=100$: $100-40=60$ km. De 1 a 2 ha estado parado.', '$f(2)=40$ و$f(3)=100$: $100-40=60$ كم. ومن 1 إلى 2 كانت متوقفة.'), graph: { box: { xMin: 0, xMax: 4, yMin: 0, yMax: 7 }, cell: 34, yUnit: 20, xTitle: say('denbora (h)', 'tiempo (h)', 'الزمن (س)'), yTitle: say('distantzia (km)', 'distancia (km)', 'المسافة (كم)'), curves: [{ points: [[0, 0], [1, 2], [2, 2], [3, 5], [4, 6]] }] } },
    { id: 106, stage: 'reading', context: 'advanced', points: 20, prompt: say('$x^{2}-4x+3=0$ ekuazioaren ebazpenak $y=x^{2}-4x+3$ funtzioaren X ardatzeko ebakiduren abzisak dira. Idatzi handiena.', 'Las soluciones de $x^{2}-4x+3=0$ son las abscisas de los cortes de $y=x^{2}-4x+3$ con el eje X. Escribe la mayor.', 'حلول $x^{2}-4x+3=0$ هي فواصل نقاط تقاطع $y=x^{2}-4x+3$ مع محور X. اكتب الأكبر.'), expected: fraction(3), hint: say('Formula orokorra: $\\Delta=16-12=4$.', 'Fórmula general: $\\Delta=16-12=4$.', 'الصيغة العامة: $\\Delta=16-12=4$.'), explanation: say('$x=\\frac{4\\pm 2}{2}$: $x=3$ eta $x=1$. Handiena: 3.', '$x=\\frac{4\\pm 2}{2}$: $x=3$ y $x=1$. La mayor: 3.', '$x=\\frac{4\\pm 2}{2}$: $x=3$ و$x=1$. الأكبر: 3.') },
    { id: 107, stage: 'reading', context: 'master', points: 30, prompt: say('$f(x)=x^{2}-6x+5$ funtzioak minimo bat du, bere bi zeroen erdian. Zenbat da minimo horren ordenatua?', 'La función $f(x)=x^{2}-6x+5$ tiene un mínimo, situado a mitad de camino entre sus dos ceros. ¿Cuánto vale la ordenada de ese mínimo?', 'للدالة $f(x)=x^{2}-6x+5$ قيمة صغرى تقع في منتصف المسافة بين صفريها. كم تساوي ترتيبة هذه القيمة الصغرى؟'), expected: fraction(-4), hint: say('Zeroak $x=1$ eta $x=5$ dira: erdian $x=3$.', 'Los ceros son $x=1$ y $x=5$: a mitad de camino, $x=3$.', 'الصفران $x=1$ و$x=5$: في المنتصف $x=3$.'), explanation: same('$f(3)=3^{2}-6\\cdot 3+5=9-18+5=-4$') },
    { id: 108, stage: 'proportional', context: 'starter', points: 10, prompt: say('Proportzionaltasun zuzeneko funtzio baten grafikoa $(6,\\,15)$ puntutik pasatzen da. Zenbat da $y$ $x=2$ denean?', 'La gráfica de una función de proporcionalidad directa pasa por $(6,\\,15)$. ¿Cuánto vale $y$ cuando $x=2$?', 'رسم دالة تناسب طردي يمر بالنقطة $(6,\\,15)$. كم تساوي $y$ عندما $x=2$؟'), expected: fraction(5), hint: say('Lehenik $m=15\\mathbin{:}6$.', 'Primero $m=15\\mathbin{:}6$.', 'أولًا $m=15\\mathbin{:}6$.'), explanation: same('$m=\\frac{15}{6}=\\frac{5}{2}\\ \\to\\ y=\\frac{5}{2}\\cdot 2=5$') },
    { id: 109, stage: 'proportional', context: 'advanced', points: 20, prompt: say('$A(-2,\\,7)$ eta $B(4,\\,k)$ puntuetatik pasatzen den zuzenaren malda $-1$ da. Zenbat da $k$?', 'La recta que pasa por $A(-2,\\,7)$ y $B(4,\\,k)$ tiene pendiente $-1$. ¿Cuánto vale $k$?', 'الخط المار بالنقطتين $A(-2,\\,7)$ و$B(4,\\,k)$ ميله $-1$. كم تساوي $k$؟'), expected: fraction(1), hint: say('$\\frac{k-7}{4-(-2)}=-1$', '$\\frac{k-7}{4-(-2)}=-1$', '$\\frac{k-7}{4-(-2)}=-1$'), explanation: same('$\\frac{k-7}{6}=-1\\ \\to\\ k-7=-6\\ \\to\\ k=1$') },
    { id: 110, stage: 'proportional', context: 'master', points: 30, prompt: say('$A(-3,\\,-2)$, $B(1,\\,6)$ eta $C(4,\\,k)$ puntuak zuzen berean daude. Zenbat da $k$?', 'Los puntos $A(-3,\\,-2)$, $B(1,\\,6)$ y $C(4,\\,k)$ están alineados. ¿Cuánto vale $k$?', 'النقاط $A(-3,\\,-2)$ و$B(1,\\,6)$ و$C(4,\\,k)$ على استقامة واحدة. كم تساوي $k$؟'), expected: fraction(12), hint: say('$A$-$B$ eta $B$-$C$ maldak berdinak dira.', 'Las pendientes $A$-$B$ y $B$-$C$ son iguales.', 'ميلا $A$-$B$ و$B$-$C$ متساويان.'), explanation: same('$m=\\frac{6-(-2)}{1-(-3)}=\\frac{8}{4}=2\\qquad \\frac{k-6}{4-1}=2\\ \\to\\ k=12$') },
    { id: 111, stage: 'lines', context: 'starter', points: 10, prompt: say('Zuzen bat $(1,\\,5)$ eta $(3,\\,9)$ puntuetatik pasatzen da. Zenbat da $n$ ($y=mx+n$)?', 'Una recta pasa por $(1,\\,5)$ y $(3,\\,9)$. ¿Cuánto vale $n$ (en $y=mx+n$)?', 'خط يمر بالنقطتين $(1,\\,5)$ و$(3,\\,9)$. كم تساوي $n$ (في $y=mx+n$)؟'), expected: fraction(3), hint: say('Lehenik $m$.', 'Primero $m$.', 'أولًا $m$.'), explanation: same('$m=\\frac{9-5}{3-1}=2\\qquad 5=2\\cdot 1+n\\ \\to\\ n=3$') },
    { id: 112, stage: 'lines', context: 'advanced', points: 20, prompt: say('Telefono-tarifak: A: $y=0{,}10x+6$; B: $y=0{,}25x$ ($x$ minutuak, $y$ €). Zenbat minututan dira berdinak?', 'Dos tarifas de móvil: A: $y=0{,}10x+6$; B: $y=0{,}25x$ ($x$ minutos, $y$ €). ¿En cuántos minutos cuestan lo mismo?', 'تعرفتان للهاتف: A: $y=0{,}10x+6$ وB: $y=0{,}25x$ ($x$ دقائق و$y$ €). بعد كم دقيقة يتساويان؟'), expected: fraction(40), hint: say('Berdindu bi formulak.', 'Iguala las dos fórmulas.', 'ساوِ الصيغتين.'), explanation: same('$0{,}10x+6=0{,}25x\\ \\to\\ 6=0{,}15x\\ \\to\\ x=6\\mathbin{:}0{,}15=40$') },
    { id: 113, stage: 'lines', context: 'master', points: 30, prompt: say('Bi txirrindulari: A-k $y=20x$ egiten du (20 km/h); B-k $y=12x+2$ (12 km/h, 2 km-ko abantailarekin). Zenbat ordu behar ditu A-k B harrapatzeko?', 'Dos ciclistas: A recorre $y=20x$ (20 km/h); B recorre $y=12x+2$ (12 km/h, con 2 km de ventaja). ¿Cuántas horas tarda A en alcanzar a B?', 'دراجان: A يقطع $y=20x$ (20 كم/س) وB يقطع $y=12x+2$ (12 كم/س مع تقدم 2 كم). كم ساعة يحتاج A ليلحق بـ B؟'), expected: fraction(1, 4), hint: say('Harrapatzean distantzia bera dute.', 'Al alcanzarlo tienen la misma distancia.', 'عند اللحاق تتساوى المسافتان.'), explanation: same('$20x=12x+2\\ \\to\\ 8x=2\\ \\to\\ x=2\\mathbin{:}8=0{,}25$') }
]

/** A short flight: rises, stays level from 2 h to 3 h, rises again and lands */
const flightGraph: GraphSpec = {
    box: { xMin: 0, xMax: 6, yMin: 0, yMax: 7 },
    cell: 34,
    xTitle: say('denbora (h)', 'tiempo (h)', 'الزمن (س)'),
    yTitle: say('altuera (km)', 'altura (km)', 'الارتفاع (كم)'),
    curves: [{ points: [[0, 0], [1, 3], [2, 5], [3, 5], [4, 6], [5, 2], [6, 0]] }]
}
const parabolaGraph: GraphSpec = { box: { xMin: -3, xMax: 3, yMin: -2, yMax: 4 }, cell: 34, curves: [{ points: sampled((x) => x * x - 1, -2.2, 2.2) }] }

export const functionsExerciseBank: FunctionsExerciseSection[] = [
    {
        id: 'idea',
        title: say('Koordenatuak eta funtzioa', 'Coordenadas y función', 'الإحداثيات والدالة'),
        items: [
            { id: 1, difficulty: 'easy', question: say('Idatzi puntu hauen koadrantea: $A(3,\\,2)$, $B(-4,\\,1)$, $C(-2,\\,-5)$, $D(0,\\,-3)$.', 'Escribe el cuadrante de estos puntos: $A(3,\\,2)$, $B(-4,\\,1)$, $C(-2,\\,-5)$, $D(0,\\,-3)$.', 'اكتب ربع كل نقطة: $A(3,\\,2)$ و$B(-4,\\,1)$ و$C(-2,\\,-5)$ و$D(0,\\,-3)$.'), solution: say('$A$: I · $B$: II · $C$: III · $D$ Y ardatzean dago (ez dago koadranterik).', '$A$: I · $B$: II · $C$: III · $D$ está en el eje Y (no está en ningún cuadrante).', '$A$: I · $B$: II · $C$: III · $D$ على محور Y (ليست في أي ربع).') },
            { id: 2, difficulty: 'easy', question: say('Zein koadrantetan egon daiteke puntu bat, bere abzisa positiboa bada?', '¿En qué cuadrantes puede estar un punto cuya abscisa es positiva?', 'في أي أرباع يمكن أن تقع نقطة فاصلتها موجبة؟'), solution: say('I edo IV koadrantean: $x>0$ da eta $y$ positiboa edo negatiboa izan daiteke.', 'En el I o en el IV: $x>0$ e $y$ puede ser positiva o negativa.', 'في الربع I أو IV: $x>0$ ويمكن أن تكون $y$ موجبة أو سالبة.') },
            { id: 3, difficulty: 'medium', question: say('Laukizuzen baten hiru erpin $A(-2,\\,1)$, $B(4,\\,1)$ eta $C(4,\\,5)$ dira. Idatzi laugarren erpina.', 'Tres vértices de un rectángulo son $A(-2,\\,1)$, $B(4,\\,1)$ y $C(4,\\,5)$. Escribe el cuarto vértice.', 'ثلاثة رؤوس مستطيل هي $A(-2,\\,1)$ و$B(4,\\,1)$ و$C(4,\\,5)$. اكتب الرأس الرابع.'), solution: say('$D$ $A$-ren abzisa eta $C$-ren ordenatua ditu: $D(-2,\\,5)$.', '$D$ tiene la abscisa de $A$ y la ordenada de $C$: $D(-2,\\,5)$.', 'لـ $D$ فاصلة $A$ وترتيبة $C$: $D(-2,\\,5)$.') },
            { id: 4, difficulty: 'medium', question: say('Laukizuzen baten erpinak $A(-2,\\,1)$, $B(4,\\,1)$, $C(4,\\,5)$ eta $D(-2,\\,5)$ dira. Zenbat da azalera?', 'Un rectángulo tiene por vértices $A(-2,\\,1)$, $B(4,\\,1)$, $C(4,\\,5)$ y $D(-2,\\,5)$. ¿Cuánto mide su área?', 'رؤوس مستطيل هي $A(-2,\\,1)$ و$B(4,\\,1)$ و$C(4,\\,5)$ و$D(-2,\\,5)$. كم مساحته؟'), solution: same('$4-(-2)=6\\qquad 5-1=4\\qquad 6\\cdot 4=24$'), answer: { expected: fraction(24) } },
            { id: 5, difficulty: 'medium', question: say('Funtzioak al dira? a) $1\\to 2,\\ 2\\to 4,\\ 3\\to 6$; b) $1\\to 3,\\ 1\\to 5,\\ 2\\to 7$; c) zenbaki bakoitza eta bere karratua.', '¿Son funciones? a) $1\\to 2,\\ 2\\to 4,\\ 3\\to 6$; b) $1\\to 3,\\ 1\\to 5,\\ 2\\to 7$; c) cada número y su cuadrado.', 'هل هي دوال؟ أ) $1\\to 2,\\ 2\\to 4,\\ 3\\to 6$؛ ب) $1\\to 3,\\ 1\\to 5,\\ 2\\to 7$؛ ج) كل عدد ومربعه.'), solution: say('a) Bai. b) Ez: $x=1$-ek bi irteera ditu (3 eta 5). c) Bai: zenbaki bakoitzak karratu bakarra du.', 'a) Sí. b) No: $x=1$ tiene dos salidas (3 y 5). c) Sí: cada número tiene un único cuadrado.', 'أ) نعم. ب) لا: للمدخل $x=1$ مخرجان (3 و5). ج) نعم: لكل عدد مربع واحد.') },
            { id: 6, difficulty: 'medium', question: say('Funtzioak al dira? a) pertsona baten altuera ($x$) eta adina ($y$); b) eguneko tenperatura maximoa ($y$) egunaren arabera ($x$).', '¿Son funciones? a) la altura de una persona ($x$) y su edad ($y$); b) la temperatura máxima ($y$) según el día ($x$).', 'هل هي دوال؟ أ) طول شخص ($x$) وعمره ($y$)؛ ب) أعلى حرارة ($y$) بحسب اليوم ($x$).'), solution: say('a) Ez: altuera bera duten pertsonek adin desberdinak izan ditzakete. b) Bai: egun bakoitzak tenperatura maximo bakarra du.', 'a) No: personas con la misma altura pueden tener edades distintas. b) Sí: cada día tiene una sola temperatura máxima.', 'أ) لا: أشخاص بالطول نفسه قد تختلف أعمارهم. ب) نعم: لكل يوم حرارة عظمى واحدة.') },
            { id: 7, difficulty: 'medium', question: say('Adierazi aldagai askea eta menpekoa: a) sagar-kiloak eta ordaindu beharreko dirua; b) denbora eta hodi batetik ateratako ur-litroak; c) abiadura eta 120 km egiteko behar den denbora.', 'Indica la variable independiente y la dependiente: a) los kilos de manzanas y el dinero a pagar; b) el tiempo y los litros de agua que salen de un grifo; c) la velocidad y el tiempo para recorrer 120 km.', 'حدّد المتغير المستقل والتابع: أ) كيلوغرامات التفاح والمبلغ المدفوع؛ ب) الزمن ولترات الماء الخارجة من صنبور؛ ج) السرعة والزمن اللازم لقطع 120 كم.'), solution: say('a) $x$: kiloak; $y$: dirua. b) $x$: denbora; $y$: litroak. c) $x$: abiadura; $y$: denbora.', 'a) $x$: kilos; $y$: dinero. b) $x$: tiempo; $y$: litros. c) $x$: velocidad; $y$: tiempo.', 'أ) $x$: الكيلوغرامات؛ $y$: المال. ب) $x$: الزمن؛ $y$: اللترات. ج) $x$: السرعة؛ $y$: الزمن.') },
            { id: 8, difficulty: 'hard', question: say('Zenbat da $A(3,\\,-2)$ puntuaren simetrikoaren ordenatua jatorriarekiko?', '¿Cuánto vale la ordenada del simétrico de $A(3,\\,-2)$ respecto al origen?', 'كم تساوي ترتيبة نظير $A(3,\\,-2)$ بالنسبة لنقطة الأصل؟'), solution: say('Jatorriarekiko simetrikoan bi koordenatuen zeinua aldatzen da: $A\'(-3,\\,2)$. Ordenatua: 2.', 'En el simétrico respecto al origen cambian los signos de las dos coordenadas: $A\'(-3,\\,2)$. La ordenada es 2.', 'في النظير بالنسبة لنقطة الأصل تنعكس إشارتا الإحداثيين: $A\'(-3,\\,2)$. الترتيبة 2.'), answer: { expected: fraction(2) } },
            { id: 9, difficulty: 'hard', question: say('$(2,\\,5),\\ (2,\\,k),\\ (3,\\,1)$ erlazioa funtzioa da. Zenbat da $k$?', 'La relación $(2,\\,5),\\ (2,\\,k),\\ (3,\\,1)$ es una función. ¿Cuánto vale $k$?', 'العلاقة $(2,\\,5),\\ (2,\\,k),\\ (3,\\,1)$ دالة. كم تساوي $k$؟'), solution: say('$x=2$-k irteera bakarra izan behar du: $k=5$.', '$x=2$ debe tener una sola salida: $k=5$.', 'يجب أن يكون لـ $x=2$ مخرج واحد: $k=5$.'), answer: { expected: fraction(5) } }
        ]
    },
    {
        id: 'representations',
        title: say('Taulak, formulak eta grafikoak', 'Tablas, fórmulas y gráficas', 'الجداول والصيغ والرسوم'),
        items: [
            { id: 10, difficulty: 'easy', question: say('Osatu $y=3x-1$ funtzioaren taula, $x=-2,\\,-1,\\,0,\\,1,\\,2$ balioekin.', 'Completa la tabla de $y=3x-1$ con $x=-2,\\,-1,\\,0,\\,1,\\,2$.', 'أكمل جدول $y=3x-1$ بالقيم $x=-2,\\,-1,\\,0,\\,1,\\,2$.'), solution: same(`${tableBlock([-2, -1, 0, 1, 2], [-7, -4, -1, 2, 5])}`) },
            { id: 11, difficulty: 'easy', question: say('$f(x)=2x+5$ bada, kalkulatu $f(0)$, $f(3)$ eta $f(-4)$.', 'Si $f(x)=2x+5$, calcula $f(0)$, $f(3)$ y $f(-4)$.', 'إذا كانت $f(x)=2x+5$ فاحسب $f(0)$ و$f(3)$ و$f(-4)$.'), solution: same('$f(0)=5\\qquad f(3)=2\\cdot 3+5=11\\qquad f(-4)=2\\cdot(-4)+5=-3$') },
            { id: 12, difficulty: 'easy', question: say('$f(x)=x^{2}+1$ bada, zenbat da $f(-3)$?', 'Si $f(x)=x^{2}+1$, ¿cuánto vale $f(-3)$?', 'إذا كانت $f(x)=x^{2}+1$ فكم تساوي $f(-3)$؟'), solution: same('$f(-3)=(-3)^{2}+1=9+1=10$'), answer: { expected: fraction(10) } },
            { id: 13, difficulty: 'medium', question: say(`${tableBlock([0, 1, 2, 3], [4, 7, 10, 13])} Idatzi taula honi dagokion formula.`, `${tableBlock([0, 1, 2, 3], [4, 7, 10, 13])} Escribe la fórmula que corresponde a esta tabla.`, `${tableBlock([0, 1, 2, 3], [4, 7, 10, 13])} اكتب الصيغة المقابلة لهذا الجدول.`), solution: say('$x$ bat handitzean $y$ 3 igotzen da: $m=3$. $x=0$ denean $y=4$: $y=3x+4$.', 'Al aumentar $x$ en 1, $y$ sube 3: $m=3$. Con $x=0$, $y=4$: $y=3x+4$.', 'عند زيادة $x$ بمقدار 1 تزيد $y$ بمقدار 3: $m=3$. وعند $x=0$ تكون $y=4$: $y=3x+4$.') },
            { id: 14, difficulty: 'medium', question: say('$y=-x+6$ funtzioaren grafikoak $(a,\\,2)$ puntua dauka. Zenbat da $a$?', 'La gráfica de $y=-x+6$ contiene el punto $(a,\\,2)$. ¿Cuánto vale $a$?', 'رسم $y=-x+6$ يحوي النقطة $(a,\\,2)$. كم تساوي $a$؟'), solution: same('$2=-a+6\\ \\to\\ a=6-2=4$'), answer: { expected: fraction(4) } },
            { id: 15, difficulty: 'medium', question: say('Menu bakoitzak 9,50 € balio du. Idatzi prezioaren funtzioa eta osatu taula $x=1,\\,2,\\,3,\\,4$ menurako. Elkartu behar dira puntuak?', 'Cada menú cuesta 9,50 €. Escribe la función del precio y completa la tabla para $x=1,\\,2,\\,3,\\,4$ menús. ¿Hay que unir los puntos?', 'ثمن كل وجبة 9.50 €. اكتب دالة السعر وأكمل الجدول من أجل $x=1,\\,2,\\,3,\\,4$ وجبات. هل نصل النقاط؟'), solution: say('$y=9{,}5x$: 9,50 · 19 · 28,50 · 38 €. Ez: ezin da 2,5 menu erosi; grafikoa etena da.', '$y=9{,}5x$: 9,50 · 19 · 28,50 · 38 €. No: no se pueden comprar 2,5 menús; la gráfica es discontinua.', '$y=9{,}5x$: 9.50 · 19 · 28.50 · 38 €. لا: لا يمكن شراء 2.5 وجبة؛ الرسم منفصل.'), solutionGraph: { box: { xMin: 0, xMax: 5, yMin: 0, yMax: 4 }, cell: 40, yUnit: 10, xTitle: say('menuak', 'menús', 'الوجبات'), yTitle: say('prezioa (€)', 'precio (€)', 'السعر (€)'), points: [1, 2, 3, 4].map((x) => ({ at: [x, 0.95 * x] as Point, color: 'stage' as const })) } },
            { id: 16, difficulty: 'hard', question: say('$f(x)=x^{2}-4x+3$ bada, zenbat da $f(5)$?', 'Si $f(x)=x^{2}-4x+3$, ¿cuánto vale $f(5)$?', 'إذا كانت $f(x)=x^{2}-4x+3$ فكم تساوي $f(5)$؟'), solution: same('$f(5)=5^{2}-4\\cdot 5+3=25-20+3=8$'), answer: { expected: fraction(8) } },
            { id: 17, difficulty: 'hard', question: say('Marraztu $y=x^{2}-2x$, taula bat eginez $x=-1,\\,0,\\,1,\\,2,\\,3$ balioekin. Zer forma du?', 'Dibuja $y=x^{2}-2x$ con una tabla para $x=-1,\\,0,\\,1,\\,2,\\,3$. ¿Qué forma tiene?', 'ارسم $y=x^{2}-2x$ بجدول من أجل $x=-1,\\,0,\\,1,\\,2,\\,3$. ما شكله؟'), solution: say(`${tableBlock([-1, 0, 1, 2, 3], [3, 0, -1, 0, 3])} Parabola da; minimoa $(1,\\,-1)$ puntuan dago.`, `${tableBlock([-1, 0, 1, 2, 3], [3, 0, -1, 0, 3])} Es una parábola; su mínimo está en $(1,\\,-1)$.`, `${tableBlock([-1, 0, 1, 2, 3], [3, 0, -1, 0, 3])} إنه قطع مكافئ وقيمته الصغرى عند $(1,\\,-1)$.`), solutionGraph: { box: { xMin: -2, xMax: 4, yMin: -2, yMax: 4 }, cell: 34, curves: [{ points: sampled((x) => x * x - 2 * x, -1.2, 3.2), color: 'second' }], points: [-1, 0, 1, 2, 3].map((x) => ({ at: [x, x * x - 2 * x] as Point, color: 'stage' as const })) } },
            { id: 18, difficulty: 'hard', question: say('Erabaki grafikoa jarraitua ala etena den: a) autoaren distantzia denboraren arabera; b) egunero saldutako sarrerak; c) aparkalekuaren prezioa, ordu osoka kobratzen bada; d) pertsona baten altuera adinaren arabera.', 'Decide si la gráfica es continua o discontinua: a) distancia de un coche según el tiempo; b) entradas vendidas cada día; c) precio de un aparcamiento si se cobra por horas enteras; d) altura de una persona según su edad.', 'حدّد هل الرسم متصل أم منفصل: أ) مسافة سيارة بحسب الزمن؛ ب) التذاكر المبيعة كل يوم؛ ج) سعر موقف إذا حُسب بالساعات الكاملة؛ د) طول شخص بحسب عمره.'), solution: say('a) Jarraitua. b) Etena. c) Etena (prezioak jauzi egiten du). d) Jarraitua.', 'a) Continua. b) Discontinua. c) Discontinua (el precio da saltos). d) Continua.', 'أ) متصل. ب) منفصل. ج) منفصل (يقفز السعر). د) متصل.') }
        ]
    },
    {
        id: 'reading',
        title: say('Grafikoak irakurtzen', 'Leer gráficas', 'قراءة الرسوم البيانية'),
        items: [
            { id: 19, difficulty: 'easy', question: say('Grafikoak hegazkin baten altuera erakusten du. Zein da altuera maximoa (km)?', 'La gráfica muestra la altura de una avioneta. ¿Cuál es la altura máxima (km)?', 'يبيّن الرسم ارتفاع طائرة صغيرة. ما أقصى ارتفاع (كم)؟'), solution: say('Punturik altuena $(4,\\,6)$ da: altuera maximoa 6 km.', 'El punto más alto es $(4,\\,6)$: la altura máxima es 6 km.', 'أعلى نقطة $(4,\\,6)$: أقصى ارتفاع 6 كم.'), answer: { expected: fraction(6) }, graph: flightGraph },
            { id: 20, difficulty: 'easy', question: say('Grafiko berean: zenbat ordu egon da hegazkina altuera berean?', 'En la misma gráfica: ¿cuántas horas ha permanecido la avioneta a la misma altura?', 'في الرسم نفسه: كم ساعة بقيت الطائرة على الارتفاع نفسه؟'), solution: say('Altuera 5 km da $x=2$ eta $x=3$ artean: $3-2=1$ ordu.', 'La altura es 5 km entre $x=2$ y $x=3$: $3-2=1$ hora.', 'الارتفاع 5 كم بين $x=2$ و$x=3$: $3-2=1$ ساعة.'), answer: { expected: fraction(1) }, graph: flightGraph },
            { id: 21, difficulty: 'medium', question: say('Grafiko berean: esan zein tartetan den gorakorra, konstantea eta beherakorra.', 'En la misma gráfica: indica en qué tramos es creciente, constante y decreciente.', 'في الرسم نفسه: حدّد فترات التزايد والثبات والتناقص.'), solution: say('Gorakorra: $(0,\\,2)$ eta $(3,\\,4)$. Konstantea: $(2,\\,3)$. Beherakorra: $(4,\\,6)$.', 'Creciente: $(0,\\,2)$ y $(3,\\,4)$. Constante: $(2,\\,3)$. Decreciente: $(4,\\,6)$.', 'متزايدة: $(0,\\,2)$ و$(3,\\,4)$. ثابتة: $(2,\\,3)$. متناقصة: $(4,\\,6)$.'), graph: flightGraph },
            { id: 22, difficulty: 'medium', question: say('Zein dira funtzio honen ebakidurak ardatzekin?', '¿Cuáles son los puntos de corte de esta función con los ejes?', 'ما نقاط تقاطع هذه الدالة مع المحورين؟'), solution: say('Y ardatza ($x=0$): $(0,\\,-1)$. X ardatza ($y=0$): $(-1,\\,0)$ eta $(1,\\,0)$.', 'Eje Y ($x=0$): $(0,\\,-1)$. Eje X ($y=0$): $(-1,\\,0)$ y $(1,\\,0)$.', 'محور Y ($x=0$): $(0,\\,-1)$. محور X ($y=0$): $(-1,\\,0)$ و$(1,\\,0)$.'), graph: parabolaGraph },
            { id: 23, difficulty: 'medium', question: say('Funtzio berean: zenbat da bere minimoaren ordenatua?', 'En la misma función: ¿cuánto vale la ordenada de su mínimo?', 'في الدالة نفسها: كم تساوي ترتيبة قيمتها الصغرى؟'), solution: say('Balio txikiena $y=-1$ da, $x=0$ denean: minimoa $(0,\\,-1)$.', 'El menor valor es $y=-1$, cuando $x=0$: mínimo $(0,\\,-1)$.', 'أصغر قيمة $y=-1$ عند $x=0$: القيمة الصغرى $(0,\\,-1)$.'), answer: { expected: fraction(-1) }, graph: parabolaGraph },
            { id: 24, difficulty: 'medium', question: say('Egia ala gezurra: "Funtzio jarraitu batek bi maximo izan ditzake, minimorik gabe".', '¿Verdadero o falso? "Una función continua puede tener dos máximos y ningún mínimo".', 'صح أم خطأ: "يمكن لدالة متصلة أن تملك قيمتين عظميين دون قيمة صغرى".'), solution: say('Gezurra: bi maximoren artean funtzioak behera egin eta gero berriro igo behar du, eta puntu horretan minimo bat dago.', 'Falso: entre dos máximos la función debe bajar y volver a subir, y ahí hay un mínimo.', 'خطأ: بين قيمتين عظميين يجب أن تنخفض الدالة ثم ترتفع، وهناك توجد قيمة صغرى.') },
            { id: 25, difficulty: 'hard', question: say('Bidaia batean, lehen orduan 60 km egiten dira, bigarrenean geldialdia eta hirugarrenean 80 km. Idatzi distantzia metatuaren taula ($x=0,\\,1,\\,2,\\,3$) eta esan zein tartetan den konstantea.', 'En un viaje se recorren 60 km la primera hora, se para la segunda y se recorren 80 km la tercera. Escribe la tabla de la distancia acumulada ($x=0,\\,1,\\,2,\\,3$) y di en qué tramo es constante.', 'في رحلة يُقطع 60 كم في الساعة الأولى، ثم توقف في الثانية، ثم 80 كم في الثالثة. اكتب جدول المسافة المتراكمة ($x=0,\\,1,\\,2,\\,3$) وحدّد فترة الثبات.'), solution: say(`${tableBlock([0, 1, 2, 3], [0, 60, 60, 140])} Konstantea $(1,\\,2)$ tartean da (geldialdia).`, `${tableBlock([0, 1, 2, 3], [0, 60, 60, 140])} Es constante en $(1,\\,2)$ (la parada).`, `${tableBlock([0, 1, 2, 3], [0, 60, 60, 140])} ثابتة في الفترة $(1,\\,2)$ (التوقف).`), solutionGraph: { box: { xMin: 0, xMax: 3, yMin: 0, yMax: 8 }, cell: 30, yUnit: 20, xTitle: say('denbora (h)', 'tiempo (h)', 'الزمن (س)'), yTitle: say('distantzia (km)', 'distancia (km)', 'المسافة (كم)'), curves: [{ points: [[0, 0], [1, 3], [2, 3], [3, 7]] }] } },
            { id: 26, difficulty: 'hard', question: say('$y=x^{2}-6x+8$ funtzioaren X ardatzeko ebakidurak aurkitu nahi dira ($y=0$). Idatzi abzisa txikiena.', 'Se quieren hallar los cortes de $y=x^{2}-6x+8$ con el eje X ($y=0$). Escribe la abscisa menor.', 'نريد إيجاد تقاطعات $y=x^{2}-6x+8$ مع محور X ($y=0$). اكتب أصغر فاصلة.'), solution: same('$\\Delta=36-32=4\\qquad x=\\frac{6\\pm 2}{2}\\ \\to\\ x=2,\\ x=4$'), answer: { expected: fraction(2) } },
            { id: 27, difficulty: 'hard', question: say('Esan funtzio hauek gorakorrak, beherakorrak ala konstanteak diren: $y=2x-1$, $y=-x+3$, $y=4$.', 'Di si estas funciones son crecientes, decrecientes o constantes: $y=2x-1$, $y=-x+3$, $y=4$.', 'قل هل هذه الدوال متزايدة أم متناقصة أم ثابتة: $y=2x-1$ و$y=-x+3$ و$y=4$.'), solution: say('$y=2x-1$: gorakorra ($m=2>0$). $y=-x+3$: beherakorra ($m=-1<0$). $y=4$: konstantea ($m=0$).', '$y=2x-1$: creciente ($m=2>0$). $y=-x+3$: decreciente ($m=-1<0$). $y=4$: constante ($m=0$).', '$y=2x-1$: متزايدة ($m=2>0$). $y=-x+3$: متناقصة ($m=-1<0$). $y=4$: ثابتة ($m=0$).') },
            { id: 50, difficulty: 'hard', question: say('Grafikoan, zenbat $x$ baliotarako da $f(x)=2$? Idatzi zenbat diren.', 'En la gráfica, ¿para cuántos valores de $x$ se cumple $f(x)=2$? Escribe cuántos son.', 'في الرسم، لكم قيمة من $x$ يتحقق $f(x)=2$؟ اكتب عددها.'), solution: say('Marraztu $y=2$ zuzen horizontala: kurba hiru puntutan ebakitzen du, $x=-2$, $x=0$ eta $x=4$. Beraz, 3 balio.', 'Traza la recta horizontal $y=2$: corta a la curva en tres puntos, $x=-2$, $x=0$ y $x=4$. Son 3 valores.', 'ارسم الخط الأفقي $y=2$: يقطع المنحنى في ثلاث نقاط، $x=-2$ و$x=0$ و$x=4$. إنها 3 قيم.'), answer: { expected: fraction(3) }, graph: { box: { xMin: -4, xMax: 5, yMin: -3, yMax: 4 }, cell: 30, curves: [{ points: [[-4, -2], [-3, 0], [-2, 2], [-1, 3], [0, 2], [1, 0], [2, -2], [3, 0], [4, 2], [5, 3]] }] } }
        ]
    },
    {
        id: 'proportional',
        title: say('Proportzionaltasun zuzena eta malda', 'Proporcionalidad directa y pendiente', 'التناسب الطردي والميل'),
        items: [
            { id: 28, difficulty: 'easy', question: say('Zein dira proportzionaltasun zuzeneko funtzioak? a) $y=5x$; b) $y=x+1$; c) $y=-\\frac{x}{2}$; d) $y=3$.', '¿Cuáles son funciones de proporcionalidad directa? a) $y=5x$; b) $y=x+1$; c) $y=-\\frac{x}{2}$; d) $y=3$.', 'أي منها دوال تناسب طردي؟ أ) $y=5x$؛ ب) $y=x+1$؛ ج) $y=-\\frac{x}{2}$؛ د) $y=3$.'), solution: say('a) eta c): $y=mx$ moldekoak dira eta jatorritik pasatzen dira.', 'a) y c): son de la forma $y=mx$ y pasan por el origen.', 'أ) وج): من الصورة $y=mx$ وتمر بنقطة الأصل.') },
            { id: 29, difficulty: 'easy', question: say('$y=mx$ funtzioaren grafikoa $(3,\\,12)$ puntutik pasatzen da. Zenbat da $m$?', 'La gráfica de $y=mx$ pasa por $(3,\\,12)$. ¿Cuánto vale $m$?', 'رسم $y=mx$ يمر بالنقطة $(3,\\,12)$. كم تساوي $m$؟'), solution: same('$12=m\\cdot 3\\ \\to\\ m=12\\mathbin{:}3=4$'), answer: { expected: fraction(4) } },
            { id: 30, difficulty: 'easy', question: say(`${tableBlock([1, 2, 3, 4], [105, 210, 315, 420])} Proportzionaltasun zuzena al da? Zein da konstantea?`, `${tableBlock([1, 2, 3, 4], [105, 210, 315, 420])} ¿Hay proporcionalidad directa? ¿Cuál es la constante?`, `${tableBlock([1, 2, 3, 4], [105, 210, 315, 420])} هل هناك تناسب طردي؟ وما الثابت؟`), solution: same('$\\frac{210}{2}=\\frac{315}{3}=\\frac{420}{4}=105$') },
            { id: 31, difficulty: 'medium', question: say('Zein da $A(-1,\\,2)$ eta $B(3,\\,-6)$ puntuetatik pasatzen den zuzenaren malda?', '¿Cuál es la pendiente de la recta que pasa por $A(-1,\\,2)$ y $B(3,\\,-6)$?', 'ما ميل الخط المار بالنقطتين $A(-1,\\,2)$ و$B(3,\\,-6)$؟'), solution: same('$m=\\frac{-6-2}{3-(-1)}=\\frac{-8}{4}=-2$'), answer: { expected: fraction(-2) } },
            { id: 32, difficulty: 'medium', question: say('Alderatu aldapak: $y=5x$, $y=-7x$, $y=\\frac{x}{2}$. Zein da aldapatsuena? Zein da beherakorra?', 'Compara las inclinaciones: $y=5x$, $y=-7x$, $y=\\frac{x}{2}$. ¿Cuál es la más inclinada? ¿Cuál es decreciente?', 'قارن الانحدارات: $y=5x$ و$y=-7x$ و$y=\\frac{x}{2}$. أيها أشد انحدارًا؟ وأيها متناقص؟'), solution: say('$|m|$ handiena 7 da: $y=-7x$ aldapatsuena da, eta $m<0$ denez beherakorra ere bai.', 'El mayor $|m|$ es 7: $y=-7x$ es la más inclinada y, como $m<0$, también la decreciente.', 'أكبر $|m|$ هو 7: $y=-7x$ هو الأشد انحدارًا، ولأن $m<0$ فهو أيضًا المتناقص.') },
            { id: 33, difficulty: 'medium', question: say('Zein da $(2,\\,5)$ eta $(6,\\,13)$ puntuetatik pasatzen den zuzenaren malda?', '¿Cuál es la pendiente de la recta que pasa por $(2,\\,5)$ y $(6,\\,13)$?', 'ما ميل الخط المار بالنقطتين $(2,\\,5)$ و$(6,\\,13)$؟'), solution: same('$m=\\frac{13-5}{6-2}=\\frac{8}{4}=2$'), answer: { expected: fraction(2) } },
            { id: 34, difficulty: 'medium', question: say('Marraztu $y=2x$, $y=-x$ eta $y=\\frac{x}{3}$. Zer dute amankomunean?', 'Dibuja $y=2x$, $y=-x$ e $y=\\frac{x}{3}$. ¿Qué tienen en común?', 'ارسم $y=2x$ و$y=-x$ و$y=\\frac{x}{3}$. ما القاسم المشترك بينها؟'), solution: say('Hirurak jatorritik $(0,\\,0)$ pasatzen dira ($n=0$). $m>0$ direnak gora doaz; $m<0$ duenak, behera.', 'Las tres pasan por el origen $(0,\\,0)$ ($n=0$). Las de $m>0$ suben; la de $m<0$, baja.', 'الثلاثة تمر بنقطة الأصل $(0,\\,0)$ ($n=0$). ذات $m>0$ تصعد وذات $m<0$ تهبط.'), solutionGraph: { box: { xMin: -4, xMax: 4, yMin: -4, yMax: 4 }, cell: 32, lines: [{ m: 2, n: 0, name: '', at: 1.5 }, { m: -1, n: 0, color: 'second', name: '', at: 3 }, { m: 1 / 3, n: 0, color: 'green', name: 'y = x/3', at: 2 }] } },
            { id: 35, difficulty: 'hard', question: say('Auto bat 90 km/h-ko abiaduran doa: $y=90x$. Zenbat km egiten ditu 2,5 ordutan?', 'Un coche va a 90 km/h: $y=90x$. ¿Cuántos km recorre en 2,5 horas?', 'سيارة تسير بسرعة 90 كم/س: $y=90x$. كم كيلومترًا تقطع في 2.5 ساعة؟'), solution: same('$y=90\\cdot 2{,}5=225$'), answer: { expected: fraction(225) } },
            { id: 36, difficulty: 'hard', question: say('Proportzionaltasun zuzeneko zuzen bat $(4,\\,-2)$ puntutik pasatzen da. Zenbat da $y$ $x=10$ denean?', 'Una recta de proporcionalidad directa pasa por $(4,\\,-2)$. ¿Cuánto vale $y$ cuando $x=10$?', 'خط تناسب طردي يمر بالنقطة $(4,\\,-2)$. كم تساوي $y$ عندما $x=10$؟'), solution: same('$m=\\frac{-2}{4}=-\\frac{1}{2}\\ \\to\\ y=-\\frac{1}{2}\\cdot 10=-5$'), answer: { expected: fraction(-5) } },
            { id: 37, difficulty: 'hard', question: say('$A(1,\\,3)$ eta $B(5,\\,k)$ puntuetatik pasatzen den zuzenaren malda 2 da. Zenbat da $k$?', 'La recta que pasa por $A(1,\\,3)$ y $B(5,\\,k)$ tiene pendiente 2. ¿Cuánto vale $k$?', 'الخط المار بالنقطتين $A(1,\\,3)$ و$B(5,\\,k)$ ميله 2. كم تساوي $k$؟'), solution: same('$\\frac{k-3}{5-1}=2\\ \\to\\ k-3=8\\ \\to\\ k=11$'), answer: { expected: fraction(11) } }
        ]
    },
    {
        id: 'lines',
        title: say('Funtzio linealak eta konstanteak', 'Funciones lineales y constantes', 'الدوال الخطية والثابتة'),
        items: [
            { id: 38, difficulty: 'easy', question: say('Idatzi $m$ eta $n$: a) $y=3x-4$; b) $y=-x+2$; c) $y=5$; d) $y=\\frac{x}{2}$.', 'Escribe $m$ y $n$: a) $y=3x-4$; b) $y=-x+2$; c) $y=5$; d) $y=\\frac{x}{2}$.', 'اكتب $m$ و$n$: أ) $y=3x-4$؛ ب) $y=-x+2$؛ ج) $y=5$؛ د) $y=\\frac{x}{2}$.'), solution: same('a) $m=3,\\ n=-4$; b) $m=-1,\\ n=2$; c) $m=0,\\ n=5$; d) $m=\\frac{1}{2},\\ n=0$') },
            { id: 39, difficulty: 'easy', question: say('$y=-2x+8$ zuzenak X ardatza non ebakitzen du? Idatzi $x$-ren balioa.', '¿Dónde corta la recta $y=-2x+8$ al eje X? Escribe el valor de $x$.', 'أين يقطع الخط $y=-2x+8$ محور X؟ اكتب قيمة $x$.'), solution: same('$0=-2x+8\\ \\to\\ 2x=8\\ \\to\\ x=4$'), answer: { expected: fraction(4) } },
            { id: 40, difficulty: 'easy', question: say('Marraztu $y=2x-3$ bi punturekin.', 'Dibuja $y=2x-3$ con dos puntos.', 'ارسم $y=2x-3$ بنقطتين.'), solution: say('$x=0$: $y=-3$, $(0,\\,-3)$. $x=2$: $y=2\\cdot 2-3=1$, $(2,\\,1)$. Elkartu bi puntuak zuzen batez.', '$x=0$: $y=-3$, $(0,\\,-3)$. $x=2$: $y=2\\cdot 2-3=1$, $(2,\\,1)$. Une los dos puntos con una recta.', '$x=0$: $y=-3$، $(0,\\,-3)$. $x=2$: $y=2\\cdot 2-3=1$، $(2,\\,1)$. صِل النقطتين بخط مستقيم.'), solutionGraph: { box: { xMin: -2, xMax: 4, yMin: -4, yMax: 4 }, cell: 32, lines: [{ m: 2, n: -3 }], points: [{ at: [0, -3], name: '(0, −3)' }, { at: [2, 1], name: '(2, 1)', left: true }] } },
            { id: 41, difficulty: 'medium', question: say('Zuzen bat $(0,\\,2)$ eta $(3,\\,8)$ puntuetatik pasatzen da. Zenbat da $m$?', 'Una recta pasa por $(0,\\,2)$ y $(3,\\,8)$. ¿Cuánto vale $m$?', 'خط يمر بالنقطتين $(0,\\,2)$ و$(3,\\,8)$. كم يساوي $m$؟'), solution: same('$m=\\frac{8-2}{3-0}=\\frac{6}{3}=2$'), answer: { expected: fraction(2) } },
            { id: 42, difficulty: 'medium', question: say('Idatzi $(1,\\,3)$ eta $(3,\\,7)$ puntuetatik pasatzen den zuzenaren ekuazioa.', 'Escribe la ecuación de la recta que pasa por $(1,\\,3)$ y $(3,\\,7)$.', 'اكتب معادلة الخط المار بالنقطتين $(1,\\,3)$ و$(3,\\,7)$.'), solution: same('$m=\\frac{7-3}{3-1}=2\\qquad 3=2\\cdot 1+n\\ \\to\\ n=1\\qquad y=2x+1$') },
            { id: 43, difficulty: 'medium', question: say('Zuzen bat $(2,\\,1)$ eta $(4,\\,5)$ puntuetatik pasatzen da. Zenbat da $n$ ($y=mx+n$)?', 'Una recta pasa por $(2,\\,1)$ y $(4,\\,5)$. ¿Cuánto vale $n$ (en $y=mx+n$)?', 'خط يمر بالنقطتين $(2,\\,1)$ و$(4,\\,5)$. كم تساوي $n$ (في $y=mx+n$)؟'), solution: same('$m=\\frac{5-1}{4-2}=2\\qquad 1=2\\cdot 2+n\\ \\to\\ n=-3$'), answer: { expected: fraction(-3) } },
            { id: 44, difficulty: 'medium', question: say('Idatzi $(-2,\\,3)$ puntutik pasatzen den funtzio konstantearen ekuazioa, eta X ardatzarena.', 'Escribe la ecuación de la función constante que pasa por $(-2,\\,3)$ y la del eje X.', 'اكتب معادلة الدالة الثابتة المارة بالنقطة $(-2,\\,3)$ ومعادلة محور X.'), solution: say('$y=3$ (horizontala, $m=0$). X ardatza: $y=0$.', '$y=3$ (horizontal, $m=0$). El eje X: $y=0$.', '$y=3$ (أفقي، $m=0$). محور X: $y=0$.') },
            { id: 45, difficulty: 'hard', question: say('Ordenagailu-denda batean 15 € ordaintzen dira hasieran eta 6 € orduko: $y=6x+15$. Zenbat € ordaindu behar dira 5 ordutan?', 'En una tienda de alquiler de ordenadores se pagan 15 € al empezar y 6 € por hora: $y=6x+15$. ¿Cuántos € se pagan por 5 horas?', 'في محل لتأجير الحواسيب يُدفع 15 € في البداية و6 € للساعة: $y=6x+15$. كم € يُدفع عن 5 ساعات؟'), solution: same('$y=6\\cdot 5+15=30+15=45$'), answer: { expected: fraction(45) } },
            { id: 46, difficulty: 'hard', question: say('Ordenagailu-denda batean 15 € ordaintzen dira hasieran eta 6 € orduko. Zenbat ordu erabili dira 63 € ordaindu badira?', 'En una tienda de alquiler de ordenadores se pagan 15 € al empezar y 6 € por hora. ¿Cuántas horas se han usado si se han pagado 63 €?', 'في محل لتأجير الحواسيب يُدفع 15 € في البداية و6 € للساعة. كم ساعة استُعملت إذا دُفع 63 €؟'), solution: same('$63=6x+15\\ \\to\\ 6x=48\\ \\to\\ x=8$'), answer: { expected: fraction(8) } },
            { id: 47, difficulty: 'hard', question: say('Bi tarifa: A: $y=4x+10$; B: $y=6x$. Zenbat ordutan dira berdinak?', 'Dos tarifas: A: $y=4x+10$; B: $y=6x$. ¿Cuántas horas deben pasar para que cuesten lo mismo?', 'تعرفتان: A: $y=4x+10$ وB: $y=6x$. بعد كم ساعة يتساويان؟'), solution: same('$4x+10=6x\\ \\to\\ 10=2x\\ \\to\\ x=5$'), answer: { expected: fraction(5) } },
            { id: 48, difficulty: 'hard', question: say('Idatzi $(1,\\,-1)$ eta $(3,\\,5)$ puntuetatik pasatzen den zuzenaren ekuazioa eta egiaztatu.', 'Escribe la ecuación de la recta que pasa por $(1,\\,-1)$ y $(3,\\,5)$ y compruébala.', 'اكتب معادلة الخط المار بالنقطتين $(1,\\,-1)$ و$(3,\\,5)$ وتحقق منها.'), solution: same('$m=\\frac{5-(-1)}{3-1}=3\\qquad -1=3\\cdot 1+n\\ \\to\\ n=-4\\qquad y=3x-4\\qquad 3\\cdot 3-4=5\\ \\checkmark$') },
            { id: 49, difficulty: 'medium', question: say('Idatzi grafikoko bi zuzenen ekuazioak. Zein puntutan ebakitzen dira?', 'Escribe las ecuaciones de las dos rectas de la gráfica. ¿En qué punto se cortan?', 'اكتب معادلتي الخطين في الرسم. في أي نقطة يتقاطعان؟'), solution: say('Urdina: $n=-1$ eta $m=2$, $y=2x-1$. Gorria: $n=4$ eta $m=-\\frac{1}{2}$, $y=-\\frac{1}{2}x+4$. $(2,\\,3)$ puntuan ebakitzen dira: $2\\cdot 2-1=3$ eta $-1+4=3$.', 'Azul: $n=-1$ y $m=2$, $y=2x-1$. Roja: $n=4$ y $m=-\\frac{1}{2}$, $y=-\\frac{1}{2}x+4$. Se cortan en $(2,\\,3)$: $2\\cdot 2-1=3$ y $-1+4=3$.', 'الأزرق: $n=-1$ و$m=2$، $y=2x-1$. الأحمر: $n=4$ و$m=-\\frac{1}{2}$، $y=-\\frac{1}{2}x+4$. يتقاطعان في $(2,\\,3)$: $2\\cdot 2-1=3$ و$-1+4=3$.'), graph: { box: { xMin: -2, xMax: 6, yMin: -3, yMax: 5 }, cell: 30, lines: [{ m: 2, n: -1 }, { m: -0.5, n: 4, color: 'second' }] } }
        ]
    }
]
