import { fraction } from '../../features/unit-v2/math/fraction.ts'
import type { ChallengeItem, DiagnosticQuestion, ExerciseItem, LocalizedText, PracticeItem } from '../../features/unit-v2/types.ts'
import type { LineSpec } from '../dbh4-aplikatuak-errealak/realLineMap.ts'
import { interval } from '../dbh4-aplikatuak-errealak/reals.ts'

/* ==========================================================================
   Zenbaki errealak eta ehunekoak · 4. DBH (akademikoak) — diagnostic, guided
   practice, exercise bank and challenges from Santillana 4.º ESO Académicas
   unit 1 (its activities and final exercises). Every closed answer is a
   single number; money is rounded to the cent and the prompt says so.
   Exercises about intervals carry a LineSpec, drawn under the prompt.
   ========================================================================== */

type WithLine = { line?: LineSpec }
export type PercentDiagnosticQuestion = DiagnosticQuestion & WithLine
export type PercentPracticeItem = PracticeItem & WithLine
export type PercentChallengeItem = ChallengeItem & WithLine
export type PercentExerciseItem = ExerciseItem & WithLine
export interface PercentExerciseSection {
    id: string
    title: LocalizedText
    items: PercentExerciseItem[]
}

/** Arabic writes the decimal point instead of the comma, so {,} becomes . there */
const say = (eu: string, es: string, ar: string): LocalizedText => ({ eu, es, ar: ar.replace(/\{,\}/g, '.') })
/** Same formula everywhere, decimal point in Arabic */
const same = (value: string): LocalizedText => ({ eu: value, es: value, ar: value.replace(/\{,\}/g, '.') })

export const percentDiagnostic: PercentDiagnosticQuestion[] = [
    {
        id: 4101,
        prompt: say('Zer motatakoa da $\\frac{5}{22}$ zatikiaren adierazpen hamartarra?', '¿De qué tipo es la expresión decimal de $\\frac{5}{22}$?', 'ما نوع الصورة العشرية للكسر $\\frac{5}{22}$؟'),
        options: [say('Zehatza', 'Exacta', 'منتهية'), say('Periodiko hutsa', 'Periódica pura', 'دورية بحتة'), say('Periodiko mistoa', 'Periódica mixta', 'دورية مختلطة')],
        correctIndex: 2,
        explanation: say('$22=2\\cdot 11$: 2 eta beste faktore bat → mistoa: $\\frac{5}{22}=0{,}2\\overline{27}$.', '$22=2\\cdot 11$: un 2 y otro factor → mixta: $\\frac{5}{22}=0{,}2\\overline{27}$.', '$22=2\\cdot 11$: العامل 2 وعامل آخر ← مختلطة: $\\frac{5}{22}=0{,}2\\overline{27}$.'),
        topic: 'decimal-kinds'
    },
    {
        id: 4102,
        prompt: say('Zein da $0{,}1\\overline{6}$ zenbakiaren zatiki sortzailea?', '¿Cuál es la fracción generatriz de $0{,}1\\overline{6}$?', 'ما الكسر المولّد للعدد $0{,}1\\overline{6}$؟'),
        options: [same('$\\frac{16}{99}$'), same('$\\frac{1}{6}$'), same('$\\frac{16}{90}$')],
        correctIndex: 1,
        explanation: say('Mistoa: $\\frac{16-1}{90}=\\frac{15}{90}=\\frac{1}{6}$. $\\frac{16}{90}$ ateratzen da aurreperiodoa kentzea ahazten bada.', 'Mixto: $\\frac{16-1}{90}=\\frac{15}{90}=\\frac{1}{6}$. $\\frac{16}{90}$ sale si se olvida restar el anteperiodo.', 'مختلط: $\\frac{16-1}{90}=\\frac{15}{90}=\\frac{1}{6}$. ونحصل على $\\frac{16}{90}$ إذا نسينا طرح ما قبل الدور.'),
        topic: 'generatrix'
    },
    {
        id: 4103,
        prompt: say('Zein zenbaki da irrazionala?', '¿Qué número es irracional?', 'أي عدد غير نسبي؟'),
        options: [same('$\\sqrt{12}$'), same('$\\sqrt{\\frac{9}{4}}$'), same('$2{,}\\overline{45}$')],
        correctIndex: 0,
        explanation: say('12 ez da karratu perfektua: $\\sqrt{12}=3{,}4641\\ldots$ $\\sqrt{\\frac{9}{4}}=\\frac{3}{2}$ eta $2{,}\\overline{45}$ arrazionalak dira.', '12 no es cuadrado perfecto: $\\sqrt{12}=3{,}4641\\ldots$ $\\sqrt{\\frac{9}{4}}=\\frac{3}{2}$ y $2{,}\\overline{45}$ son racionales.', '12 ليس مربعًا كاملًا: $\\sqrt{12}=3{,}4641\\ldots$ أما $\\sqrt{\\frac{9}{4}}=\\frac{3}{2}$ و$2{,}\\overline{45}$ فنسبيان.'),
        topic: 'irrational'
    },
    {
        id: 4104,
        prompt: say('Zein tarte dago marraztuta?', '¿Qué intervalo está dibujado?', 'ما الفترة المرسومة؟'),
        options: [same('$(-3,\\,2]$'), same('$[-3,\\,2)$'), same('$(-3,\\,2)$')],
        correctIndex: 0,
        explanation: say('−3 puntu hutsa da (kanpo) eta 2 betea (barne): $-3<x\\le 2$.', 'El −3 es un punto hueco (fuera) y el 2 relleno (dentro): $-3<x\\le 2$.', '−3 نقطة فارغة (خارج) و2 ممتلئة (داخل): $-3<x\\le 2$.'),
        topic: 'intervals',
        line: { from: -5, to: 4, intervals: [{ value: interval(-3, 2, false, true) }] }
    },
    {
        id: 4105,
        prompt: say('Biribildu $4{,}7569$ ehunenetara.', 'Redondea $4{,}7569$ a las centésimas.', 'قرّب $4{,}7569$ إلى الأجزاء من مئة.'),
        options: [same('$4{,}75$'), same('$4{,}76$'), same('$4{,}8$')],
        correctIndex: 1,
        explanation: say('Kentzen den lehen zifra 6 da (≥ 5): gora, $4{,}76$. $4{,}75$ trunkatzea da.', 'La primera cifra suprimida es 6 (≥ 5): hacia arriba, $4{,}76$. $4{,}75$ es truncar.', 'أول رقم محذوف 6 (≥ 5): إلى الأعلى $4{,}76$. أما $4{,}75$ فبتر.'),
        topic: 'rounding'
    },
    {
        id: 4106,
        prompt: say('$2{,}5$ zenbakiaren ordez 2 hartu da. Zein da errore erlatiboa?', 'Se toma 2 en lugar de $2{,}5$. ¿Cuál es el error relativo?', 'أُخذ 2 بدل $2{,}5$. ما الخطأ النسبي؟'),
        options: [same('$0{,}5$'), same('$0{,}2$'), same('$0{,}25$')],
        correctIndex: 1,
        explanation: say('$E_a=0{,}5$ eta $E_r=\\frac{0{,}5}{2{,}5}=0{,}2$. Benetako balioaz zatitzen da, ez hurbilketaz ($0{,}25$).', '$E_a=0{,}5$ y $E_r=\\frac{0{,}5}{2{,}5}=0{,}2$. Se divide entre el valor real, no entre la aproximación ($0{,}25$).', '$E_a=0{,}5$ و$E_r=\\frac{0{,}5}{2{,}5}=0{,}2$. نقسم على القيمة الحقيقية لا على التقريب ($0{,}25$).'),
        topic: 'errors'
    },
    {
        id: 4107,
        prompt: say('Prezio bat % 20 igo eta gero % 20 jaisten da. Zer gertatzen da?', 'Un precio sube un 20 % y después baja un 20 %. ¿Qué ocurre?', 'يرتفع سعر 20 % ثم ينخفض 20 %. ماذا يحدث؟'),
        options: [say('Berdin geratzen da', 'Queda igual', 'يبقى كما هو'), say('% 4 jaisten da', 'Baja un 4 %', 'ينخفض 4 %'), say('% 4 igotzen da', 'Sube un 4 %', 'يرتفع 4 %')],
        correctIndex: 1,
        explanation: say('Indizeak biderkatzen dira: $1{,}2\\cdot 0{,}8=0{,}96$, hau da, % 4 gutxiago.', 'Los índices se multiplican: $1{,}2\\cdot 0{,}8=0{,}96$, es decir, un 4 % menos.', 'تُضرب المؤشرات: $1{,}2\\cdot 0{,}8=0{,}96$ أي أقل بـ 4 %.'),
        topic: 'chained'
    },
    {
        id: 4108,
        prompt: say('% 25 igo ondoren, sarrera batek 30 € balio du. Zenbat balio zuen?', 'Tras subir un 25 %, una entrada cuesta 30 €. ¿Cuánto costaba?', 'بعد زيادة 25 % صار ثمن تذكرة 30 €. كم كان ثمنها؟'),
        options: [same('$22{,}50$ €'), same('$37{,}50$ €'), same('$24$ €')],
        correctIndex: 2,
        explanation: say('$C\\cdot 1{,}25=30\\ \\to\\ C=30:1{,}25=24$. $22{,}50$ ateratzen da 30en % 25 kentzean, baina ehunekoa hasierakoaren gainean zegoen.', '$C\\cdot 1{,}25=30\\ \\to\\ C=30:1{,}25=24$. $22{,}50$ sale al restar el 25 % de 30, pero el porcentaje era sobre el precio inicial.', '$C\\cdot 1{,}25=30\\ \\to\\ C=30:1{,}25=24$. ونحصل على $22{,}50$ بطرح 25 % من 30، لكن النسبة كانت من السعر الأولي.'),
        topic: 'percent-inverse'
    }
]

export const percentPractice: PercentPracticeItem[] = [
    { id: 1, stage: 'rational', prompt: say('Idatzi $0{,}375$ zatiki laburtezin gisa.', 'Escribe $0{,}375$ como fracción irreducible.', 'اكتب $0{,}375$ كسرًا غير قابل للاختزال.'), expected: fraction(3, 8), answerForm: 'simplified', hint: say('Hiru hamartar: izendatzailea 1000.', 'Tres decimales: denominador 1000.', 'ثلاث منازل: المقام 1000.'), explanation: same('$0{,}375=\\frac{375}{1000}=\\frac{3}{8}$') },
    { id: 2, stage: 'rational', prompt: say('Idatzi $13{,}\\overline{46}$ zatiki gisa.', 'Escribe $13{,}\\overline{46}$ como fracción.', 'اكتب $13{,}\\overline{46}$ كسرًا.'), expected: fraction(1333, 99), hint: say('Periodiko hutsa, bi zifra: izendatzailea 99.', 'Periódico puro de dos cifras: denominador 99.', 'دوري بحت من رقمين: المقام 99.'), explanation: same('$\\frac{1346-13}{99}=\\frac{1333}{99}$') },
    { id: 3, stage: 'rational', prompt: say('Idatzi $2{,}9\\overline{4}$ zatiki laburtezin gisa.', 'Escribe $2{,}9\\overline{4}$ como fracción irreducible.', 'اكتب $2{,}9\\overline{4}$ كسرًا غير قابل للاختزال.'), expected: fraction(53, 18), answerForm: 'simplified', hint: say('Mistoa: izendatzailea 90.', 'Mixto: denominador 90.', 'مختلط: المقام 90.'), explanation: same('$\\frac{294-29}{90}=\\frac{265}{90}=\\frac{53}{18}$') },
    { id: 4, stage: 'rational', prompt: say('Kalkulatu $\\frac{4}{5}$ eta $\\frac{5}{6}$ zatikien erdiko puntua.', 'Calcula el punto medio de $\\frac{4}{5}$ y $\\frac{5}{6}$.', 'احسب نقطة المنتصف بين $\\frac{4}{5}$ و$\\frac{5}{6}$.'), expected: fraction(49, 60), hint: say('Batu eta zatitu 2z: izendatzaile komuna 30.', 'Suma y divide entre 2: denominador común 30.', 'اجمع واقسم على 2: المقام المشترك 30.'), explanation: same('$\\frac{1}{2}\\left(\\frac{24}{30}+\\frac{25}{30}\\right)=\\frac{49}{60}$') },
    { id: 5, stage: 'reals', prompt: say('$\\sqrt{26}$ kokatzeko, $26=5^{2}+b^{2}$ idazten da, $b$ naturala izanik. Zenbat da $b$?', 'Para situar $\\sqrt{26}$ se escribe $26=5^{2}+b^{2}$, con $b$ natural. ¿Cuánto vale $b$?', 'لوضع $\\sqrt{26}$ نكتب $26=5^{2}+b^{2}$ حيث $b$ طبيعي. كم تساوي $b$؟'), expected: fraction(1), hint: say('Kendu 25.', 'Resta 25.', 'اطرح 25.'), explanation: same('$26-25=1=1^{2}$') },
    { id: 6, stage: 'reals', prompt: say('$\\sqrt{40}$ bi zenbaki oso jarraituren artean dago. Idatzi txikiena.', '$\\sqrt{40}$ está entre dos enteros consecutivos. Escribe el menor.', '$\\sqrt{40}$ يقع بين عددين صحيحين متتاليين. اكتب الأصغر.'), expected: fraction(6), hint: say('Bilatu 40ren inguruko karratuak.', 'Busca los cuadrados cercanos a 40.', 'ابحث عن المربعات القريبة من 40.'), explanation: same('$36<40<49\\ \\to\\ 6<\\sqrt{40}<7$') },
    { id: 7, stage: 'reals', prompt: say('$\\frac{\\pi}{2}=1{,}5707\\ldots$ bi hamarren jarraituren artean dago. Idatzi txikiena.', '$\\frac{\\pi}{2}=1{,}5707\\ldots$ está entre dos décimas consecutivas. Escribe la menor.', '$\\frac{\\pi}{2}=1{,}5707\\ldots$ يقع بين عُشرين متتاليين. اكتب الأصغر.'), expected: fraction(3, 2), hint: say('Begiratu lehen hamartarrari.', 'Mira la primera cifra decimal.', 'انظر إلى أول رقم عشري.'), explanation: same('$1{,}5<\\frac{\\pi}{2}<1{,}6$') },
    { id: 8, stage: 'reals', prompt: say('Zenbat dira irrazionalak? $\\sqrt{16}$, $\\sqrt{20}$, $\\frac{\\pi}{5}$, $0{,}\\overline{3}$, $\\sqrt{\\frac{9}{4}}$, $1+\\sqrt{8}$', '¿Cuántos son irracionales? $\\sqrt{16}$, $\\sqrt{20}$, $\\frac{\\pi}{5}$, $0{,}\\overline{3}$, $\\sqrt{\\frac{9}{4}}$, $1+\\sqrt{8}$', 'كم منها غير نسبي؟ $\\sqrt{16}$، $\\sqrt{20}$، $\\frac{\\pi}{5}$، $0{,}\\overline{3}$، $\\sqrt{\\frac{9}{4}}$، $1+\\sqrt{8}$'), expected: fraction(3), hint: say('Sinplifikatu lehenik: $\\sqrt{16}=4$ eta $\\sqrt{\\frac{9}{4}}=\\frac{3}{2}$.', 'Simplifica primero: $\\sqrt{16}=4$ y $\\sqrt{\\frac{9}{4}}=\\frac{3}{2}$.', 'بسّط أولًا: $\\sqrt{16}=4$ و$\\sqrt{\\frac{9}{4}}=\\frac{3}{2}$.'), explanation: say('Irrazionalak: $\\sqrt{20}$, $\\frac{\\pi}{5}$ eta $1+\\sqrt{8}$: 3.', 'Irracionales: $\\sqrt{20}$, $\\frac{\\pi}{5}$ y $1+\\sqrt{8}$: 3.', 'غير النسبية: $\\sqrt{20}$ و$\\frac{\\pi}{5}$ و$1+\\sqrt{8}$: 3.') },
    { id: 9, stage: 'approx', prompt: say('Zenbat zenbaki oso daude $(-4,\\,0]$ tartean?', '¿Cuántos números enteros hay en el intervalo $(-4,\\,0]$?', 'كم عددًا صحيحًا في الفترة $(-4,\\,0]$؟'), expected: fraction(4), hint: say('−4 kanpo; 0 barne.', 'El −4 queda fuera; el 0 dentro.', '−4 خارج و0 داخل.'), explanation: say('$-3,\\,-2,\\,-1,\\,0$: 4 zenbaki.', '$-3,\\,-2,\\,-1,\\,0$: 4 números.', '$-3,\\,-2,\\,-1,\\,0$: 4 أعداد.'), line: { from: -6, to: 2, intervals: [{ value: interval(-4, 0, false, true) }] } },
    { id: 10, stage: 'approx', prompt: say('$A=(-5,\\,3]$ eta $B=(-1,\\,+\\infty)$. $A\\cap B=(a,\\,3]$. Zenbat da $a$?', '$A=(-5,\\,3]$ y $B=(-1,\\,+\\infty)$. $A\\cap B=(a,\\,3]$. ¿Cuánto vale $a$?', '$A=(-5,\\,3]$ و$B=(-1,\\,+\\infty)$. $A\\cap B=(a,\\,3]$. كم تساوي $a$؟'), expected: fraction(-1), hint: say('Ebakidura: bi marrak gainjartzen diren zatia.', 'La intersección: donde se solapan las dos bandas.', 'التقاطع: حيث يتداخل الشريطان.'), explanation: same('$A\\cap B=(-1,\\,3]$'), line: { from: -7, to: 5, intervals: [{ value: interval(-5, 3, false, true) }, { value: interval(-1, null, false, false), color: 'second', lift: 22 }] } },
    { id: 11, stage: 'approx', prompt: say('Biribildu $5{,}23888\\ldots$ ehunenetara.', 'Redondea $5{,}23888\\ldots$ a las centésimas.', 'قرّب $5{,}23888\\ldots$ إلى الأجزاء من مئة.'), expected: fraction(131, 25), hint: say('Kentzen den lehen zifra 8 da.', 'La primera cifra suprimida es 8.', 'أول رقم محذوف 8.'), explanation: same('$5{,}23888\\ldots\\approx 5{,}24$') },
    { id: 12, stage: 'approx', prompt: say('$\\frac{17}{3}$ zenbakiaren ordez $5{,}7$ hartzen da. Zein da errore absolutua? (Zatiki gisa.)', 'Se toma $5{,}7$ en lugar de $\\frac{17}{3}$. ¿Cuál es el error absoluto? (En forma de fracción.)', 'نأخذ $5{,}7$ بدل $\\frac{17}{3}$. ما الخطأ المطلق؟ (على صورة كسر.)'), expected: fraction(1, 30), hint: say('$5{,}7=\\frac{57}{10}$; izendatzaile komuna 30.', '$5{,}7=\\frac{57}{10}$; denominador común 30.', '$5{,}7=\\frac{57}{10}$؛ المقام المشترك 30.'), explanation: same('$\\frac{57}{10}-\\frac{17}{3}=\\frac{171-170}{30}=\\frac{1}{30}$') },
    { id: 13, stage: 'percent', prompt: say('Kalkulatu 48ren % 8,5.', 'Calcula el 8,5 % de 48.', 'احسب 8.5 % من 48.'), expected: fraction(102, 25), hint: say('% 8,5 = 0,085.', '8,5 % = 0,085.', '8.5 % = 0.085.'), explanation: same('$0{,}085\\cdot 48=4{,}08$') },
    { id: 14, stage: 'percent', prompt: say('94 €-ko jaka bat % 15 merkatu dute. Zenbat balio du orain (€)?', 'Una chaqueta de 94 € se rebaja un 15 %. ¿Cuánto cuesta ahora (€)?', 'سترة ثمنها 94 € خُفّضت 15 %. كم ثمنها الآن (€)؟'), expected: fraction(799, 10), hint: say('Indizea: $1-0{,}15$.', 'Índice: $1-0{,}15$.', 'المؤشر: $1-0{,}15$.'), explanation: same('$94\\cdot 0{,}85=79{,}9$') },
    { id: 15, stage: 'percent', prompt: say('Prezio bat % 30 igo eta gero % 15 jaitsi da. Guztira, zer ehuneko igo da?', 'Un precio sube un 30 % y después baja un 15 %. En total, ¿qué porcentaje ha subido?', 'ارتفع سعر 30 % ثم انخفض 15 %. ما نسبة الزيادة الكلية؟'), expected: fraction(21, 2), hint: say('Biderkatu indizeak.', 'Multiplica los índices.', 'اضرب المؤشرين.'), explanation: same('$1{,}3\\cdot 0{,}85=1{,}105\\ \\to\\ 10{,}5\\,\\%$') },
    { id: 16, stage: 'percent', prompt: say('% 20ko beherapenaren ondoren, beroki batek 120 € balio du. Zein zen hasierako prezioa (€)?', 'Tras una rebaja del 20 %, un abrigo cuesta 120 €. ¿Cuál era el precio inicial (€)?', 'بعد خصم 20 % صار ثمن معطف 120 €. ما السعر الأولي (€)؟'), expected: fraction(150), hint: say('$0{,}8\\cdot C=120$.', '$0{,}8\\cdot C=120$.', '$0{,}8\\cdot C=120$.'), explanation: same('$C=120:0{,}8=150$') },
    { id: 17, stage: 'interest', prompt: say('2000 € uzten ditugu % 3an 5 urtez, interes sinplean. Zenbat interes (€)?', 'Ingresamos 2000 € al 3 % durante 5 años a interés simple. ¿Cuántos intereses (€)?', 'نودع 2000 € بنسبة 3 % لمدة 5 أعوام بفائدة بسيطة. كم الفائدة (€)؟'), expected: fraction(300), hint: say('$I=\\frac{C\\cdot r\\cdot t}{100}$.', '$I=\\frac{C\\cdot r\\cdot t}{100}$.', '$I=\\frac{C\\cdot r\\cdot t}{100}$.'), explanation: same('$I=\\frac{2000\\cdot 3\\cdot 5}{100}=300$') },
    { id: 18, stage: 'interest', prompt: say('Kapital batek % 3,6an 5 urtez 540 € interes sinple eman ditu. Zein da kapitala (€)?', 'Un capital al 3,6 % durante 5 años ha dado 540 € de interés simple. ¿Cuál es el capital (€)?', 'أعطى رأس مال بنسبة 3.6 % لمدة 5 أعوام فائدة بسيطة قدرها 540 €. ما رأس المال (€)؟'), expected: fraction(3000), hint: say('Askatu $C$: $C=\\frac{100\\cdot I}{r\\cdot t}$.', 'Despeja $C$: $C=\\frac{100\\cdot I}{r\\cdot t}$.', 'اعزل $C$: $C=\\frac{100\\cdot I}{r\\cdot t}$.'), explanation: same('$C=\\frac{100\\cdot 540}{3{,}6\\cdot 5}=\\frac{54\\,000}{18}=3000$') },
    { id: 19, stage: 'interest', prompt: say('3400 € % 3,4an 2 urtez, interes konposatuan. Zenbat izango dira? (Zentimoetara.)', '3400 € al 3,4 % durante 2 años a interés compuesto. ¿En cuánto se convierten? (A los céntimos.)', '3400 € بنسبة 3.4 % لمدة عامين بفائدة مركبة. كم تصبح؟ (إلى السنت.)'), expected: fraction(363513, 100), hint: say('$C_f=C_i\\cdot 1{,}034^{2}$.', '$C_f=C_i\\cdot 1{,}034^{2}$.', '$C_f=C_i\\cdot 1{,}034^{2}$.'), explanation: same('$C_f=3400\\cdot 1{,}034^{2}=3635{,}1304\\approx 3635{,}13$') },
    { id: 20, stage: 'interest', prompt: say('1000 € % 2an 5 urtez: Fernandok interes konposatuan eta Estherrek sinplean. Zenbat € gehiago irabazten ditu Fernandok? (Zentimoetara.)', '1000 € al 2 % durante 5 años: Fernando a interés compuesto y Esther a simple. ¿Cuántos € más gana Fernando? (A los céntimos.)', '1000 € بنسبة 2 % لمدة 5 أعوام: فرناندو بفائدة مركبة وإستير ببسيطة. كم يورو يربح فرناندو أكثر؟ (إلى السنت.)'), expected: fraction(102, 25), hint: say('Konposatua: $1000\\cdot 1{,}02^{5}$. Sinplea: $\\frac{1000\\cdot 2\\cdot 5}{100}$.', 'Compuesto: $1000\\cdot 1{,}02^{5}$. Simple: $\\frac{1000\\cdot 2\\cdot 5}{100}$.', 'المركبة: $1000\\cdot 1{,}02^{5}$. البسيطة: $\\frac{1000\\cdot 2\\cdot 5}{100}$.'), explanation: same('$1000\\cdot 1{,}02^{5}\\approx 1104{,}08\\qquad 104{,}08-100=4{,}08$') }
]

export const percentChallenges: PercentChallengeItem[] = [
    { id: 101, stage: 'rational', context: 'starter', points: 10, prompt: say('Aplikatu zatiki sortzailearen araua $1{,}\\overline{9}$ zenbakiari. Zenbat da?', 'Aplica la regla de la fracción generatriz a $1{,}\\overline{9}$. ¿Cuánto vale?', 'طبّق قاعدة الكسر المولّد على $1{,}\\overline{9}$. كم يساوي؟'), expected: fraction(2), hint: say('Periodiko hutsa: $\\frac{19-1}{9}$.', 'Periódico puro: $\\frac{19-1}{9}$.', 'دوري بحت: $\\frac{19-1}{9}$.'), explanation: same('$\\frac{19-1}{9}=\\frac{18}{9}=2$') },
    { id: 102, stage: 'rational', context: 'advanced', points: 20, prompt: same('$0{,}\\overline{3}+0{,}1\\overline{6}$'), expected: fraction(1, 2), hint: say('Pasa biak zatiki: $\\frac{3}{9}$ eta $\\frac{16-1}{90}$.', 'Pasa los dos a fracción: $\\frac{3}{9}$ y $\\frac{16-1}{90}$.', 'حوّل العددين إلى كسرين: $\\frac{3}{9}$ و$\\frac{16-1}{90}$.'), explanation: same('$\\frac{3}{9}+\\frac{15}{90}=\\frac{1}{3}+\\frac{1}{6}=\\frac{1}{2}$') },
    { id: 103, stage: 'rational', context: 'master', points: 30, prompt: say('120 izendatzailea duten zenbat zatiki daude $\\frac{4}{5}$ eta $\\frac{5}{6}$ artean (muturrak kontatu gabe)?', '¿Cuántas fracciones de denominador 120 hay entre $\\frac{4}{5}$ y $\\frac{5}{6}$ (sin contar los extremos)?', 'كم كسرًا مقامه 120 يقع بين $\\frac{4}{5}$ و$\\frac{5}{6}$ (دون عدّ الطرفين)؟'), expected: fraction(3), hint: say('Idatzi biak 120 izendatzailearekin.', 'Escribe las dos con denominador 120.', 'اكتب الكسرين بالمقام 120.'), explanation: say('$\\frac{4}{5}=\\frac{96}{120}$ eta $\\frac{5}{6}=\\frac{100}{120}$: tartean $\\frac{97}{120}$, $\\frac{98}{120}$ eta $\\frac{99}{120}$: 3.', '$\\frac{4}{5}=\\frac{96}{120}$ y $\\frac{5}{6}=\\frac{100}{120}$: en medio $\\frac{97}{120}$, $\\frac{98}{120}$ y $\\frac{99}{120}$: 3.', '$\\frac{4}{5}=\\frac{96}{120}$ و$\\frac{5}{6}=\\frac{100}{120}$: بينهما $\\frac{97}{120}$ و$\\frac{98}{120}$ و$\\frac{99}{120}$: 3.') },
    { id: 104, stage: 'reals', context: 'starter', points: 10, prompt: say('$\\sqrt{117}$ kokatzeko, $117=a^{2}+6^{2}$ idazten da, $a$ naturala izanik. Zenbat da $a$?', 'Para situar $\\sqrt{117}$ se escribe $117=a^{2}+6^{2}$, con $a$ natural. ¿Cuánto vale $a$?', 'لوضع $\\sqrt{117}$ نكتب $117=a^{2}+6^{2}$ حيث $a$ طبيعي. كم تساوي $a$؟'), expected: fraction(9), hint: say('Kendu 36.', 'Resta 36.', 'اطرح 36.'), explanation: same('$117-36=81=9^{2}$') },
    { id: 105, stage: 'reals', context: 'advanced', points: 20, prompt: say('$\\sqrt{1}$, $\\sqrt{2}$, …, $\\sqrt{20}$ zenbakien artean, zenbat dira irrazionalak?', 'Entre $\\sqrt{1}$, $\\sqrt{2}$, …, $\\sqrt{20}$, ¿cuántos son irracionales?', 'من بين $\\sqrt{1}$ و$\\sqrt{2}$ و… و$\\sqrt{20}$ كم عددًا غير نسبي؟'), expected: fraction(16), hint: say('Arrazionalak karratu perfektuen erroak dira: 1, 4, 9, 16.', 'Son racionales las raíces de los cuadrados perfectos: 1, 4, 9, 16.', 'النسبية هي جذور المربعات الكاملة: 1 و4 و9 و16.'), explanation: say('20 erro, horietatik 4 arrazionalak: $20-4=16$.', '20 raíces, de las que 4 son racionales: $20-4=16$.', '20 جذرًا منها 4 نسبية: $20-4=16$.') },
    { id: 106, stage: 'reals', context: 'master', points: 30, prompt: say('$2\\sqrt{6}=4{,}898979\\ldots$ bi ehunen jarraituren artean dago. Idatzi handiena.', '$2\\sqrt{6}=4{,}898979\\ldots$ está entre dos centésimas consecutivas. Escribe la mayor.', '$2\\sqrt{6}=4{,}898979\\ldots$ يقع بين جزأين متتاليين من مئة. اكتب الأكبر.'), expected: fraction(49, 10), hint: say('Bi hamartar: $4{,}89$ eta hurrengoa.', 'Dos decimales: $4{,}89$ y la siguiente.', 'منزلتان: $4{,}89$ والتالية.'), explanation: same('$4{,}89<2\\sqrt{6}<4{,}90$') },
    { id: 107, stage: 'approx', context: 'starter', points: 10, prompt: say('$A=(-\\infty,\\,3)$ eta $B=(-3,\\,+\\infty)$. Zenbat zenbaki oso daude $A\\cap B$ tartean?', '$A=(-\\infty,\\,3)$ y $B=(-3,\\,+\\infty)$. ¿Cuántos enteros hay en $A\\cap B$?', '$A=(-\\infty,\\,3)$ و$B=(-3,\\,+\\infty)$. كم عددًا صحيحًا في $A\\cap B$؟'), expected: fraction(5), hint: say('Ebakidura: $(-3,\\,3)$.', 'La intersección: $(-3,\\,3)$.', 'التقاطع: $(-3,\\,3)$.'), explanation: say('$A\\cap B=(-3,\\,3)$: −2, −1, 0, 1 eta 2: 5.', '$A\\cap B=(-3,\\,3)$: −2, −1, 0, 1 y 2: 5.', '$A\\cap B=(-3,\\,3)$: −2 و−1 و0 و1 و2: 5.'), line: { from: -6, to: 6, intervals: [{ value: interval(null, 3, false, false) }, { value: interval(-3, null, false, false), color: 'second', lift: 22 }] } },
    { id: 108, stage: 'approx', context: 'advanced', points: 20, prompt: say('Biribildu $1{,}\\overline{9}$ ehunenetara.', 'Redondea $1{,}\\overline{9}$ a las centésimas.', 'قرّب $1{,}\\overline{9}$ إلى الأجزاء من مئة.'), expected: fraction(2), hint: say('$1{,}999\\ldots$: kentzen den lehen zifra 9 da, eta gehitutako 1ak bederatziak eramaten ditu.', '$1{,}999\\ldots$: la primera cifra suprimida es 9, y el 1 que se suma arrastra los nueves.', '$1{,}999\\ldots$: أول رقم محذوف 9، والواحد المضاف يحمل التسعات.'), explanation: same('$1{,}999\\ldots\\approx 2{,}00$') },
    { id: 109, stage: 'approx', context: 'master', points: 30, prompt: say('Zenbaki bat milarenetara biribiltzen da. Gehienez, zenbatekoa izan daiteke errore absolutua?', 'Un número se redondea a las milésimas. Como mucho, ¿cuánto puede valer el error absoluto?', 'يُقرَّب عدد إلى الأجزاء من ألف. ما أكبر قيمة ممكنة للخطأ المطلق؟'), expected: fraction(1, 2000), hint: say('Errore-bornea: azken ordenaren unitate erdia.', 'Cota de error: media unidad del último orden.', 'حدّ الخطأ: نصف وحدة آخر منزلة.'), explanation: same('$\\frac{1}{2}\\cdot 0{,}001=0{,}0005$') },
    { id: 110, stage: 'percent', context: 'starter', points: 10, prompt: say('Inkesta batean 860 pertsonak erantzun dute: 301ek bai, 172k ez, eta gainerakoek ez dakite. Zer ehunekok ez daki?', 'En una encuesta responden 860 personas: 301 sí, 172 no y el resto no sabe. ¿Qué porcentaje no sabe?', 'في استطلاع أجاب 860 شخصًا: 301 نعم و172 لا والبقية لا يعرفون. ما نسبة من لا يعرفون؟'), expected: fraction(45), hint: say('Lehenik, zenbat ez dakiten.', 'Primero, cuántos no saben.', 'أولًا عدد من لا يعرفون.'), explanation: same('$860-(301+172)=387\\qquad\\frac{387}{860}=0{,}45\\ \\to\\ 45\\,\\%$') },
    { id: 111, stage: 'percent', context: 'advanced', points: 20, prompt: say('Kantitate bat % 16 igo eta gero % 60 jaisten da. Hasierakoaren zer ehuneko geratzen da?', 'Una cantidad sube un 16 % y después baja un 60 %. ¿Qué porcentaje de la inicial queda?', 'ترتفع كمية 16 % ثم تنخفض 60 %. ما النسبة الباقية من الأولية؟'), expected: fraction(232, 5), hint: say('Indizeak: $1{,}16$ eta $0{,}40$.', 'Índices: $1{,}16$ y $0{,}40$.', 'المؤشرات: $1{,}16$ و$0{,}40$.'), explanation: same('$1{,}16\\cdot 0{,}40=0{,}464\\ \\to\\ 46{,}4\\,\\%$') },
    { id: 112, stage: 'percent', context: 'master', points: 30, prompt: say('Prezio bat % 25 igo da. Zer ehuneko jaitsi behar da hasierako prezioa berreskuratzeko?', 'Un precio ha subido un 25 %. ¿Qué porcentaje hay que bajarlo para volver al precio inicial?', 'ارتفع سعر 25 %. بأي نسبة يجب خفضه ليعود إلى السعر الأولي؟'), expected: fraction(20), hint: say('Bilatu $1{,}25\\cdot I=1$ egiten duen indizea.', 'Busca el índice que cumple $1{,}25\\cdot I=1$.', 'ابحث عن المؤشر الذي يحقق $1{,}25\\cdot I=1$.'), explanation: same('$I=\\frac{1}{1{,}25}=0{,}8\\ \\to\\ 20\\,\\%$') },
    { id: 113, stage: 'interest', context: 'advanced', points: 20, prompt: say('Zer interes-tasa sinplerekin ematen dute 20 000 €-k 2400 € 3 urtetan (%)?', '¿A qué rédito simple dan 20 000 € unos intereses de 2400 € en 3 años (%)?', 'بأي معدل بسيط يعطي 20 000 € فائدة قدرها 2400 € في 3 أعوام (%)؟'), expected: fraction(4), hint: say('$r=\\frac{100\\cdot I}{C\\cdot t}$.', '$r=\\frac{100\\cdot I}{C\\cdot t}$.', '$r=\\frac{100\\cdot I}{C\\cdot t}$.'), explanation: same('$r=\\frac{100\\cdot 2400}{20\\,000\\cdot 3}=4$') },
    { id: 114, stage: 'interest', context: 'master', points: 30, prompt: say('Kapital batek % 5ean 3 urtez interes konposatuan 1576,25 € interes eman ditu. Zein zen kapitala (€)?', 'Un capital al 5 % durante 3 años a interés compuesto ha generado 1576,25 € de intereses. ¿Cuál era el capital (€)?', 'ولّد رأس مال بنسبة 5 % لمدة 3 أعوام بفائدة مركبة فوائد قدرها 1576.25 €. ما رأس المال (€)؟'), expected: fraction(10000), hint: say('$C_i\\cdot 1{,}05^{3}-C_i=1576{,}25$.', '$C_i\\cdot 1{,}05^{3}-C_i=1576{,}25$.', '$C_i\\cdot 1{,}05^{3}-C_i=1576{,}25$.'), explanation: same('$1{,}05^{3}-1=0{,}157625\\qquad C_i=\\frac{1576{,}25}{0{,}157625}=10\\,000$') }
]

export const percentExerciseBank: PercentExerciseSection[] = [
    {
        id: 'rational',
        title: say('Zenbaki arrazionalak', 'Números racionales', 'الأعداد النسبية'),
        items: [
            { id: 1, difficulty: 'easy', question: say('Sailkatu: $2{,}333\\ldots$, $2{,}345$, $6{,}00999\\ldots$ eta $2{,}435555\\ldots$', 'Clasifica: $2{,}333\\ldots$, $2{,}345$, $6{,}00999\\ldots$ y $2{,}435555\\ldots$', 'صنّف: $2{,}333\\ldots$ و$2{,}345$ و$6{,}00999\\ldots$ و$2{,}435555\\ldots$'), solution: say('Periodiko hutsa, zehatza, periodiko mistoa eta periodiko mistoa.', 'Periódico puro, exacto, periódico mixto y periódico mixto.', 'دوري بحت، منتهٍ، دوري مختلط، دوري مختلط.') },
            { id: 2, difficulty: 'easy', question: say('Idatzi $35{,}47$ zatiki gisa.', 'Escribe $35{,}47$ como fracción.', 'اكتب $35{,}47$ كسرًا.'), solution: same('$35{,}47=\\frac{3547}{100}$'), answer: { expected: fraction(3547, 100) } },
            { id: 3, difficulty: 'medium', question: say('Idatzi $0{,}1\\overline{6}$ zatiki laburtezin gisa.', 'Escribe $0{,}1\\overline{6}$ como fracción irreducible.', 'اكتب $0{,}1\\overline{6}$ كسرًا غير قابل للاختزال.'), solution: same('$\\frac{16-1}{90}=\\frac{15}{90}=\\frac{1}{6}$'), answer: { expected: fraction(1, 6), form: 'simplified' } },
            { id: 4, difficulty: 'medium', question: say('Idatzi $5{,}2\\overline{31}$ zatiki gisa.', 'Escribe $5{,}2\\overline{31}$ como fracción.', 'اكتب $5{,}2\\overline{31}$ كسرًا.'), solution: same('$\\frac{5231-52}{990}=\\frac{5179}{990}$'), answer: { expected: fraction(5179, 990) } },
            { id: 5, difficulty: 'medium', question: say('Zatiketa egin gabe, esan zer hamartar mota ematen duten: $\\frac{3}{40}$, $\\frac{11}{3}$, $\\frac{5}{500}$ eta $\\frac{7}{90}$.', 'Sin dividir, di qué tipo de decimal dan: $\\frac{3}{40}$, $\\frac{11}{3}$, $\\frac{5}{500}$ y $\\frac{7}{90}$.', 'دون قسمة، اذكر نوع العشري: $\\frac{3}{40}$ و$\\frac{11}{3}$ و$\\frac{5}{500}$ و$\\frac{7}{90}$.'), solution: say('$40=2^{3}\\cdot 5$: zehatza. 3: hutsa. $\\frac{5}{500}=\\frac{1}{100}$: zehatza. $90=2\\cdot 3^{2}\\cdot 5$: mistoa ($0{,}0\\overline{7}$).', '$40=2^{3}\\cdot 5$: exacto. 3: puro. $\\frac{5}{500}=\\frac{1}{100}$: exacto. $90=2\\cdot 3^{2}\\cdot 5$: mixto ($0{,}0\\overline{7}$).', '$40=2^{3}\\cdot 5$: منتهٍ. 3: بحت. $\\frac{5}{500}=\\frac{1}{100}$: منتهٍ. $90=2\\cdot 3^{2}\\cdot 5$: مختلط ($0{,}0\\overline{7}$).') },
            { id: 6, difficulty: 'medium', question: say('Ordenatu txikienetik handienera: $5{,}69$; $5{,}556$; $5{,}966$; $5{,}665$; $5{,}96$; $5{,}565$.', 'Ordena de menor a mayor: $5{,}69$; $5{,}556$; $5{,}966$; $5{,}665$; $5{,}96$; $5{,}565$.', 'رتّب من الأصغر إلى الأكبر: $5{,}69$؛ $5{,}556$؛ $5{,}966$؛ $5{,}665$؛ $5{,}96$؛ $5{,}565$.'), solution: same('$5{,}556<5{,}565<5{,}665<5{,}69<5{,}96<5{,}966$') },
            { id: 7, difficulty: 'hard', question: say('Ordenatu handienetik txikienera: $0{,}\\overline{14}$, $0{,}4\\overline{12}$, $0{,}\\overline{1}$, $0{,}14$, $0{,}4\\overline{1}$.', 'Ordena de mayor a menor: $0{,}\\overline{14}$, $0{,}4\\overline{12}$, $0{,}\\overline{1}$, $0{,}14$, $0{,}4\\overline{1}$.', 'رتّب من الأكبر إلى الأصغر: $0{,}\\overline{14}$ و$0{,}4\\overline{12}$ و$0{,}\\overline{1}$ و$0{,}14$ و$0{,}4\\overline{1}$.'), solution: say('Idatzi zifra batzuk: $0{,}41212\\ldots>0{,}41111\\ldots>0{,}1414\\ldots>0{,}14>0{,}111\\ldots$', 'Escribe varias cifras: $0{,}41212\\ldots>0{,}41111\\ldots>0{,}1414\\ldots>0{,}14>0{,}111\\ldots$', 'اكتب عدة أرقام: $0{,}41212\\ldots>0{,}41111\\ldots>0{,}1414\\ldots>0{,}14>0{,}111\\ldots$') },
            { id: 8, difficulty: 'medium', question: say('Idatzi hiru zatiki $\\frac{5}{4}$ eta $\\frac{6}{4}$ artean.', 'Escribe tres fracciones entre $\\frac{5}{4}$ y $\\frac{6}{4}$.', 'اكتب ثلاثة كسور بين $\\frac{5}{4}$ و$\\frac{6}{4}$.'), solution: say('Biderkatu gaiak 4z: $\\frac{20}{16}<\\frac{21}{16}<\\frac{22}{16}<\\frac{23}{16}<\\frac{24}{16}$.', 'Multiplica los términos por 4: $\\frac{20}{16}<\\frac{21}{16}<\\frac{22}{16}<\\frac{23}{16}<\\frac{24}{16}$.', 'اضرب الحدين في 4: $\\frac{20}{16}<\\frac{21}{16}<\\frac{22}{16}<\\frac{23}{16}<\\frac{24}{16}$.') },
            { id: 9, difficulty: 'hard', question: same('$0{,}\\overline{3}+0{,}\\overline{6}$'), solution: say('$\\frac{3}{9}+\\frac{6}{9}=\\frac{9}{9}=1$: $0{,}999\\ldots$ eta 1 zenbaki bera dira.', '$\\frac{3}{9}+\\frac{6}{9}=\\frac{9}{9}=1$: $0{,}999\\ldots$ y 1 son el mismo número.', '$\\frac{3}{9}+\\frac{6}{9}=\\frac{9}{9}=1$: العددان $0{,}999\\ldots$ و1 عدد واحد.'), answer: { expected: fraction(1) } },
            { id: 10, difficulty: 'hard', question: say('Idatzi $-27{,}3\\overline{5}$ zatiki laburtezin gisa.', 'Escribe $-27{,}3\\overline{5}$ como fracción irreducible.', 'اكتب $-27{,}3\\overline{5}$ كسرًا غير قابل للاختزال.'), solution: same('$-\\frac{2735-273}{90}=-\\frac{2462}{90}=-\\frac{1231}{45}$'), answer: { expected: fraction(-1231, 45), form: 'simplified' } }
        ]
    },
    {
        id: 'reals',
        title: say('Irrazionalak eta zuzen erreala', 'Irracionales y recta real', 'غير النسبية والمستقيم الحقيقي'),
        items: [
            { id: 11, difficulty: 'easy', question: say('Sailkatu: 41, $\\sqrt{17}$, $\\frac{8}{49}$ eta $-87$.', 'Clasifica: 41, $\\sqrt{17}$, $\\frac{8}{49}$ y $-87$.', 'صنّف: 41 و$\\sqrt{17}$ و$\\frac{8}{49}$ و$-87$.'), solution: say('41 naturala; $\\sqrt{17}=4{,}1231\\ldots$ irrazionala; $\\frac{8}{49}$ arrazionala; $-87$ osoa.', '41 natural; $\\sqrt{17}=4{,}1231\\ldots$ irracional; $\\frac{8}{49}$ racional; $-87$ entero.', '41 طبيعي؛ $\\sqrt{17}=4{,}1231\\ldots$ غير نسبي؛ $\\frac{8}{49}$ نسبي؛ $-87$ صحيح.') },
            { id: 12, difficulty: 'easy', question: say('Arrazionala ala irrazionala? $1+\\sqrt{8}$, $\\sqrt{1+8}$, $\\pi^{2}$ eta $24{,}\\overline{23}$.', '¿Racional o irracional? $1+\\sqrt{8}$, $\\sqrt{1+8}$, $\\pi^{2}$ y $24{,}\\overline{23}$.', 'نسبي أم غير نسبي؟ $1+\\sqrt{8}$ و$\\sqrt{1+8}$ و$\\pi^{2}$ و$24{,}\\overline{23}$.'), solution: say('$1+\\sqrt{8}$ irrazionala; $\\sqrt{9}=3$ arrazionala; $\\pi^{2}=9{,}8696\\ldots$ irrazionala; $24{,}\\overline{23}=\\frac{2399}{99}$ arrazionala.', '$1+\\sqrt{8}$ irracional; $\\sqrt{9}=3$ racional; $\\pi^{2}=9{,}8696\\ldots$ irracional; $24{,}\\overline{23}=\\frac{2399}{99}$ racional.', '$1+\\sqrt{8}$ غير نسبي؛ $\\sqrt{9}=3$ نسبي؛ $\\pi^{2}=9{,}8696\\ldots$ غير نسبي؛ $24{,}\\overline{23}=\\frac{2399}{99}$ نسبي.') },
            { id: 13, difficulty: 'medium', question: say('Kalkulatu $\\sqrt{9+16}$ eta konparatu $\\sqrt{9}+\\sqrt{16}$-rekin.', 'Calcula $\\sqrt{9+16}$ y compáralo con $\\sqrt{9}+\\sqrt{16}$.', 'احسب $\\sqrt{9+16}$ وقارنه بـ $\\sqrt{9}+\\sqrt{16}$.'), solution: same('$\\sqrt{9+16}=\\sqrt{25}=5\\qquad\\sqrt{9}+\\sqrt{16}=3+4=7$'), answer: { expected: fraction(5) } },
            { id: 14, difficulty: 'medium', question: say('Nola kokatzen dira $\\sqrt{10}$, $\\sqrt{17}$ eta $\\sqrt{26}$ zuzenean?', '¿Cómo se sitúan $\\sqrt{10}$, $\\sqrt{17}$ y $\\sqrt{26}$ en la recta?', 'كيف نضع $\\sqrt{10}$ و$\\sqrt{17}$ و$\\sqrt{26}$ على المستقيم؟'), solution: say('Bi karraturen batura gisa: $10=3^{2}+1^{2}$, $17=4^{2}+1^{2}$, $26=5^{2}+1^{2}$. Katetoak marraztu, eta hipotenusa konpasarekin zuzenera eraman.', 'Como suma de dos cuadrados: $10=3^{2}+1^{2}$, $17=4^{2}+1^{2}$, $26=5^{2}+1^{2}$. Se dibujan los catetos y se lleva la hipotenusa a la recta con el compás.', 'مجموع مربعين: $10=3^{2}+1^{2}$ و$17=4^{2}+1^{2}$ و$26=5^{2}+1^{2}$. نرسم الضلعين وننقل الوتر إلى المستقيم بالفرجار.') },
            { id: 15, difficulty: 'medium', question: say('Nola kokatzen da $\\frac{17}{3}$ zuzenean Talesen teoremarekin?', '¿Cómo se sitúa $\\frac{17}{3}$ en la recta con el teorema de Tales?', 'كيف نضع $\\frac{17}{3}$ على المستقيم بمبرهنة طاليس؟'), solution: say('$\\frac{17}{3}=5+\\frac{2}{3}$: zatitu $[5,\\,6]$ hiru zati berdinetan zuzen zeihar baten eta paraleloen bidez, eta hartu bigarren marka.', '$\\frac{17}{3}=5+\\frac{2}{3}$: divide $[5,\\,6]$ en tres partes iguales con una recta oblicua y paralelas, y toma la segunda marca.', '$\\frac{17}{3}=5+\\frac{2}{3}$: قسّم $[5,\\,6]$ ثلاثة أجزاء متساوية بمستقيم مائل ومتوازيات، وخذ العلامة الثانية.') },
            { id: 16, difficulty: 'medium', question: say('$\\sqrt{40}$ bi zenbaki oso jarraituren artean dago. Zein da txikiena?', '$\\sqrt{40}$ está entre dos enteros consecutivos. ¿Cuál es el menor?', '$\\sqrt{40}$ بين عددين صحيحين متتاليين. ما الأصغر؟'), solution: same('$36<40<49\\ \\to\\ 6<\\sqrt{40}<7$'), answer: { expected: fraction(6) } },
            { id: 17, difficulty: 'hard', question: say('Ordenatu handienetik txikienera: $\\sqrt{10}$, $2\\pi$, $3{,}\\overline{4}$, $\\sqrt[3]{31}$, $\\sqrt{\\frac{256}{25}}$, $3{,}\\overline{123}$.', 'Ordena de mayor a menor: $\\sqrt{10}$, $2\\pi$, $3{,}\\overline{4}$, $\\sqrt[3]{31}$, $\\sqrt{\\frac{256}{25}}$, $3{,}\\overline{123}$.', 'رتّب من الأكبر إلى الأصغر: $\\sqrt{10}$ و$2\\pi$ و$3{,}\\overline{4}$ و$\\sqrt[3]{31}$ و$\\sqrt{\\frac{256}{25}}$ و$3{,}\\overline{123}$.'), solution: say('Hamartarrak: $6{,}28$; $3{,}444$; $3{,}2$; $3{,}162$; $3{,}141$; $3{,}123$. Beraz: $2\\pi>3{,}\\overline{4}>\\sqrt{\\frac{256}{25}}>\\sqrt{10}>\\sqrt[3]{31}>3{,}\\overline{123}$.', 'En decimal: $6{,}28$; $3{,}444$; $3{,}2$; $3{,}162$; $3{,}141$; $3{,}123$. Así: $2\\pi>3{,}\\overline{4}>\\sqrt{\\frac{256}{25}}>\\sqrt{10}>\\sqrt[3]{31}>3{,}\\overline{123}$.', 'بالعشري: $6{,}28$؛ $3{,}444$؛ $3{,}2$؛ $3{,}162$؛ $3{,}141$؛ $3{,}123$. إذن: $2\\pi>3{,}\\overline{4}>\\sqrt{\\frac{256}{25}}>\\sqrt{10}>\\sqrt[3]{31}>3{,}\\overline{123}$.') },
            { id: 18, difficulty: 'hard', question: say('$2\\sqrt{6}=4{,}898979\\ldots$ Hurbildu ehunenetara gutxiagoz.', '$2\\sqrt{6}=4{,}898979\\ldots$ Aproxímalo a las centésimas por defecto.', '$2\\sqrt{6}=4{,}898979\\ldots$ قرّبه إلى الأجزاء من مئة بالنقصان.'), solution: same('$4{,}89<2\\sqrt{6}<4{,}90$'), answer: { expected: fraction(489, 100) } },
            { id: 19, difficulty: 'hard', question: say('Egia ala gezurra? Bi irrazionalen batura beti da irrazionala.', '¿Verdadero o falso? La suma de dos irracionales siempre es irracional.', 'صح أم خطأ؟ مجموع عددين غير نسبيين غير نسبي دائمًا.'), solution: say('Gezurra: $\\pi+(-\\pi)=0$ eta $(1+\\sqrt{2})+(1-\\sqrt{2})=2$ arrazionalak dira.', 'Falso: $\\pi+(-\\pi)=0$ y $(1+\\sqrt{2})+(1-\\sqrt{2})=2$ son racionales.', 'خطأ: $\\pi+(-\\pi)=0$ و$(1+\\sqrt{2})+(1-\\sqrt{2})=2$ نسبيان.') },
            { id: 20, difficulty: 'hard', question: say('Karratu baten aldea $\\sqrt{8}$ cm da. Zenbat cm neurtzen du diagonalak?', 'El lado de un cuadrado mide $\\sqrt{8}$ cm. ¿Cuántos cm mide la diagonal?', 'ضلع مربع $\\sqrt{8}$ سم. كم سم طول القطر؟'), solution: same('$d=\\sqrt{8+8}=\\sqrt{16}=4$'), answer: { expected: fraction(4) } }
        ]
    },
    {
        id: 'approx',
        title: say('Tarteak eta hurbilketak', 'Intervalos y aproximaciones', 'الفترات والتقريب'),
        items: [
            { id: 21, difficulty: 'easy', question: say('Idatzi desberdintza gisa: $(4,\\,8)$, $(-\\infty,\\,2)$ eta $[1,\\,5)$.', 'Escribe como desigualdad: $(4,\\,8)$, $(-\\infty,\\,2)$ y $[1,\\,5)$.', 'اكتب على صورة متباينة: $(4,\\,8)$ و$(-\\infty,\\,2)$ و$[1,\\,5)$.'), solution: same('$4<x<8\\qquad x<2\\qquad 1\\le x<5$') },
            { id: 22, difficulty: 'easy', question: say('Idatzi tarte gisa: $-4<x\\le 0$, $1\\le x\\le 2$ eta $10>x>4$.', 'Escribe como intervalo: $-4<x\\le 0$, $1\\le x\\le 2$ y $10>x>4$.', 'اكتب على صورة فترة: $-4<x\\le 0$ و$1\\le x\\le 2$ و$10>x>4$.'), solution: same('$(-4,\\,0]\\qquad [1,\\,2]\\qquad (4,\\,10)$') },
            { id: 23, difficulty: 'medium', question: say('Zenbat zenbaki oso daude $[-3,\\,4)$ tartean?', '¿Cuántos números enteros hay en el intervalo $[-3,\\,4)$?', 'كم عددًا صحيحًا في الفترة $[-3,\\,4)$؟'), solution: say('$-3,\\,-2,\\,-1,\\,0,\\,1,\\,2,\\,3$: 7.', '$-3,\\,-2,\\,-1,\\,0,\\,1,\\,2,\\,3$: 7.', '$-3,\\,-2,\\,-1,\\,0,\\,1,\\,2,\\,3$: 7.'), answer: { expected: fraction(7) }, line: { from: -5, to: 6, intervals: [{ value: interval(-3, 4, true, false) }] } },
            { id: 24, difficulty: 'medium', question: say('$A=[-5,\\,3]$ eta $B=(-1,\\,+\\infty)$. Kalkulatu $A\\cup B$ eta $A\\cap B$.', '$A=[-5,\\,3]$ y $B=(-1,\\,+\\infty)$. Calcula $A\\cup B$ y $A\\cap B$.', '$A=[-5,\\,3]$ و$B=(-1,\\,+\\infty)$. احسب $A\\cup B$ و$A\\cap B$.'), solution: same('$A\\cup B=[-5,\\,+\\infty)\\qquad A\\cap B=(-1,\\,3]$'), line: { from: -7, to: 6, intervals: [{ value: interval(-5, 3, true, true) }, { value: interval(-1, null, false, false), color: 'second', lift: 22 }] } },
            { id: 25, difficulty: 'medium', question: say('Kalkulatu: $(-\\infty,\\,3)\\cap(-3,\\,+\\infty)$, $[0,\\,1)\\cap[1,\\,2]$ eta $(-\\infty,\\,1]\\cup(0,\\,+\\infty)$.', 'Calcula: $(-\\infty,\\,3)\\cap(-3,\\,+\\infty)$, $[0,\\,1)\\cap[1,\\,2]$ y $(-\\infty,\\,1]\\cup(0,\\,+\\infty)$.', 'احسب: $(-\\infty,\\,3)\\cap(-3,\\,+\\infty)$ و$[0,\\,1)\\cap[1,\\,2]$ و$(-\\infty,\\,1]\\cup(0,\\,+\\infty)$.'), solution: same('$(-3,\\,3)\\qquad\\emptyset\\qquad\\mathbb{R}$') },
            { id: 26, difficulty: 'easy', question: say('Hurbildu $0{,}\\overline{12}$ ehunenetara, gutxiagoz eta gehiagoz.', 'Aproxima $0{,}\\overline{12}$ a las centésimas por defecto y por exceso.', 'قرّب $0{,}\\overline{12}$ إلى الأجزاء من مئة بالنقصان وبالزيادة.'), solution: say('$0{,}1212\\ldots$: gutxiagoz $0{,}12$; gehiagoz $0{,}13$.', '$0{,}1212\\ldots$: por defecto $0{,}12$; por exceso $0{,}13$.', '$0{,}1212\\ldots$: بالنقصان $0{,}12$؛ بالزيادة $0{,}13$.') },
            { id: 27, difficulty: 'medium', question: say('Biribildu $4{,}7569$ ehunenetara eta kalkulatu errore absolutua.', 'Redondea $4{,}7569$ a las centésimas y calcula el error absoluto.', 'قرّب $4{,}7569$ إلى الأجزاء من مئة واحسب الخطأ المطلق.'), solution: same('$4{,}7569\\approx 4{,}76\\qquad E_a=4{,}76-4{,}7569=0{,}0031$'), answer: { expected: fraction(31, 10000) } },
            { id: 28, difficulty: 'medium', question: say('Biribildu $2{,}\\overline{3}$ hamarrenetara. Zein da errore absolutua? (Zatiki gisa.)', 'Redondea $2{,}\\overline{3}$ a las décimas. ¿Cuál es el error absoluto? (Como fracción.)', 'قرّب $2{,}\\overline{3}$ إلى الأعشار. ما الخطأ المطلق؟ (على صورة كسر.)'), solution: same('$2{,}\\overline{3}=\\frac{7}{3}\\approx 2{,}3\\qquad \\frac{7}{3}-\\frac{23}{10}=\\frac{70-69}{30}=\\frac{1}{30}$'), answer: { expected: fraction(1, 30) } },
            { id: 29, difficulty: 'hard', question: say('$1{,}468$ zenbakirako, $1{,}5$ ala $1{,}4$ da hobea? Eman hurbilketa onenaren errore absolutua.', 'Para $1{,}468$, ¿es mejor $1{,}5$ o $1{,}4$? Da el error absoluto de la mejor aproximación.', 'للعدد $1{,}468$ أيهما أفضل $1{,}5$ أم $1{,}4$؟ أعطِ الخطأ المطلق لأفضل تقريب.'), solution: say('$1{,}5-1{,}468=0{,}032$ eta $1{,}468-1{,}4=0{,}068$: hobea da $1{,}5$, $E_a=0{,}032$ duena.', '$1{,}5-1{,}468=0{,}032$ y $1{,}468-1{,}4=0{,}068$: es mejor $1{,}5$, con $E_a=0{,}032$.', '$1{,}5-1{,}468=0{,}032$ و$1{,}468-1{,}4=0{,}068$: الأفضل $1{,}5$ بخطأ $E_a=0{,}032$.'), answer: { expected: fraction(4, 125) } },
            { id: 30, difficulty: 'hard', question: say('Neurketa bat hamarrenetara biribiltzen da. Zein da errore-bornea?', 'Una medida se redondea a las décimas. ¿Cuál es la cota de error?', 'يُقرَّب قياس إلى الأعشار. ما حدّ الخطأ؟'), solution: same('$\\frac{1}{2}\\cdot 0{,}1=0{,}05$'), answer: { expected: fraction(1, 20) } }
        ]
    },
    {
        id: 'percent',
        title: say('Ehunekoak', 'Porcentajes', 'النسب المئوية'),
        items: [
            { id: 31, difficulty: 'easy', question: say('Kalkulatu 220ren % 16.', 'Calcula el 16 % de 220.', 'احسب 16 % من 220.'), solution: same('$0{,}16\\cdot 220=35{,}2$'), answer: { expected: fraction(176, 5) } },
            { id: 32, difficulty: 'easy', question: say('25 zenbat da 200en ehunekotan?', '¿Qué porcentaje es 25 de 200?', 'ما النسبة التي يمثلها 25 من 200؟'), solution: same('$\\frac{25}{200}=0{,}125\\ \\to\\ 12{,}5\\,\\%$'), answer: { expected: fraction(25, 2) } },
            { id: 33, difficulty: 'easy', question: say('Kalkulatu 400en % 6aren % 20.', 'Calcula el 20 % del 6 % de 400.', 'احسب 20 % من 6 % من 400.'), solution: same('$0{,}2\\cdot 0{,}06\\cdot 400=4{,}8$'), answer: { expected: fraction(24, 5) } },
            { id: 34, difficulty: 'medium', question: say('18 000 €-ko auto bati % 20ko deskontua egin diote eta gero % 21 BEZ gehitu. Zenbat ordaindu da (€)?', 'A un coche de 18 000 € le hacen un descuento del 20 % y después le suman el 21 % de IVA. ¿Cuánto se paga (€)?', 'سيارة ثمنها 18 000 € حصلت على خصم 20 % ثم أضيفت ضريبة 21 %. كم يُدفع (€)؟'), solution: same('$18\\,000\\cdot 0{,}8\\cdot 1{,}21=17\\,424$'), answer: { expected: fraction(17424) } },
            { id: 35, difficulty: 'medium', question: say('Heriotza-tasa % 12,5 jaitsi da eta aurten 98 pertsona hil dira. Zenbat hil ziren iaz?', 'La mortalidad ha bajado un 12,5 % y este año han muerto 98 personas. ¿Cuántas murieron el año pasado?', 'انخفضت الوفيات 12.5 % وتوفي هذا العام 98 شخصًا. كم توفي العام الماضي؟'), solution: same('$0{,}875\\cdot C=98\\ \\to\\ C=98:0{,}875=112$'), answer: { expected: fraction(112) } },
            { id: 36, difficulty: 'medium', question: say('Kantitate baten % 20aren % 112 112 da. Zein da kantitatea?', 'El 112 % del 20 % de una cantidad es 112. ¿Cuál es la cantidad?', '112 % من 20 % من كمية يساوي 112. ما الكمية؟'), solution: same('$1{,}12\\cdot 0{,}2=0{,}224\\qquad C=\\frac{112}{0{,}224}=500$'), answer: { expected: fraction(500) } },
            { id: 37, difficulty: 'medium', question: say('45 €-ko artikulu bat % 30 garestitu eta gero % 15 merkatu da. Zenbat balio du (€)?', 'Un artículo de 45 € sube un 30 % y después baja un 15 %. ¿Cuánto cuesta (€)?', 'سلعة ثمنها 45 € ارتفعت 30 % ثم انخفضت 15 %. كم ثمنها (€)؟'), solution: same('$45\\cdot 1{,}3\\cdot 0{,}85=49{,}725$'), answer: { expected: fraction(1989, 40) } },
            { id: 38, difficulty: 'hard', question: say('Produktu bati % 25eko eta gero % 30eko beherapenak egin dizkiote, eta 125 € balio du. Zenbat balio zuen? (Zentimoetara.)', 'A un producto le aplican una rebaja del 25 % y luego otra del 30 %, y cuesta 125 €. ¿Cuánto valía? (A los céntimos.)', 'طُبّق على منتج خصم 25 % ثم خصم 30 % وصار ثمنه 125 €. كم كان ثمنه؟ (إلى السنت.)'), solution: same('$0{,}75\\cdot 0{,}70=0{,}525\\qquad C=\\frac{125}{0{,}525}\\approx 238{,}10$'), answer: { expected: fraction(23810, 100) } },
            { id: 39, difficulty: 'hard', question: say('Prezio bat bi aldiz igo da % 30. Guztira, zer ehuneko igo da?', 'Un precio sube dos veces un 30 %. En total, ¿qué porcentaje ha subido?', 'ارتفع سعر 30 % مرتين. ما نسبة الزيادة الكلية؟'), solution: same('$1{,}3\\cdot 1{,}3=1{,}69\\ \\to\\ 69\\,\\%$'), answer: { expected: fraction(69) } },
            { id: 40, difficulty: 'hard', question: say('26 000 ikasletatik % 94k probak gainditzen dituzte; horien % 25ek lehen urtean uzten dute, eta gainerakoen % 90ek amaitzen dute. Zenbatek amaitzen dute?', 'De 26 000 estudiantes, el 94 % aprueba las pruebas; de ellos, el 25 % abandona el primer año, y el 90 % del resto termina. ¿Cuántos terminan?', 'من 26 000 طالب ينجح 94 %؛ ومنهم ينسحب 25 % في العام الأول، وينهي 90 % من الباقين. كم طالبًا ينهي؟'), solution: same('$0{,}94\\cdot 26\\,000=24\\,440\\qquad 0{,}75\\cdot 24\\,440=18\\,330\\qquad 0{,}9\\cdot 18\\,330=16\\,497$'), answer: { expected: fraction(16497) } }
        ]
    },
    {
        id: 'interest',
        title: say('Interes sinplea eta konposatua', 'Interés simple y compuesto', 'الفائدة البسيطة والمركبة'),
        items: [
            { id: 41, difficulty: 'easy', question: say('2000 € % 3an 5 urtez, interes sinplean. Zenbat interes (€)?', '2000 € al 3 % durante 5 años a interés simple. ¿Cuántos intereses (€)?', '2000 € بنسبة 3 % لمدة 5 أعوام بفائدة بسيطة. كم الفائدة (€)؟'), solution: same('$I=\\frac{2000\\cdot 3\\cdot 5}{100}=300$'), answer: { expected: fraction(300) } },
            { id: 42, difficulty: 'easy', question: say('30 € % 3an 7 urtez, interes sinplean. Zenbat interes (€)?', '30 € al 3 % durante 7 años a interés simple. ¿Cuántos intereses (€)?', '30 € بنسبة 3 % لمدة 7 أعوام بفائدة بسيطة. كم الفائدة (€)؟'), solution: same('$I=\\frac{30\\cdot 3\\cdot 7}{100}=6{,}3\\qquad 30+6{,}3=36{,}3$'), answer: { expected: fraction(63, 10) } },
            { id: 43, difficulty: 'medium', question: say('670 € % 3an 30 hilabetez, interes sinplean. Zenbat interes (€)?', '670 € al 3 % durante 30 meses a interés simple. ¿Cuántos intereses (€)?', '670 € بنسبة 3 % لمدة 30 شهرًا بفائدة بسيطة. كم الفائدة (€)؟'), solution: same('$I=\\frac{670\\cdot 3\\cdot\\frac{30}{12}}{100}=50{,}25$'), answer: { expected: fraction(201, 4) } },
            { id: 44, difficulty: 'medium', question: say('Kapital batek % 3,6an 5 urtez 490 € interes sinple eman ditu. Zein da kapitala? (Zentimoetara.)', 'Un capital al 3,6 % durante 5 años da 490 € de interés simple. ¿Cuál es el capital? (A los céntimos.)', 'رأس مال بنسبة 3.6 % لمدة 5 أعوام يعطي 490 € فائدة بسيطة. ما رأس المال؟ (إلى السنت.)'), solution: same('$490=\\frac{C\\cdot 3{,}6\\cdot 5}{100}\\ \\to\\ C=\\frac{490}{0{,}18}\\approx 2722{,}22$'), answer: { expected: fraction(272222, 100) } },
            { id: 45, difficulty: 'medium', question: say('Zer interes-tasa sinplerekin ematen dute 20 000 €-k 2400 € 3 urtetan (%)?', '¿A qué rédito simple dan 20 000 € unos intereses de 2400 € en 3 años (%)?', 'بأي معدل بسيط يعطي 20 000 € فائدة 2400 € في 3 أعوام (%)؟'), solution: same('$2400=\\frac{20\\,000\\cdot r\\cdot 3}{100}\\ \\to\\ r=\\frac{2400}{600}=4$'), answer: { expected: fraction(4) } },
            { id: 46, difficulty: 'medium', question: say('600 € % 3,4an 5 urtez, interes konposatuan. Zenbat izango dira? (Zentimoetara.)', '600 € al 3,4 % durante 5 años a interés compuesto. ¿En cuánto se convierten? (A los céntimos.)', '600 € بنسبة 3.4 % لمدة 5 أعوام بفائدة مركبة. كم تصبح؟ (إلى السنت.)'), solution: same('$C_f=600\\cdot 1{,}034^{5}\\approx 709{,}18$'), answer: { expected: fraction(70918, 100) } },
            { id: 47, difficulty: 'medium', question: say('1000 € % 7an 5 urtez. Kalkulatu amaierako kapitala interes sinplean eta konposatuan. (Konposatuarena, zentimoetara.)', '1000 € al 7 % durante 5 años. Calcula el capital final a interés simple y compuesto. (El compuesto, a los céntimos.)', '1000 € بنسبة 7 % لمدة 5 أعوام. احسب رأس المال النهائي بالفائدة البسيطة والمركبة. (المركبة إلى السنت.)'), solution: same('$1000+\\frac{1000\\cdot 7\\cdot 5}{100}=1350\\qquad 1000\\cdot 1{,}07^{5}\\approx 1402{,}55$'), answer: { expected: fraction(140255, 100) } },
            { id: 48, difficulty: 'hard', question: say('5000 € % 4an 3 urtez. Zenbat € gehiago ematen ditu interes konposatuak sinpleak baino?', '5000 € al 4 % durante 3 años. ¿Cuántos € más da el interés compuesto que el simple?', '5000 € بنسبة 4 % لمدة 3 أعوام. كم يورو تعطي الفائدة المركبة أكثر من البسيطة؟'), solution: same('$5000\\cdot 1{,}04^{3}=5624{,}32\\qquad 5000+600=5600\\qquad 5624{,}32-5600=24{,}32$'), answer: { expected: fraction(2432, 100) } },
            { id: 49, difficulty: 'hard', question: say('Kapital batek % 2an 2 urtez interes konposatuan 101 € interes eman ditu. Zein zen kapitala (€)?', 'Un capital al 2 % durante 2 años a interés compuesto genera 101 € de intereses. ¿Cuál era el capital (€)?', 'ولّد رأس مال بنسبة 2 % لمدة عامين بفائدة مركبة 101 € فوائد. ما رأس المال (€)؟'), solution: same('$1{,}02^{2}-1=0{,}0404\\qquad C_i=\\frac{101}{0{,}0404}=2500$'), answer: { expected: fraction(2500) } },
            { id: 50, difficulty: 'hard', question: say('1000 € % 2an, urteko aldiekin, interes konposatuan. Urte eta erdira ateratzen dira. Zenbat jasotzen da (€)?', '1000 € al 2 % en periodos anuales a interés compuesto. Se sacan al año y medio. ¿Cuánto se recibe (€)?', '1000 € بنسبة 2 % بفترات سنوية وفائدة مركبة. سُحبت بعد عام ونصف. كم يُستلم (€)؟'), solution: say('Urte osoa, konposatua: $1000\\cdot 1{,}02=1020$. Azken sei hilabeteak, sinplea: $I=\\frac{1020\\cdot 2\\cdot\\frac{6}{12}}{100}=10{,}2$. Guztira $1020+10{,}2=1030{,}2$.', 'El año completo, compuesto: $1000\\cdot 1{,}02=1020$. Los seis meses finales, simple: $I=\\frac{1020\\cdot 2\\cdot\\frac{6}{12}}{100}=10{,}2$. En total $1020+10{,}2=1030{,}2$.', 'العام الكامل مركبة: $1000\\cdot 1{,}02=1020$. والأشهر الستة الأخيرة بسيطة: $I=\\frac{1020\\cdot 2\\cdot\\frac{6}{12}}{100}=10{,}2$. المجموع $1020+10{,}2=1030{,}2$.'), answer: { expected: fraction(5151, 5) } }
        ]
    }
]
