import { fraction } from '../../features/unit-v2/math/fraction.ts'
import type { ChallengeItem, DiagnosticQuestion, ExerciseSection, LocalizedText, PracticeItem } from '../../features/unit-v2/types.ts'

/* ==========================================================================
   Zenbaki arrazionalak · 3. DBH — diagnostic, guided practice, exercise bank
   and challenges from Santillana 3.º ESO unit 1 (its activities and final
   exercises). Every closed answer is a single number; "irreducible" asks
   for the simplified form.
   ========================================================================== */

/** Arabic writes the decimal point instead of the comma, so {,} becomes . there */
const say = (eu: string, es: string, ar: string): LocalizedText => ({ eu, es, ar: ar.replace(/\{,\}/g, '.') })
/** Same formula everywhere, decimal point in Arabic */
const same = (value: string): LocalizedText => ({ eu: value, es: value, ar: value.replace(/\{,\}/g, '.') })

const kinds = [say('Zehatza', 'Exacto', 'منتهٍ'), say('Periodiko hutsa', 'Periódico puro', 'دوري بحت'), say('Periodiko mistoa', 'Periódico mixto', 'دوري مختلط')]

export const rationalsDiagnostic: DiagnosticQuestion[] = [
    {
        id: 3101,
        prompt: say('Zein zatiki da $\\frac{-6}{5}$-en baliokidea?', '¿Qué fracción es equivalente a $\\frac{-6}{5}$?', 'أي كسر يكافئ $\\frac{-6}{5}$؟'),
        options: [same('$\\frac{-18}{15}$'), same('$\\frac{18}{15}$'), same('$\\frac{-6}{15}$')],
        correctIndex: 0,
        explanation: say('Gurutzeko biderkadurak: $-6\\cdot 15=-90$ eta $5\\cdot(-18)=-90$. Berdinak dira.', 'Productos cruzados: $-6\\cdot 15=-90$ y $5\\cdot(-18)=-90$. Son iguales.', 'الضرب التبادلي: $-6\\cdot 15=-90$ و$5\\cdot(-18)=-90$. متساويان.'),
        topic: 'equivalent'
    },
    {
        id: 3102,
        prompt: say('Zein da $\\frac{84}{126}$ zatikiaren zatiki laburtezina?', '¿Cuál es la fracción irreducible de $\\frac{84}{126}$?', 'ما الكسر غير القابل للاختزال لـ $\\frac{84}{126}$؟'),
        options: [same('$\\frac{14}{21}$'), same('$\\frac{42}{63}$'), same('$\\frac{2}{3}$')],
        correctIndex: 2,
        explanation: say('z.k.h.(84, 126) = 42: $\\frac{84:42}{126:42}=\\frac{2}{3}$. Besteak baliokideak dira, baina oraindik sinplifika daitezke.', 'm.c.d.(84, 126) = 42: $\\frac{84:42}{126:42}=\\frac{2}{3}$. Las otras son equivalentes, pero aún se pueden simplificar.', 'ق.م.أ.(84، 126) = 42: $\\frac{84:42}{126:42}=\\frac{2}{3}$. والأخريان مكافئتان لكن يمكن اختزالهما.'),
        topic: 'simplify'
    },
    {
        id: 3103,
        prompt: say('Zein da handiena?', '¿Cuál es la mayor?', 'أيها الأكبر؟'),
        options: [same('$-\\frac{3}{4}$'), same('$-\\frac{2}{3}$'), same('$-\\frac{5}{6}$')],
        correctIndex: 1,
        explanation: say('Izendatzaile komuna 12: $-\\frac{9}{12}$, $-\\frac{8}{12}$, $-\\frac{10}{12}$. Negatiboetan, handiena zerotik hurbilen dagoena da.', 'Denominador común 12: $-\\frac{9}{12}$, $-\\frac{8}{12}$, $-\\frac{10}{12}$. En los negativos, la mayor es la más cercana a cero.', 'المقام المشترك 12: $-\\frac{9}{12}$ و$-\\frac{8}{12}$ و$-\\frac{10}{12}$. وفي السالبة الأكبر هو الأقرب إلى الصفر.'),
        topic: 'compare'
    },
    {
        id: 3104,
        prompt: same('$\\frac{1}{2}-\\frac{3}{4}+\\frac{5}{6}=\\ ?$'),
        options: [same('$\\frac{7}{12}$'), same('$\\frac{1}{4}$'), same('$-\\frac{1}{12}$')],
        correctIndex: 0,
        explanation: say('m.k.t. = 12: $\\frac{6-9+10}{12}=\\frac{7}{12}$. $\\frac{1}{4}=\\frac{3}{12}$ zenbakitzaileak eta izendatzaileak batzean ateratzen da.', 'm.c.m. = 12: $\\frac{6-9+10}{12}=\\frac{7}{12}$. $\\frac{1}{4}=\\frac{3}{12}$ sale al sumar numeradores y denominadores.', 'م.م.أ. = 12: $\\frac{6-9+10}{12}=\\frac{7}{12}$. ونحصل على $\\frac{1}{4}=\\frac{3}{12}$ بجمع البسوط والمقامات.'),
        topic: 'add-sub'
    },
    {
        id: 3105,
        prompt: same('$\\left(-\\frac{4}{5}\\right):\\frac{2}{3}=\\ ?$'),
        options: [same('$-\\frac{8}{15}$'), same('$\\frac{6}{5}$'), same('$-\\frac{6}{5}$')],
        correctIndex: 2,
        explanation: say('Gurutzean: $-\\frac{4\\cdot 3}{5\\cdot 2}=-\\frac{12}{10}=-\\frac{6}{5}$. Zeinu desberdinak: negatiboa.', 'En cruz: $-\\frac{4\\cdot 3}{5\\cdot 2}=-\\frac{12}{10}=-\\frac{6}{5}$. Signos distintos: negativo.', 'تبادليًا: $-\\frac{4\\cdot 3}{5\\cdot 2}=-\\frac{12}{10}=-\\frac{6}{5}$. إشارتان مختلفتان: سالب.'),
        topic: 'mul-div'
    },
    {
        id: 3106,
        prompt: same('$\\frac{3}{2}-\\frac{4}{5}\\cdot\\frac{5}{6}=\\ ?$'),
        options: [same('$\\frac{7}{12}$'), same('$\\frac{5}{6}$'), same('$\\frac{1}{6}$')],
        correctIndex: 1,
        explanation: say('Lehenik biderketa: $\\frac{4}{5}\\cdot\\frac{5}{6}=\\frac{2}{3}$; gero $\\frac{3}{2}-\\frac{2}{3}=\\frac{5}{6}$. $\\frac{7}{12}$ kenketa lehenik egitean ateratzen da.', 'Primero el producto: $\\frac{4}{5}\\cdot\\frac{5}{6}=\\frac{2}{3}$; después $\\frac{3}{2}-\\frac{2}{3}=\\frac{5}{6}$. $\\frac{7}{12}$ sale al hacer antes la resta.', 'الضرب أولًا: $\\frac{4}{5}\\cdot\\frac{5}{6}=\\frac{2}{3}$؛ ثم $\\frac{3}{2}-\\frac{2}{3}=\\frac{5}{6}$. ونحصل على $\\frac{7}{12}$ إذا بدأنا بالطرح.'),
        topic: 'combined'
    },
    {
        id: 3107,
        prompt: say('Zer motatako hamartarra ematen du $\\frac{13}{990}$ zatikiak?', '¿Qué tipo de decimal da $\\frac{13}{990}$?', 'ما نوع العشري الذي يعطيه $\\frac{13}{990}$؟'),
        options: kinds,
        correctIndex: 2,
        explanation: say('$990=2\\cdot 3^{2}\\cdot 5\\cdot 11$: 2 eta 5, eta beste faktore batzuk → mistoa: $0{,}0\\overline{13}$.', '$990=2\\cdot 3^{2}\\cdot 5\\cdot 11$: 2 y 5, y otros factores → mixto: $0{,}0\\overline{13}$.', '$990=2\\cdot 3^{2}\\cdot 5\\cdot 11$: 2 و5 وعوامل أخرى ← مختلط: $0{,}0\\overline{13}$.'),
        topic: 'decimal-kinds'
    },
    {
        id: 3108,
        prompt: say('Zein da $2{,}\\overline{7}$ zenbakiaren zatiki sortzailea?', '¿Cuál es la fracción generatriz de $2{,}\\overline{7}$?', 'ما الكسر المولّد للعدد $2{,}\\overline{7}$؟'),
        options: [same('$\\frac{27}{9}$'), same('$\\frac{25}{9}$'), same('$\\frac{27}{10}$')],
        correctIndex: 1,
        explanation: say('$\\frac{27-2}{9}=\\frac{25}{9}$. $\\frac{27}{9}$ zati osoa kentzea ahaztean ateratzen da.', '$\\frac{27-2}{9}=\\frac{25}{9}$. $\\frac{27}{9}$ sale al olvidar restar la parte entera.', '$\\frac{27-2}{9}=\\frac{25}{9}$. ونحصل على $\\frac{27}{9}$ إذا نسينا طرح الجزء الصحيح.'),
        topic: 'periodic-generatrix'
    }
]

export const rationalsPractice: PracticeItem[] = [
    { id: 1, stage: 'fractions', prompt: say('$\\frac{18}{11}=\\frac{72}{x}$. Zenbat da $x$?', '$\\frac{18}{11}=\\frac{72}{x}$. ¿Cuánto vale $x$?', '$\\frac{18}{11}=\\frac{72}{x}$. كم تساوي $x$؟'), expected: fraction(44), hint: say('Gurutzeko biderkadurak: $18\\cdot x=11\\cdot 72$.', 'Productos cruzados: $18\\cdot x=11\\cdot 72$.', 'الضرب التبادلي: $18\\cdot x=11\\cdot 72$.'), explanation: same('$x=\\frac{11\\cdot 72}{18}=44$') },
    { id: 2, stage: 'fractions', prompt: say('$\\frac{x}{4}=\\frac{-21}{28}=\\frac{6}{y}$. Zenbat da $y$?', '$\\frac{x}{4}=\\frac{-21}{28}=\\frac{6}{y}$. ¿Cuánto vale $y$?', '$\\frac{x}{4}=\\frac{-21}{28}=\\frac{6}{y}$. كم تساوي $y$؟'), expected: fraction(-8), hint: say('Erabili $\\frac{-21}{28}=\\frac{6}{y}$.', 'Usa $\\frac{-21}{28}=\\frac{6}{y}$.', 'استعمل $\\frac{-21}{28}=\\frac{6}{y}$.'), explanation: same('$y=\\frac{28\\cdot 6}{-21}=-8$') },
    { id: 3, stage: 'fractions', prompt: say('Lortu $\\frac{105}{126}$ zatikiaren zatiki laburtezina.', 'Obtén la fracción irreducible de $\\frac{105}{126}$.', 'جد الكسر غير القابل للاختزال لـ $\\frac{105}{126}$.'), expected: fraction(5, 6), answerForm: 'simplified', hint: say('z.k.h.(105, 126) = 21.', 'm.c.d.(105, 126) = 21.', 'ق.م.أ.(105، 126) = 21.'), explanation: same('$\\frac{105:21}{126:21}=\\frac{5}{6}$') },
    { id: 4, stage: 'fractions', prompt: say('Lortu $\\frac{-120}{165}$ zatikiaren zatiki laburtezina.', 'Obtén la fracción irreducible de $\\frac{-120}{165}$.', 'جد الكسر غير القابل للاختزال لـ $\\frac{-120}{165}$.'), expected: fraction(-8, 11), answerForm: 'simplified', hint: say('z.k.h.(120, 165) = 15.', 'm.c.d.(120, 165) = 15.', 'ق.م.أ.(120، 165) = 15.'), explanation: same('$\\frac{-120:15}{165:15}=-\\frac{8}{11}$') },
    { id: 5, stage: 'order', prompt: say('Zein da handiena: $\\frac{4}{15}$, $\\frac{6}{8}$ ala $\\frac{3}{16}$? Idatzi.', '¿Cuál es la mayor: $\\frac{4}{15}$, $\\frac{6}{8}$ o $\\frac{3}{16}$? Escríbela.', 'أيها الأكبر: $\\frac{4}{15}$ أم $\\frac{6}{8}$ أم $\\frac{3}{16}$؟ اكتبه.'), expected: fraction(3, 4), hint: say('Izendatzaile komuna: 240.', 'Denominador común: 240.', 'المقام المشترك: 240.'), explanation: same('$\\frac{4}{15}=\\frac{64}{240}\\qquad\\frac{6}{8}=\\frac{180}{240}=\\frac{3}{4}\\qquad\\frac{3}{16}=\\frac{45}{240}$') },
    { id: 6, stage: 'order', prompt: say('$\\frac{17}{6}$ bi zenbaki oso jarraituren artean dago. Idatzi txikiena.', '$\\frac{17}{6}$ está entre dos enteros consecutivos. Escribe el menor.', '$\\frac{17}{6}$ يقع بين عددين صحيحين متتاليين. اكتب الأصغر.'), expected: fraction(2), hint: say('Zatitu 17 : 6.', 'Divide 17 : 6.', 'اقسم 17 : 6.'), explanation: same('$\\frac{17}{6}=2+\\frac{5}{6}$') },
    { id: 7, stage: 'order', prompt: say('$\\frac{6}{5}<\\frac{a}{5}<\\frac{8}{5}$, $a$ osoa izanik. Zenbat da $a$?', '$\\frac{6}{5}<\\frac{a}{5}<\\frac{8}{5}$, con $a$ entero. ¿Cuánto vale $a$?', '$\\frac{6}{5}<\\frac{a}{5}<\\frac{8}{5}$ حيث $a$ صحيح. كم تساوي $a$؟'), expected: fraction(7), hint: say('Izendatzaile bera: konparatu zenbakitzaileak.', 'Mismo denominador: compara los numeradores.', 'المقام نفسه: قارن البسوط.'), explanation: same('$6<a<8\\ \\to\\ a=7$') },
    { id: 8, stage: 'order', prompt: say('Kalkulatu $\\frac{4}{5}$ eta $\\frac{7}{8}$ zatikien erdiko puntua.', 'Calcula el punto medio de $\\frac{4}{5}$ y $\\frac{7}{8}$.', 'احسب نقطة المنتصف بين $\\frac{4}{5}$ و$\\frac{7}{8}$.'), expected: fraction(67, 80), hint: say('Batu eta zatitu 2z.', 'Suma y divide entre 2.', 'اجمع واقسم على 2.'), explanation: same('$\\left(\\frac{32}{40}+\\frac{35}{40}\\right):2=\\frac{67}{40}:2=\\frac{67}{80}$') },
    { id: 9, stage: 'operations', prompt: same('$\\frac{5}{9}+\\frac{3}{10}-3$'), expected: fraction(-193, 90), hint: say('m.k.t.(9, 10) = 90; $3=\\frac{270}{90}$.', 'm.c.m.(9, 10) = 90; $3=\\frac{270}{90}$.', 'م.م.أ.(9، 10) = 90؛ $3=\\frac{270}{90}$.'), explanation: same('$\\frac{50+27-270}{90}=-\\frac{193}{90}$') },
    { id: 10, stage: 'operations', prompt: same('$\\frac{-18}{25}-\\frac{1}{5}+2$'), expected: fraction(27, 25), hint: say('Izendatzaile komuna: 25.', 'Denominador común: 25.', 'المقام المشترك: 25.'), explanation: same('$\\frac{-18-5+50}{25}=\\frac{27}{25}$') },
    { id: 11, stage: 'operations', prompt: same('$\\frac{9}{10}:\\frac{8}{14}$'), expected: fraction(63, 40), hint: say('Gurutzean biderkatu.', 'Multiplica en cruz.', 'اضرب تبادليًا.'), explanation: same('$\\frac{9\\cdot 14}{10\\cdot 8}=\\frac{126}{80}=\\frac{63}{40}$') },
    { id: 12, stage: 'operations', prompt: same('$\\frac{5}{3}:\\left(\\frac{1}{9}+\\frac{1}{6}\\right)$'), expected: fraction(6), hint: say('Parentesia lehenik: $\\frac{5}{18}$.', 'Primero el paréntesis: $\\frac{5}{18}$.', 'القوس أولًا: $\\frac{5}{18}$.'), explanation: same('$\\frac{5}{3}:\\frac{5}{18}=\\frac{90}{15}=6$') },
    { id: 13, stage: 'decimals', prompt: say('Idatzi $\\frac{73}{8}$ zenbaki hamartar gisa.', 'Escribe $\\frac{73}{8}$ como número decimal.', 'اكتب $\\frac{73}{8}$ عددًا عشريًا.'), expected: fraction(73, 8), hint: say('Zatitu 73 : 8. Hamartar zehatza da (8 = 2³).', 'Divide 73 : 8. Es exacto (8 = 2³).', 'اقسم 73 : 8. هو منتهٍ (8 = 2³).'), explanation: same('$73:8=9{,}125$') },
    { id: 14, stage: 'decimals', prompt: say('Idatzi $0{,}0016$ zatiki laburtezin gisa.', 'Escribe $0{,}0016$ como fracción irreducible.', 'اكتب $0{,}0016$ كسرًا غير قابل للاختزال.'), expected: fraction(1, 625), answerForm: 'simplified', hint: say('Lau hamartar: 10 000.', 'Cuatro decimales: 10 000.', 'أربع منازل: 10 000.'), explanation: same('$\\frac{16}{10\\,000}=\\frac{1}{625}$') },
    { id: 15, stage: 'decimals', prompt: say('Idatzi $24{,}\\overline{7}$ zatiki gisa.', 'Escribe $24{,}\\overline{7}$ como fracción.', 'اكتب $24{,}\\overline{7}$ كسرًا.'), expected: fraction(223, 9), hint: say('Periodiko hutsa: $\\frac{247-24}{9}$.', 'Periódico puro: $\\frac{247-24}{9}$.', 'دوري بحت: $\\frac{247-24}{9}$.'), explanation: same('$\\frac{247-24}{9}=\\frac{223}{9}$') },
    { id: 16, stage: 'decimals', prompt: say('Idatzi $3{,}4\\overline{5}$ zatiki gisa.', 'Escribe $3{,}4\\overline{5}$ como fracción.', 'اكتب $3{,}4\\overline{5}$ كسرًا.'), expected: fraction(311, 90), hint: say('Mistoa: izendatzailea 90.', 'Mixto: denominador 90.', 'مختلط: المقام 90.'), explanation: same('$\\frac{345-34}{90}=\\frac{311}{90}$') },
    { id: 17, stage: 'problems', prompt: say('Etxe batek 9600 kWh kontsumitzen ditu urtean, eta $\\frac{3}{5}$ berokuntzan. Zenbat kWh berokuntzan?', 'Una casa consume 9600 kWh al año, $\\frac{3}{5}$ en calefacción. ¿Cuántos kWh en calefacción?', 'يستهلك بيت 9600 ك.و.س سنويًا، $\\frac{3}{5}$ منها للتدفئة. كم ك.و.س للتدفئة؟'), expected: fraction(5760), hint: say('Zatitu 5ez eta biderkatu 3z.', 'Divide entre 5 y multiplica por 3.', 'اقسم على 5 واضرب في 3.'), explanation: same('$\\frac{3}{5}\\cdot 9600=5760$') },
    { id: 18, stage: 'problems', prompt: say('Soldataren $\\frac{1}{3}$ alokairuan eta gainerakoaren $\\frac{1}{4}$ janarian. Soldata 1800 € bada, zenbat € geratzen dira?', 'Se gasta $\\frac{1}{3}$ del sueldo en alquiler y $\\frac{1}{4}$ de lo que queda en comida. Si el sueldo es 1800 €, ¿cuántos € quedan?', 'يُنفَق $\\frac{1}{3}$ من الراتب على الإيجار و$\\frac{1}{4}$ من الباقي على الطعام. إذا كان الراتب 1800 € فكم يبقى؟'), expected: fraction(900), hint: say('Janaria osoarekiko: $\\frac{1}{4}\\cdot\\frac{2}{3}$.', 'La comida respecto al total: $\\frac{1}{4}\\cdot\\frac{2}{3}$.', 'الطعام بالنسبة إلى الكل: $\\frac{1}{4}\\cdot\\frac{2}{3}$.'), explanation: same('$1-\\frac{1}{3}-\\frac{1}{6}=\\frac{1}{2}\\qquad\\frac{1}{2}\\cdot 1800=900$') },
    { id: 19, stage: 'problems', prompt: say('Anek pizzaren $\\frac{3}{8}$ jan du eta Jonek gainerakoaren $\\frac{2}{5}$. Pizzaren zer zati geratzen da?', 'Ane se come $\\frac{3}{8}$ de la pizza y Jon $\\frac{2}{5}$ de lo que queda. ¿Qué fracción de la pizza queda?', 'أكلت آنه $\\frac{3}{8}$ من البيتزا وأكل جون $\\frac{2}{5}$ مما بقي. ما الكسر الباقي؟'), expected: fraction(3, 8), hint: say('Jonek $\\frac{2}{5}\\cdot\\frac{5}{8}$ jaten du.', 'Jon se come $\\frac{2}{5}\\cdot\\frac{5}{8}$.', 'يأكل جون $\\frac{2}{5}\\cdot\\frac{5}{8}$.'), explanation: same('$\\frac{2}{5}\\cdot\\frac{5}{8}=\\frac{1}{4}\\qquad 1-\\frac{3}{8}-\\frac{1}{4}=\\frac{3}{8}$') },
    { id: 20, stage: 'problems', prompt: say('Bidaia baten $\\frac{3}{8}$ 45 km dira. Zenbat km ditu bidaiak?', 'Los $\\frac{3}{8}$ de un viaje son 45 km. ¿Cuántos km tiene el viaje?', '$\\frac{3}{8}$ من رحلة يساوي 45 كم. كم كم طول الرحلة؟'), expected: fraction(120), hint: say('Zatiren bat: $45:3$.', 'Una parte: $45:3$.', 'جزء واحد: $45:3$.'), explanation: same('$45:3=15\\qquad 15\\cdot 8=120$') }
]

export const rationalsChallenges: ChallengeItem[] = [
    { id: 101, stage: 'fractions', context: 'starter', points: 10, prompt: say('$\\frac{8}{16}$-ren baliokidea den zatiki baten zenbakitzailea 32 da. Zenbat da izendatzailea?', 'Una fracción equivalente a $\\frac{8}{16}$ tiene numerador 32. ¿Cuál es su denominador?', 'كسر يكافئ $\\frac{8}{16}$ بسطه 32. ما مقامه؟'), expected: fraction(64), hint: say('8 bider 4 da 32.', '8 por 4 es 32.', '8 في 4 يساوي 32.'), explanation: same('$\\frac{8}{16}=\\frac{32}{64}$') },
    { id: 102, stage: 'fractions', context: 'advanced', points: 20, prompt: say('$\\frac{x}{24}=\\frac{5}{6}=\\frac{y}{30}$. Zenbat da $x+y$?', '$\\frac{x}{24}=\\frac{5}{6}=\\frac{y}{30}$. ¿Cuánto vale $x+y$?', '$\\frac{x}{24}=\\frac{5}{6}=\\frac{y}{30}$. كم تساوي $x+y$؟'), expected: fraction(45), hint: say('Kalkulatu bakoitza gurutzeko biderkadurekin.', 'Calcula cada uno con productos cruzados.', 'احسب كلًّا منهما بالضرب التبادلي.'), explanation: same('$x=\\frac{5\\cdot 24}{6}=20\\qquad y=\\frac{5\\cdot 30}{6}=25\\qquad 20+25=45$') },
    { id: 103, stage: 'fractions', context: 'master', points: 30, prompt: say('Zenbatek dute $\\frac{26}{17}$ zatiki laburtezin gisa? $\\frac{140}{198}$, $\\frac{130}{85}$, $\\frac{270}{160}$, $\\frac{182}{119}$', '¿Cuántas tienen $\\frac{26}{17}$ como fracción irreducible? $\\frac{140}{198}$, $\\frac{130}{85}$, $\\frac{270}{160}$, $\\frac{182}{119}$', 'كم منها كسره غير القابل للاختزال $\\frac{26}{17}$؟ $\\frac{140}{198}$، $\\frac{130}{85}$، $\\frac{270}{160}$، $\\frac{182}{119}$'), expected: fraction(2), hint: say('Sinplifikatu bakoitza: izendatzaileak 17ren multiploa izan behar du.', 'Simplifica cada una: el denominador tiene que ser múltiplo de 17.', 'اختزل كلًّا منها: يجب أن يكون المقام مضاعفًا لـ 17.'), explanation: say('$\\frac{130}{85}=\\frac{26}{17}$ (5ez) eta $\\frac{182}{119}=\\frac{26}{17}$ (7z): 2.', '$\\frac{130}{85}=\\frac{26}{17}$ (entre 5) y $\\frac{182}{119}=\\frac{26}{17}$ (entre 7): 2.', '$\\frac{130}{85}=\\frac{26}{17}$ (على 5) و$\\frac{182}{119}=\\frac{26}{17}$ (على 7): 2.') },
    { id: 104, stage: 'order', context: 'starter', points: 10, prompt: say('Zein da txikiena? $-\\frac{21}{6}$, $-\\frac{10}{4}$, $-\\frac{15}{9}$, $\\frac{1}{3}$. Idatzi laburtezin gisa.', '¿Cuál es la menor? $-\\frac{21}{6}$, $-\\frac{10}{4}$, $-\\frac{15}{9}$, $\\frac{1}{3}$. Escríbela irreducible.', 'أيها الأصغر؟ $-\\frac{21}{6}$ و$-\\frac{10}{4}$ و$-\\frac{15}{9}$ و$\\frac{1}{3}$. اكتبه في أبسط صورة.'), expected: fraction(-7, 2), answerForm: 'simplified', hint: say('Negatiboen artean, balio absolutu handiena duena.', 'Entre las negativas, la de mayor valor absoluto.', 'بين السالبة: صاحب القيمة المطلقة الأكبر.'), explanation: same('$-\\frac{21}{6}=-\\frac{7}{2}\\qquad -\\frac{7}{2}<-\\frac{10}{4}<-\\frac{15}{9}<\\frac{1}{3}$') },
    { id: 105, stage: 'order', context: 'advanced', points: 20, prompt: say('$-\\frac{9}{5}$-en baliokidea den zatiki baten zenbakitzailea −63 da. Zenbat da izendatzailea?', 'Una fracción equivalente a $-\\frac{9}{5}$ tiene numerador −63. ¿Cuál es su denominador?', 'كسر يكافئ $-\\frac{9}{5}$ بسطه −63. ما مقامه؟'), expected: fraction(35), hint: say('9 bider 7 da 63.', '9 por 7 es 63.', '9 في 7 يساوي 63.'), explanation: same('$\\frac{-9}{5}=\\frac{-63}{35}$') },
    { id: 106, stage: 'order', context: 'master', points: 30, prompt: say('Zenbat zenbaki oso $a$-k betetzen dute $-\\frac{1}{2}<\\frac{a}{2}<\\frac{3}{4}$?', '¿Cuántos enteros $a$ cumplen $-\\frac{1}{2}<\\frac{a}{2}<\\frac{3}{4}$?', 'كم عددًا صحيحًا $a$ يحقق $-\\frac{1}{2}<\\frac{a}{2}<\\frac{3}{4}$؟'), expected: fraction(2), hint: say('Izendatzaile komuna 4: $-\\frac{2}{4}<\\frac{2a}{4}<\\frac{3}{4}$.', 'Denominador común 4: $-\\frac{2}{4}<\\frac{2a}{4}<\\frac{3}{4}$.', 'المقام المشترك 4: $-\\frac{2}{4}<\\frac{2a}{4}<\\frac{3}{4}$.'), explanation: say('$-2<2a<3\\ \\to\\ a=0$ edo $a=1$: 2.', '$-2<2a<3\\ \\to\\ a=0$ o $a=1$: 2.', '$-2<2a<3\\ \\to\\ a=0$ أو $a=1$: 2.') },
    { id: 107, stage: 'operations', context: 'starter', points: 10, prompt: same('$\\left(\\frac{7}{2}+\\frac{1}{5}\\right)\\cdot\\frac{5}{6}$'), expected: fraction(37, 12), hint: say('Parentesia: $\\frac{37}{10}$.', 'El paréntesis: $\\frac{37}{10}$.', 'القوس: $\\frac{37}{10}$.'), explanation: same('$\\frac{37}{10}\\cdot\\frac{5}{6}=\\frac{185}{60}=\\frac{37}{12}$') },
    { id: 108, stage: 'operations', context: 'advanced', points: 20, prompt: same('$-\\frac{4}{7}+\\frac{12}{5}-\\frac{3}{4}\\cdot\\left(-\\frac{5}{6}\\right)$'), expected: fraction(687, 280), hint: say('Biderketa lehenik: $\\frac{3}{4}\\cdot\\left(-\\frac{5}{6}\\right)=-\\frac{5}{8}$.', 'Primero el producto: $\\frac{3}{4}\\cdot\\left(-\\frac{5}{6}\\right)=-\\frac{5}{8}$.', 'الضرب أولًا: $\\frac{3}{4}\\cdot\\left(-\\frac{5}{6}\\right)=-\\frac{5}{8}$.'), explanation: same('$-\\frac{4}{7}+\\frac{12}{5}+\\frac{5}{8}=\\frac{-160+672+175}{280}=\\frac{687}{280}$') },
    { id: 109, stage: 'operations', context: 'master', points: 30, prompt: same('$2\\cdot\\frac{9}{5}-\\frac{3}{2}:\\left(\\frac{7}{4}+\\frac{5}{6}\\right)$'), expected: fraction(468, 155), hint: say('Parentesia: $\\frac{31}{12}$; gero zatiketa eta biderketa.', 'El paréntesis: $\\frac{31}{12}$; después la división y el producto.', 'القوس: $\\frac{31}{12}$؛ ثم القسمة والضرب.'), explanation: same('$\\frac{18}{5}-\\frac{3}{2}:\\frac{31}{12}=\\frac{18}{5}-\\frac{18}{31}=\\frac{558-90}{155}=\\frac{468}{155}$') },
    { id: 110, stage: 'decimals', context: 'starter', points: 10, prompt: same('$0{,}\\overline{3}+0{,}\\overline{6}$'), expected: fraction(1), hint: say('Pasa biak zatiki.', 'Pasa los dos a fracción.', 'حوّلهما إلى كسرين.'), explanation: same('$\\frac{3}{9}+\\frac{6}{9}=\\frac{9}{9}=1$') },
    { id: 111, stage: 'decimals', context: 'advanced', points: 20, prompt: say('Idatzi $5{,}6\\overline{005}$ zatiki gisa.', 'Escribe $5{,}6\\overline{005}$ como fracción.', 'اكتب $5{,}6\\overline{005}$ كسرًا.'), expected: fraction(55949, 9990), hint: say('Periodoa 3 zifra (999) eta aurreperiodoa 1 (0).', 'Periodo de 3 cifras (999) y anteperiodo de 1 (0).', 'دور من 3 أرقام (999) وجزء غير دوري من رقم (0).'), explanation: same('$\\frac{56005-56}{9990}=\\frac{55949}{9990}$') },
    { id: 112, stage: 'decimals', context: 'master', points: 30, prompt: say('Idatzi $0{,}667\\overline{2}$ zatiki laburtezin gisa.', 'Escribe $0{,}667\\overline{2}$ como fracción irreducible.', 'اكتب $0{,}667\\overline{2}$ كسرًا غير قابل للاختزال.'), expected: fraction(1201, 1800), answerForm: 'simplified', hint: say('Aurreperiodoa 3 zifra: izendatzailea 9000.', 'Anteperiodo de 3 cifras: denominador 9000.', 'جزء غير دوري من 3 أرقام: المقام 9000.'), explanation: same('$\\frac{6672-667}{9000}=\\frac{6005}{9000}=\\frac{1201}{1800}$') },
    { id: 113, stage: 'problems', context: 'advanced', points: 20, prompt: say('Depositu baten $\\frac{2}{7}$ hustu da eta 35 L geratzen dira. Zenbat litro sartzen dira?', 'Se ha vaciado $\\frac{2}{7}$ de un depósito y quedan 35 L. ¿Cuántos litros caben?', 'أُفرغ $\\frac{2}{7}$ من خزان وبقي 35 لترًا. كم لترًا يتسع؟'), expected: fraction(49), hint: say('Geratzen dena $\\frac{5}{7}$ da.', 'Lo que queda son $\\frac{5}{7}$.', 'الباقي $\\frac{5}{7}$.'), explanation: same('$35:5=7\\qquad 7\\cdot 7=49$') },
    { id: 114, stage: 'problems', context: 'master', points: 30, prompt: say('Herentzia batean, anaia nagusiak $\\frac{1}{3}$ hartzen du, erdikoak gainerakoaren $\\frac{2}{5}$ eta gazteenak 12 000 €. Zenbat da herentzia (€)?', 'En una herencia, el hermano mayor recibe $\\frac{1}{3}$, el mediano $\\frac{2}{5}$ de lo que queda y el pequeño 12 000 €. ¿A cuánto asciende la herencia (€)?', 'في إرث يأخذ الأخ الأكبر $\\frac{1}{3}$ والأوسط $\\frac{2}{5}$ من الباقي والأصغر 12 000 €. كم الإرث (€)؟'), expected: fraction(30000), hint: say('Erdikoak osoaren $\\frac{2}{5}\\cdot\\frac{2}{3}$ hartzen du.', 'El mediano recibe $\\frac{2}{5}\\cdot\\frac{2}{3}$ del total.', 'يأخذ الأوسط $\\frac{2}{5}\\cdot\\frac{2}{3}$ من الكل.'), explanation: same('$1-\\frac{1}{3}-\\frac{4}{15}=\\frac{2}{5}\\qquad 12\\,000:\\frac{2}{5}=30\\,000$') }
]

export const rationalsExerciseBank: ExerciseSection[] = [
    {
        id: 'fractions',
        title: say('Zatikiak eta baliokidetasuna', 'Fracciones y equivalencia', 'الكسور والتكافؤ'),
        items: [
            { id: 1, difficulty: 'easy', question: say('$\\frac{8}{7}$ eta $\\frac{4}{17}$ baliokideak dira?', '¿Son equivalentes $\\frac{8}{7}$ y $\\frac{4}{17}$?', 'هل $\\frac{8}{7}$ و$\\frac{4}{17}$ متكافئان؟'), solution: say('$8\\cdot 17=136$ eta $7\\cdot 4=28$: ez dira berdinak, beraz ez dira baliokideak.', '$8\\cdot 17=136$ y $7\\cdot 4=28$: no son iguales, así que no son equivalentes.', '$8\\cdot 17=136$ و$7\\cdot 4=28$: غير متساويين، فالكسران غير متكافئين.') },
            { id: 2, difficulty: 'easy', question: say('Idatzi $\\frac{-4}{3}$-ren lau zatiki baliokide.', 'Escribe cuatro fracciones equivalentes a $\\frac{-4}{3}$.', 'اكتب أربعة كسور تكافئ $\\frac{-4}{3}$.'), solution: same('$\\frac{-4}{3}=\\frac{-8}{6}=\\frac{-12}{9}=\\frac{-80}{60}=\\frac{-24}{18}$') },
            { id: 3, difficulty: 'easy', question: say('$\\frac{7}{15}=\\frac{x}{60}$. Kalkulatu $x$.', '$\\frac{7}{15}=\\frac{x}{60}$. Calcula $x$.', '$\\frac{7}{15}=\\frac{x}{60}$. احسب $x$.'), solution: same('$x=\\frac{60\\cdot 7}{15}=28$'), answer: { expected: fraction(28) } },
            { id: 4, difficulty: 'medium', question: say('$\\frac{9}{x}=\\frac{45}{25}$. Kalkulatu $x$.', '$\\frac{9}{x}=\\frac{45}{25}$. Calcula $x$.', '$\\frac{9}{x}=\\frac{45}{25}$. احسب $x$.'), solution: same('$x=\\frac{9\\cdot 25}{45}=5$'), answer: { expected: fraction(5) } },
            { id: 5, difficulty: 'medium', question: say('Eman $\\frac{8}{16}$-ren baliokide bat, izendatzailea 48 duena. Zein da zenbakitzailea?', 'Da una fracción equivalente a $\\frac{8}{16}$ con denominador 48. ¿Cuál es el numerador?', 'أعطِ كسرًا يكافئ $\\frac{8}{16}$ مقامه 48. ما البسط؟'), solution: same('$\\frac{8}{16}=\\frac{24}{48}$'), answer: { expected: fraction(24) } },
            { id: 6, difficulty: 'medium', question: say('Lortu $\\frac{50}{60}$ zatikiaren zatiki laburtezina.', 'Obtén la fracción irreducible de $\\frac{50}{60}$.', 'جد الكسر غير القابل للاختزال لـ $\\frac{50}{60}$.'), solution: same('$\\frac{50:10}{60:10}=\\frac{5}{6}$'), answer: { expected: fraction(5, 6), form: 'simplified' } },
            { id: 7, difficulty: 'medium', question: say('Lortu $\\frac{-92}{18}$ zatikiaren zatiki laburtezina.', 'Obtén la fracción irreducible de $\\frac{-92}{18}$.', 'جد الكسر غير القابل للاختزال لـ $\\frac{-92}{18}$.'), solution: same('$\\frac{-92:2}{18:2}=-\\frac{46}{9}$'), answer: { expected: fraction(-46, 9), form: 'simplified' } },
            { id: 8, difficulty: 'hard', question: say('Zeinen zatiki laburtezina da $\\frac{26}{17}$? $\\frac{140}{198}$, $\\frac{130}{85}$, $\\frac{270}{160}$, $\\frac{182}{119}$', '¿De cuáles es $\\frac{26}{17}$ la fracción irreducible? $\\frac{140}{198}$, $\\frac{130}{85}$, $\\frac{270}{160}$, $\\frac{182}{119}$', 'لأيها $\\frac{26}{17}$ هو الكسر غير القابل للاختزال؟ $\\frac{140}{198}$، $\\frac{130}{85}$، $\\frac{270}{160}$، $\\frac{182}{119}$'), solution: same('$\\frac{130}{85}=\\frac{26}{17}\\qquad\\frac{182}{119}=\\frac{26}{17}$') },
            { id: 9, difficulty: 'hard', question: say('Zatiki baten gai bat zenbaki lehena bada, ziur daiteke laburtezina dela?', 'Si uno de los términos de una fracción es primo, ¿se puede asegurar que es irreducible?', 'إذا كان أحد حدّي كسر عددًا أوليًا، فهل نضمن أنه غير قابل للاختزال؟'), solution: say('Ez: beste gaia lehen horren multiploa bada, sinplifika daiteke: $\\frac{7}{14}=\\frac{1}{2}$ edo $\\frac{165}{11}=15$.', 'No: si el otro término es múltiplo de ese primo, se puede simplificar: $\\frac{7}{14}=\\frac{1}{2}$ o $\\frac{165}{11}=15$.', 'لا: إذا كان الحد الآخر مضاعفًا لذلك العدد الأولي أمكن الاختزال: $\\frac{7}{14}=\\frac{1}{2}$ أو $\\frac{165}{11}=15$.') },
            { id: 10, difficulty: 'hard', question: say('$\\frac{x}{4}=\\frac{-21}{28}=\\frac{6}{y}$. Kalkulatu $x$.', '$\\frac{x}{4}=\\frac{-21}{28}=\\frac{6}{y}$. Calcula $x$.', '$\\frac{x}{4}=\\frac{-21}{28}=\\frac{6}{y}$. احسب $x$.'), solution: same('$x=\\frac{-21\\cdot 4}{28}=-3\\qquad y=\\frac{28\\cdot 6}{-21}=-8$'), answer: { expected: fraction(-3) } }
        ]
    },
    {
        id: 'order',
        title: say('Ordena eta zuzena', 'Orden y recta', 'الترتيب والمستقيم'),
        items: [
            { id: 11, difficulty: 'easy', question: say('Ordenatu txikienetik handienera: $\\frac{4}{5}$, $\\frac{-10}{4}$, $\\frac{-21}{6}$, $\\frac{-15}{9}$, $\\frac{1}{3}$, $\\frac{7}{9}$.', 'Ordena de menor a mayor: $\\frac{4}{5}$, $\\frac{-10}{4}$, $\\frac{-21}{6}$, $\\frac{-15}{9}$, $\\frac{1}{3}$, $\\frac{7}{9}$.', 'رتّب من الأصغر إلى الأكبر: $\\frac{4}{5}$ و$\\frac{-10}{4}$ و$\\frac{-21}{6}$ و$\\frac{-15}{9}$ و$\\frac{1}{3}$ و$\\frac{7}{9}$.'), solution: same('$\\frac{-21}{6}<\\frac{-10}{4}<\\frac{-15}{9}<\\frac{1}{3}<\\frac{7}{9}<\\frac{4}{5}$') },
            { id: 12, difficulty: 'easy', question: say('Jarri izendatzaile komuna eta ordenatu: $\\frac{2}{5}$, $\\frac{5}{4}$ eta $\\frac{3}{8}$.', 'Reduce a común denominador y ordena: $\\frac{2}{5}$, $\\frac{5}{4}$ y $\\frac{3}{8}$.', 'وحّد المقامات ورتّب: $\\frac{2}{5}$ و$\\frac{5}{4}$ و$\\frac{3}{8}$.'), solution: same('$\\frac{3}{8}=\\frac{15}{40}\\qquad\\frac{2}{5}=\\frac{16}{40}\\qquad\\frac{5}{4}=\\frac{50}{40}\\ \\to\\ \\frac{3}{8}<\\frac{2}{5}<\\frac{5}{4}$') },
            { id: 13, difficulty: 'medium', question: say('$\\frac{6}{5}<\\frac{a}{5}<\\frac{8}{5}$, $a$ osoa izanik. Kalkulatu $a$.', '$\\frac{6}{5}<\\frac{a}{5}<\\frac{8}{5}$, con $a$ entero. Calcula $a$.', '$\\frac{6}{5}<\\frac{a}{5}<\\frac{8}{5}$ حيث $a$ صحيح. احسب $a$.'), solution: same('$6<a<8\\ \\to\\ a=7$'), answer: { expected: fraction(7) } },
            { id: 14, difficulty: 'medium', question: say('$\\frac{25}{8}$ bi zenbaki oso jarraituren artean dago. Zein da txikiena?', '$\\frac{25}{8}$ está entre dos enteros consecutivos. ¿Cuál es el menor?', '$\\frac{25}{8}$ بين عددين صحيحين متتاليين. ما الأصغر؟'), solution: same('$\\frac{25}{8}=3+\\frac{1}{8}\\ \\to\\ 3<\\frac{25}{8}<4$'), answer: { expected: fraction(3) } },
            { id: 15, difficulty: 'medium', question: say('Aurkitu $\\frac{4}{5}$ eta $\\frac{7}{8}$ arteko zatiki bat (erdiko puntua).', 'Encuentra una fracción entre $\\frac{4}{5}$ y $\\frac{7}{8}$ (el punto medio).', 'جد كسرًا بين $\\frac{4}{5}$ و$\\frac{7}{8}$ (نقطة المنتصف).'), solution: same('$\\left(\\frac{4}{5}+\\frac{7}{8}\\right):2=\\frac{67}{80}$'), answer: { expected: fraction(67, 80) } },
            { id: 16, difficulty: 'medium', question: say('Aurkitu $-\\frac{3}{7}$ eta $-\\frac{2}{5}$ arteko zatiki bat (erdiko puntua).', 'Encuentra una fracción entre $-\\frac{3}{7}$ y $-\\frac{2}{5}$ (el punto medio).', 'جد كسرًا بين $-\\frac{3}{7}$ و$-\\frac{2}{5}$ (نقطة المنتصف).'), solution: same('$\\left(-\\frac{3}{7}-\\frac{2}{5}\\right):2=-\\frac{29}{35}:2=-\\frac{29}{70}$'), answer: { expected: fraction(-29, 70) } },
            { id: 17, difficulty: 'hard', question: say('Irudikatu zuzenean $\\frac{17}{6}$ eta $-\\frac{12}{5}$.', 'Representa en la recta $\\frac{17}{6}$ y $-\\frac{12}{5}$.', 'مثّل على المستقيم $\\frac{17}{6}$ و$-\\frac{12}{5}$.'), solution: say('$\\frac{17}{6}=2+\\frac{5}{6}$: zatitu $[2,\\,3]$ sei zatitan eta hartu bosgarren marka. $-\\frac{12}{5}=-2-\\frac{2}{5}$: zatitu $[-3,\\,-2]$ bost zatitan eta hartu −2tik ezkerrera bigarren marka.', '$\\frac{17}{6}=2+\\frac{5}{6}$: divide $[2,\\,3]$ en seis partes y toma la quinta marca. $-\\frac{12}{5}=-2-\\frac{2}{5}$: divide $[-3,\\,-2]$ en cinco partes y toma la segunda marca a la izquierda de −2.', '$\\frac{17}{6}=2+\\frac{5}{6}$: قسّم $[2,\\,3]$ ستة أجزاء وخذ العلامة الخامسة. $-\\frac{12}{5}=-2-\\frac{2}{5}$: قسّم $[-3,\\,-2]$ خمسة أجزاء وخذ العلامة الثانية يسار −2.') },
            { id: 18, difficulty: 'hard', question: say('Ordenatu txikienetik handienera: $\\frac{5}{9}$, $\\frac{5}{4}$, $\\frac{5}{3}$, $\\frac{5}{7}$, $\\frac{5}{8}$.', 'Ordena de menor a mayor: $\\frac{5}{9}$, $\\frac{5}{4}$, $\\frac{5}{3}$, $\\frac{5}{7}$, $\\frac{5}{8}$.', 'رتّب من الأصغر إلى الأكبر: $\\frac{5}{9}$ و$\\frac{5}{4}$ و$\\frac{5}{3}$ و$\\frac{5}{7}$ و$\\frac{5}{8}$.'), solution: say('Zenbakitzaile bera: izendatzaile handiena, zatiki txikiena. $\\frac{5}{9}<\\frac{5}{8}<\\frac{5}{7}<\\frac{5}{4}<\\frac{5}{3}$.', 'Mismo numerador: mayor denominador, menor fracción. $\\frac{5}{9}<\\frac{5}{8}<\\frac{5}{7}<\\frac{5}{4}<\\frac{5}{3}$.', 'البسط نفسه: المقام الأكبر يعطي الكسر الأصغر. $\\frac{5}{9}<\\frac{5}{8}<\\frac{5}{7}<\\frac{5}{4}<\\frac{5}{3}$.') },
            { id: 19, difficulty: 'hard', question: say('Idatzi $\\frac{-7}{3}$-ren eta $\\frac{-9}{5}$-en baliokide bana, zenbakitzaile bera dutenak.', 'Escribe una fracción equivalente a $\\frac{-7}{3}$ y otra a $\\frac{-9}{5}$ con el mismo numerador.', 'اكتب كسرًا يكافئ $\\frac{-7}{3}$ وآخر يكافئ $\\frac{-9}{5}$ لهما البسط نفسه.'), solution: same('$\\frac{-7}{3}=\\frac{-63}{27}\\qquad\\frac{-9}{5}=\\frac{-63}{35}$') },
            { id: 20, difficulty: 'hard', question: say('Kalkulatu $\\frac{-1}{6}$ eta $\\frac{1}{5}$ zatikien erdiko puntua.', 'Calcula el punto medio de $\\frac{-1}{6}$ y $\\frac{1}{5}$.', 'احسب نقطة المنتصف بين $\\frac{-1}{6}$ و$\\frac{1}{5}$.'), solution: same('$\\left(\\frac{-1}{6}+\\frac{1}{5}\\right):2=\\frac{1}{30}:2=\\frac{1}{60}$'), answer: { expected: fraction(1, 60) } }
        ]
    },
    {
        id: 'operations',
        title: say('Eragiketak', 'Operaciones', 'العمليات'),
        items: [
            { id: 21, difficulty: 'easy', question: same('$\\frac{5}{3}+\\frac{4}{18}+\\frac{6}{3}$'), solution: same('$\\frac{30+4+36}{18}=\\frac{70}{18}=\\frac{35}{9}$'), answer: { expected: fraction(35, 9) } },
            { id: 22, difficulty: 'easy', question: same('$\\frac{23}{6}-\\frac{11}{6}-\\frac{1}{6}$'), solution: same('$\\frac{23-11-1}{6}=\\frac{11}{6}$'), answer: { expected: fraction(11, 6) } },
            { id: 23, difficulty: 'medium', question: same('$\\frac{5}{9}+\\frac{3}{10}-3$'), solution: same('$\\frac{50+27-270}{90}=-\\frac{193}{90}$'), answer: { expected: fraction(-193, 90) } },
            { id: 24, difficulty: 'medium', question: same('$\\frac{-4}{5}\\cdot\\frac{20}{8}$'), solution: same('$\\frac{-80}{40}=-2$'), answer: { expected: fraction(-2) } },
            { id: 25, difficulty: 'medium', question: same('$\\frac{9}{10}:\\frac{8}{14}$'), solution: same('$\\frac{9\\cdot 14}{10\\cdot 8}=\\frac{126}{80}=\\frac{63}{40}$'), answer: { expected: fraction(63, 40) } },
            { id: 26, difficulty: 'medium', question: same('$\\left(-\\frac{4}{80}\\right):\\left(-\\frac{8}{46}\\right)$'), solution: same('$\\frac{4\\cdot 46}{80\\cdot 8}=\\frac{184}{640}=\\frac{23}{80}$'), answer: { expected: fraction(23, 80) } },
            { id: 27, difficulty: 'hard', question: say('Kalkulatu $\\frac{3}{2}-\\frac{4}{5}\\cdot\\frac{5}{6}$ eta konparatu $\\left(\\frac{3}{2}-\\frac{4}{5}\\right)\\cdot\\frac{5}{6}$-rekin. Eman lehenengoa.', 'Calcula $\\frac{3}{2}-\\frac{4}{5}\\cdot\\frac{5}{6}$ y compáralo con $\\left(\\frac{3}{2}-\\frac{4}{5}\\right)\\cdot\\frac{5}{6}$. Da el primero.', 'احسب $\\frac{3}{2}-\\frac{4}{5}\\cdot\\frac{5}{6}$ وقارنه بـ $\\left(\\frac{3}{2}-\\frac{4}{5}\\right)\\cdot\\frac{5}{6}$. أعطِ الأول.'), solution: same('$\\frac{3}{2}-\\frac{2}{3}=\\frac{5}{6}\\qquad\\frac{7}{10}\\cdot\\frac{5}{6}=\\frac{7}{12}$'), answer: { expected: fraction(5, 6) } },
            { id: 28, difficulty: 'hard', question: same('$\\frac{2}{7}:\\left(\\frac{1}{4}-\\frac{3}{14}\\right)$'), solution: same('$\\frac{1}{4}-\\frac{3}{14}=\\frac{7-6}{28}=\\frac{1}{28}\\qquad\\frac{2}{7}:\\frac{1}{28}=\\frac{56}{7}=8$'), answer: { expected: fraction(8) } },
            { id: 29, difficulty: 'hard', question: same('$\\frac{4}{9}:\\left(\\frac{5}{3}-\\frac{1}{6}\\right)+\\left(-\\frac{1}{4}\\right)$'), solution: same('$\\frac{5}{3}-\\frac{1}{6}=\\frac{3}{2}\\qquad\\frac{4}{9}:\\frac{3}{2}=\\frac{8}{27}\\qquad\\frac{8}{27}-\\frac{1}{4}=\\frac{32-27}{108}=\\frac{5}{108}$'), answer: { expected: fraction(5, 108) } },
            { id: 30, difficulty: 'hard', question: same('$\\left(2-\\frac{1}{2}\\right):\\left(4+\\frac{1}{3}\\right)\\cdot\\left(-\\frac{6}{5}\\right)$'), solution: same('$\\frac{3}{2}:\\frac{13}{3}=\\frac{9}{26}\\qquad\\frac{9}{26}\\cdot\\left(-\\frac{6}{5}\\right)=-\\frac{54}{130}=-\\frac{27}{65}$'), answer: { expected: fraction(-27, 65) } }
        ]
    },
    {
        id: 'decimals',
        title: say('Hamartarrak eta zatiki sortzailea', 'Decimales y fracción generatriz', 'العشريات والكسر المولّد'),
        items: [
            { id: 31, difficulty: 'easy', question: say('Sailkatu: $9{,}0909\\ldots$, $45{,}7$, $2{,}3333\\ldots$ eta $1{,}121122111222\\ldots$', 'Clasifica: $9{,}0909\\ldots$, $45{,}7$, $2{,}3333\\ldots$ y $1{,}121122111222\\ldots$', 'صنّف: $9{,}0909\\ldots$ و$45{,}7$ و$2{,}3333\\ldots$ و$1{,}121122111222\\ldots$'), solution: say('Periodiko hutsa, zehatza, periodiko hutsa eta ez zehatza ez periodikoa (ez da arrazionala).', 'Periódico puro, exacto, periódico puro y ni exacto ni periódico (no es racional).', 'دوري بحت، منتهٍ، دوري بحت، وليس منتهيًا ولا دوريًا (ليس نسبيًا).') },
            { id: 32, difficulty: 'easy', question: say('Idatzi $\\frac{7}{100}$ hamartar gisa.', 'Escribe $\\frac{7}{100}$ como decimal.', 'اكتب $\\frac{7}{100}$ عددًا عشريًا.'), solution: same('$\\frac{7}{100}=0{,}07$'), answer: { expected: fraction(7, 100) } },
            { id: 33, difficulty: 'easy', question: say('Zatitu gabe, sailkatu: $\\frac{5}{9}$, $\\frac{14}{20}$, $\\frac{18}{300}$, $\\frac{7}{210}$, $\\frac{9}{40}$.', 'Sin dividir, clasifica: $\\frac{5}{9}$, $\\frac{14}{20}$, $\\frac{18}{300}$, $\\frac{7}{210}$, $\\frac{9}{40}$.', 'دون قسمة، صنّف: $\\frac{5}{9}$ و$\\frac{14}{20}$ و$\\frac{18}{300}$ و$\\frac{7}{210}$ و$\\frac{9}{40}$.'), solution: say('$\\frac{5}{3^{2}}$ periodikoa; $\\frac{7}{2\\cdot 5}$ zehatza; $\\frac{3}{2\\cdot 5^{2}}$ zehatza; $\\frac{1}{2\\cdot 3\\cdot 5}$ periodikoa; $\\frac{9}{2^{3}\\cdot 5}$ zehatza.', '$\\frac{5}{3^{2}}$ periódico; $\\frac{7}{2\\cdot 5}$ exacto; $\\frac{3}{2\\cdot 5^{2}}$ exacto; $\\frac{1}{2\\cdot 3\\cdot 5}$ periódico; $\\frac{9}{2^{3}\\cdot 5}$ exacto.', '$\\frac{5}{3^{2}}$ دوري؛ $\\frac{7}{2\\cdot 5}$ منتهٍ؛ $\\frac{3}{2\\cdot 5^{2}}$ منتهٍ؛ $\\frac{1}{2\\cdot 3\\cdot 5}$ دوري؛ $\\frac{9}{2^{3}\\cdot 5}$ منتهٍ.') },
            { id: 34, difficulty: 'medium', question: say('Zein dira $\\frac{1}{600}$ zatikiaren periodoa eta aurreperiodoa?', '¿Cuáles son el periodo y el anteperiodo de $\\frac{1}{600}$?', 'ما الدور وما الجزء غير الدوري للكسر $\\frac{1}{600}$؟'), solution: say('$\\frac{1}{600}=0{,}001\\overline{6}$: periodoa zifra bat (6) eta aurreperiodoa hiru (001).', '$\\frac{1}{600}=0{,}001\\overline{6}$: periodo de una cifra (6) y anteperiodo de tres (001).', '$\\frac{1}{600}=0{,}001\\overline{6}$: دور من رقم (6) وجزء غير دوري من ثلاثة (001).') },
            { id: 35, difficulty: 'medium', question: say('Idatzi $0{,}\\overline{08}$ zatiki gisa.', 'Escribe $0{,}\\overline{08}$ como fracción.', 'اكتب $0{,}\\overline{08}$ كسرًا.'), solution: same('$0{,}\\overline{08}=\\frac{8}{99}$'), answer: { expected: fraction(8, 99) } },
            { id: 36, difficulty: 'medium', question: say('Idatzi $24{,}\\overline{7}$ zatiki gisa.', 'Escribe $24{,}\\overline{7}$ como fracción.', 'اكتب $24{,}\\overline{7}$ كسرًا.'), solution: same('$\\frac{247-24}{9}=\\frac{223}{9}$'), answer: { expected: fraction(223, 9) } },
            { id: 37, difficulty: 'medium', question: say('Idatzi $0{,}00\\overline{7}$ zatiki gisa.', 'Escribe $0{,}00\\overline{7}$ como fracción.', 'اكتب $0{,}00\\overline{7}$ كسرًا.'), solution: same('$\\frac{7}{900}$'), answer: { expected: fraction(7, 900) } },
            { id: 38, difficulty: 'hard', question: say('Idatzi $1{,}3\\overline{56}$ zatiki gisa.', 'Escribe $1{,}3\\overline{56}$ como fracción.', 'اكتب $1{,}3\\overline{56}$ كسرًا.'), solution: same('$\\frac{1356-13}{990}=\\frac{1343}{990}$'), answer: { expected: fraction(1343, 990) } },
            { id: 39, difficulty: 'hard', question: say('Idatzi $4{,}\\overline{453}$ zatiki laburtezin gisa.', 'Escribe $4{,}\\overline{453}$ como fracción irreducible.', 'اكتب $4{,}\\overline{453}$ كسرًا غير قابل للاختزال.'), solution: same('$\\frac{4453-4}{999}=\\frac{4449}{999}=\\frac{1483}{333}$'), answer: { expected: fraction(1483, 333), form: 'simplified' } },
            { id: 40, difficulty: 'hard', question: say('Idatzi $0{,}1\\overline{25}$ zatiki laburtezin gisa.', 'Escribe $0{,}1\\overline{25}$ como fracción irreducible.', 'اكتب $0{,}1\\overline{25}$ كسرًا غير قابل للاختزال.'), solution: same('$\\frac{125-1}{990}=\\frac{124}{990}=\\frac{62}{495}$'), answer: { expected: fraction(62, 495), form: 'simplified' } }
        ]
    },
    {
        id: 'problems',
        title: say('Problemak', 'Problemas', 'المسائل'),
        items: [
            { id: 41, difficulty: 'easy', question: say('Kalkulatu 120ren $\\frac{3}{8}$.', 'Calcula $\\frac{3}{8}$ de 120.', 'احسب $\\frac{3}{8}$ من 120.'), solution: same('$120:8=15\\qquad 15\\cdot 3=45$'), answer: { expected: fraction(45) } },
            { id: 42, difficulty: 'easy', question: say('Kalkulatu 60ren $\\frac{5}{6}$-ren $\\frac{2}{5}$.', 'Calcula $\\frac{2}{5}$ de $\\frac{5}{6}$ de 60.', 'احسب $\\frac{2}{5}$ من $\\frac{5}{6}$ من 60.'), solution: same('$\\frac{2}{5}\\cdot\\frac{5}{6}\\cdot 60=\\frac{1}{3}\\cdot 60=20$'), answer: { expected: fraction(20) } },
            { id: 43, difficulty: 'easy', question: say('1440 €-ko aurrezkietatik 480 € gastatu ditugu. Zer zatiki da? (Laburtezina.)', 'De unos ahorros de 1440 € hemos gastado 480 €. ¿Qué fracción es? (Irreducible.)', 'من مدخرات قدرها 1440 € أنفقنا 480 €. ما الكسر؟ (غير قابل للاختزال.)'), solution: same('$\\frac{480}{1440}=\\frac{1}{3}$'), answer: { expected: fraction(1, 3), form: 'simplified' } },
            { id: 44, difficulty: 'medium', question: say('Soldataren $\\frac{1}{3}$ alokairuan eta gainerakoaren $\\frac{1}{4}$ janarian. Soldata 1800 € bada, zenbat € janarian?', 'Se gasta $\\frac{1}{3}$ del sueldo en alquiler y $\\frac{1}{4}$ de lo que queda en comida. Si el sueldo es 1800 €, ¿cuántos € en comida?', 'يُنفَق $\\frac{1}{3}$ من الراتب على الإيجار و$\\frac{1}{4}$ من الباقي على الطعام. إذا كان الراتب 1800 € فكم للطعام؟'), solution: same('$\\frac{1}{4}\\cdot\\frac{2}{3}=\\frac{1}{6}\\qquad\\frac{1}{6}\\cdot 1800=300$'), answer: { expected: fraction(300) } },
            { id: 45, difficulty: 'medium', question: say('Anek pizzaren $\\frac{3}{8}$ jan du eta Jonek gainerakoaren $\\frac{2}{5}$. Zer zati geratzen da?', 'Ane se come $\\frac{3}{8}$ de la pizza y Jon $\\frac{2}{5}$ de lo que queda. ¿Qué fracción queda?', 'أكلت آنه $\\frac{3}{8}$ من البيتزا وجون $\\frac{2}{5}$ مما بقي. ما الكسر الباقي؟'), solution: same('$\\frac{2}{5}\\cdot\\frac{5}{8}=\\frac{1}{4}\\qquad 1-\\frac{3}{8}-\\frac{1}{4}=\\frac{3}{8}$'), answer: { expected: fraction(3, 8) } },
            { id: 46, difficulty: 'medium', question: say('Bidaia baten $\\frac{3}{8}$ 45 km dira. Zenbat km ditu bidaiak?', 'Los $\\frac{3}{8}$ de un viaje son 45 km. ¿Cuántos km tiene el viaje?', '$\\frac{3}{8}$ من رحلة يساوي 45 كم. كم كم طولها؟'), solution: same('$45:3=15\\qquad 15\\cdot 8=120$'), answer: { expected: fraction(120) } },
            { id: 47, difficulty: 'medium', question: say('Depositu baten $\\frac{2}{7}$ hustu da eta 35 L geratzen dira. Zenbat litro sartzen dira?', 'Se ha vaciado $\\frac{2}{7}$ de un depósito y quedan 35 L. ¿Cuántos litros caben?', 'أُفرغ $\\frac{2}{7}$ من خزان وبقي 35 لترًا. كم لترًا يتسع؟'), solution: same('$1-\\frac{2}{7}=\\frac{5}{7}\\qquad 35:5=7\\qquad 7\\cdot 7=49$'), answer: { expected: fraction(49) } },
            { id: 48, difficulty: 'hard', question: say('Herentzia: nagusiak $\\frac{1}{3}$, erdikoak gainerakoaren $\\frac{2}{5}$ eta gazteenak 12 000 €. Zenbat da herentzia (€)?', 'Una herencia: el mayor recibe $\\frac{1}{3}$, el mediano $\\frac{2}{5}$ de lo que queda y el pequeño 12 000 €. ¿Cuánto es la herencia (€)?', 'إرث: الأكبر $\\frac{1}{3}$، والأوسط $\\frac{2}{5}$ من الباقي، والأصغر 12 000 €. كم الإرث (€)؟'), solution: same('$1-\\frac{1}{3}-\\frac{2}{5}\\cdot\\frac{2}{3}=\\frac{2}{5}\\qquad 12\\,000:\\frac{2}{5}=30\\,000$'), answer: { expected: fraction(30000) } },
            { id: 49, difficulty: 'hard', question: say('Liburu baten $\\frac{1}{4}$ irakurri dut astelehenean eta gainerakoaren $\\frac{1}{3}$ asteartean. 90 orri geratzen zaizkit. Zenbat orri ditu liburuak?', 'He leído $\\frac{1}{4}$ de un libro el lunes y $\\frac{1}{3}$ de lo que quedaba el martes. Me quedan 90 páginas. ¿Cuántas páginas tiene el libro?', 'قرأت $\\frac{1}{4}$ من كتاب يوم الاثنين و$\\frac{1}{3}$ مما بقي يوم الثلاثاء. بقيت 90 صفحة. كم صفحة في الكتاب؟'), solution: same('$\\frac{1}{3}\\cdot\\frac{3}{4}=\\frac{1}{4}\\qquad 1-\\frac{1}{4}-\\frac{1}{4}=\\frac{1}{2}\\qquad 90:\\frac{1}{2}=180$'), answer: { expected: fraction(180) } },
            { id: 50, difficulty: 'hard', question: say('Depositu bat $\\frac{3}{4}$ beteta dago. Daukanaren $\\frac{2}{3}$ gastatu eta 50 L geratzen dira. Zenbat litro sartzen dira depositu osoan?', 'Un depósito está lleno en sus $\\frac{3}{4}$. Se gasta $\\frac{2}{3}$ de lo que hay y quedan 50 L. ¿Cuántos litros caben en total?', 'خزان مملوء $\\frac{3}{4}$. أُنفق $\\frac{2}{3}$ مما فيه وبقي 50 لترًا. كم لترًا يتسع كله؟'), solution: same('$\\frac{1}{3}\\cdot\\frac{3}{4}=\\frac{1}{4}\\qquad 50:\\frac{1}{4}=200$'), answer: { expected: fraction(200) } }
        ]
    }
]
