import { fraction } from '../../features/unit-v2/math/fraction.ts'
import type { ChallengeItem, DiagnosticQuestion, ExerciseItem, LocalizedText, PracticeItem } from '../../features/unit-v2/types.ts'
import type { LineSpec } from './realLineMap.ts'
import { interval } from './reals.ts'

/* ==========================================================================
   Zenbaki errealak · 4. DBH (aplikatuak) — diagnostic, guided practice,
   exercise bank and challenges from Santillana 4.º ESO Aplicadas unit 1 and
   Anaya 4.º ESO Aplicadas unit 3. Every closed answer is a single number;
   for a radical a√b the exercise asks for a. Exercises about intervals carry
   a LineSpec, drawn under the prompt by index.tsx.
   ========================================================================== */

type WithLine = { line?: LineSpec; solutionLine?: LineSpec }
export type RealsDiagnosticQuestion = DiagnosticQuestion & WithLine
export type RealsPracticeItem = PracticeItem & WithLine
export type RealsChallengeItem = ChallengeItem & WithLine
export type RealsExerciseItem = ExerciseItem & WithLine
export interface RealsExerciseSection {
    id: string
    title: LocalizedText
    items: RealsExerciseItem[]
}

/** Arabic writes the decimal point instead of the comma, so {,} becomes . there */
const say = (eu: string, es: string, ar: string): LocalizedText => ({ eu, es, ar: ar.replace(/\{,\}/g, '.') })
/** Same formula everywhere, decimal point in Arabic */
const same = (value: string): LocalizedText => ({ eu: value, es: value, ar: value.replace(/\{,\}/g, '.') })

export const realsDiagnostic: RealsDiagnosticQuestion[] = [
    {
        id: 4001,
        prompt: same('$\\frac{3}{4}:\\frac{9}{8}=\\ ?$'),
        options: [same('$\\frac{27}{32}$'), same('$\\frac{2}{3}$'), same('$\\frac{3}{2}$')],
        correctIndex: 1,
        explanation: say('Zatitzeko, gurutzean biderkatu: $\\frac{3\\cdot 8}{4\\cdot 9}=\\frac{24}{36}=\\frac{2}{3}$. $\\frac{27}{32}$ zuzenean biderkatzean ateratzen da.', 'Para dividir se multiplica en cruz: $\\frac{3\\cdot 8}{4\\cdot 9}=\\frac{24}{36}=\\frac{2}{3}$. $\\frac{27}{32}$ sale al multiplicar en línea.', 'للقسمة نضرب تبادليًا: $\\frac{3\\cdot 8}{4\\cdot 9}=\\frac{24}{36}=\\frac{2}{3}$. وينتج $\\frac{27}{32}$ عند الضرب المباشر.'),
        topic: 'fraction-ops'
    },
    {
        id: 4002,
        prompt: same('$\\left(\\frac{2}{3}\\right)^{-2}=\\ ?$'),
        options: [same('$-\\frac{4}{9}$'), same('$\\frac{4}{9}$'), same('$\\frac{9}{4}$')],
        correctIndex: 2,
        explanation: say('Berretzaile negatiboa: alderantzizkoa. $\\left(\\frac{3}{2}\\right)^{2}=\\frac{9}{4}$. Emaitza ez da negatiboa.', 'Exponente negativo: el inverso. $\\left(\\frac{3}{2}\\right)^{2}=\\frac{9}{4}$. El resultado no es negativo.', 'الأس السالب: المقلوب. $\\left(\\frac{3}{2}\\right)^{2}=\\frac{9}{4}$. والنتيجة ليست سالبة.'),
        topic: 'powers'
    },
    {
        id: 4003,
        prompt: say('Zer motatakoa da $\\frac{7}{12}$ zatikiaren adierazpen hamartarra?', '¿De qué tipo es la expresión decimal de $\\frac{7}{12}$?', 'ما نوع الصورة العشرية للكسر $\\frac{7}{12}$؟'),
        options: [say('Zehatza', 'Exacta', 'منتهية'), say('Periodiko hutsa', 'Periódica pura', 'دورية بحتة'), say('Periodiko mistoa', 'Periódica mixta', 'دورية مختلطة')],
        correctIndex: 2,
        explanation: say('$12=2^{2}\\cdot 3$: 2 eta beste faktore bat → mistoa. $\\frac{7}{12}=0{,}58\\overline{3}$.', '$12=2^{2}\\cdot 3$: un 2 y otro factor → mixta. $\\frac{7}{12}=0{,}58\\overline{3}$.', '$12=2^{2}\\cdot 3$: 2 وعامل آخر ← مختلطة. $\\frac{7}{12}=0{,}58\\overline{3}$.'),
        topic: 'decimal-kinds'
    },
    {
        id: 4004,
        prompt: same('$0{,}\\overline{3}=\\ ?$'),
        options: [same('$\\frac{3}{10}$'), same('$\\frac{1}{3}$'), same('$\\frac{33}{100}$')],
        correctIndex: 1,
        explanation: say('Periodiko hutsa, periodoa zifra bat: $\\frac{3}{9}=\\frac{1}{3}$. $\\frac{3}{10}=0{,}3$ zehatza da.', 'Periódico puro de una cifra: $\\frac{3}{9}=\\frac{1}{3}$. $\\frac{3}{10}=0{,}3$ es exacto.', 'دوري بحت دوره رقم واحد: $\\frac{3}{9}=\\frac{1}{3}$. أما $\\frac{3}{10}=0{,}3$ فمنتهٍ.'),
        topic: 'periodic-to-fraction'
    },
    {
        id: 4005,
        prompt: say('Zein da zenbaki irrazionala?', '¿Cuál es un número irracional?', 'أيها عدد غير نسبي؟'),
        options: [same('$\\sqrt{16}$'), same('$1{,}\\overline{25}$'), same('$\\sqrt{12}$')],
        correctIndex: 2,
        explanation: say('12 ez da karratu perfektua: $\\sqrt{12}=3{,}4641\\ldots$ periodorik gabe. $\\sqrt{16}=4$ eta $1{,}\\overline{25}$ arrazionalak dira.', '12 no es cuadrado perfecto: $\\sqrt{12}=3{,}4641\\ldots$ sin periodo. $\\sqrt{16}=4$ y $1{,}\\overline{25}$ son racionales.', '12 ليس مربعًا كاملًا: $\\sqrt{12}=3{,}4641\\ldots$ بلا دور. أما $\\sqrt{16}=4$ و$1{,}\\overline{25}$ فنسبيان.'),
        topic: 'irrational'
    },
    {
        id: 4006,
        prompt: say('Zein tarte dago marraztuta?', '¿Qué intervalo está dibujado?', 'ما الفترة المرسومة؟'),
        options: [same('$(-1,\\,3]$'), same('$[-1,\\,3]$'), same('$[-1,\\,3)$')],
        correctIndex: 2,
        explanation: say('−1-en puntua betea da (barne, kortxetea) eta 3-ena hutsa (kanpo, parentesia): $-1\\le x<3$.', 'En −1 el punto es lleno (incluido, corchete) y en 3 vacío (excluido, paréntesis): $-1\\le x<3$.', 'النقطة عند −1 ممتلئة (داخل، قوس معقوف) وعند 3 فارغة (خارج، قوس عادي): $-1\\le x<3$.'),
        topic: 'intervals',
        line: { from: -3, to: 5, intervals: [{ value: interval(-1, 3, true, false) }] }
    },
    {
        id: 4007,
        prompt: say('Nola idazten da $0{,}00072$ idazkera zientifikoan?', '¿Cómo se escribe $0{,}00072$ en notación científica?', 'كيف يُكتب $0{,}00072$ بالترميز العلمي؟'),
        options: [same('$7{,}2\\cdot 10^{4}$'), same('$72\\cdot 10^{-5}$'), same('$7{,}2\\cdot 10^{-4}$')],
        correctIndex: 2,
        explanation: say('Koma 4 jauzi eskuinera → $10^{-4}$. $72\\cdot 10^{-5}$ balio bera da, baina 72 ez dago 1 eta 10 artean.', 'La coma salta 4 lugares a la derecha → $10^{-4}$. $72\\cdot 10^{-5}$ vale lo mismo, pero 72 no está entre 1 y 10.', 'تقفز الفاصلة 4 منازل إلى اليمين ← $10^{-4}$. و$72\\cdot 10^{-5}$ له القيمة نفسها لكن 72 ليس بين 1 و10.'),
        topic: 'scientific'
    },
    {
        id: 4008,
        prompt: same('$\\sqrt{50}=\\ ?$'),
        options: [same('$5\\sqrt{2}$'), same('$25\\sqrt{2}$'), same('$2\\sqrt{5}$')],
        correctIndex: 0,
        explanation: say('$50=5^{2}\\cdot 2$: bikotea (5) errotik ateratzen da: $5\\sqrt{2}$.', '$50=5^{2}\\cdot 2$: la pareja (5) sale de la raíz: $5\\sqrt{2}$.', '$50=5^{2}\\cdot 2$: يخرج الزوج (5) من الجذر: $5\\sqrt{2}$.'),
        topic: 'radical-simplify'
    }
]

export const realsPractice: RealsPracticeItem[] = [
    { id: 1, stage: 'rational', prompt: say('Depositu batek 120 litro ditu eta $\\frac{3}{8}$ hustu dira. Zenbat litro geratzen dira?', 'Un depósito tiene 120 litros y se han vaciado $\\frac{3}{8}$. ¿Cuántos litros quedan?', 'خزان فيه 120 لترًا وأُفرغ منه $\\frac{3}{8}$. كم لترًا بقي؟'), expected: fraction(75), hint: say('Lehenik $\\frac{3}{8}\\cdot 120$.', 'Primero $\\frac{3}{8}\\cdot 120$.', 'أولًا $\\frac{3}{8}\\cdot 120$.'), explanation: same('$\\frac{3}{8}\\cdot 120=45\\qquad 120-45=75$') },
    { id: 2, stage: 'rational', prompt: same('$\\frac{1}{2}+\\frac{3}{4}-\\frac{5}{6}$'), expected: fraction(5, 12), hint: say('Izendatzaile komuna: m.k.t.(2, 4, 6) = 12.', 'Denominador común: m.c.m.(2, 4, 6) = 12.', 'المقام المشترك: م.م.أ.(2، 4، 6) = 12.'), explanation: same('$\\frac{6}{12}+\\frac{9}{12}-\\frac{10}{12}=\\frac{5}{12}$') },
    { id: 3, stage: 'rational', prompt: same('$\\left(\\frac{4}{3}+\\frac{2}{5}\\right)-\\left(\\frac{1}{6}+\\frac{5}{3}\\right)$'), expected: fraction(-1, 10), hint: say('Egin parentesi bakoitza; gero kendu. m.k.t. = 30.', 'Haz cada paréntesis y después resta. m.c.m. = 30.', 'احسب كل قوس ثم اطرح. م.م.أ. = 30.'), explanation: same('$\\frac{26}{15}-\\frac{11}{6}=\\frac{52}{30}-\\frac{55}{30}=-\\frac{3}{30}=-\\frac{1}{10}$') },
    { id: 4, stage: 'rational', prompt: same('$\\left(\\frac{3}{2}\\right)^{-2}\\cdot\\left(\\frac{3}{2}\\right)^{5}$'), expected: fraction(27, 8), hint: say('Oinarri bera: batu berretzaileak.', 'Misma base: suma los exponentes.', 'الأساس نفسه: اجمع الأسس.'), explanation: same('$\\left(\\frac{3}{2}\\right)^{-2+5}=\\left(\\frac{3}{2}\\right)^{3}=\\frac{27}{8}$') },
    { id: 5, stage: 'decimals', prompt: say('Idatzi $\\frac{13}{5}$ zenbaki hamartar gisa.', 'Escribe $\\frac{13}{5}$ como número decimal.', 'اكتب $\\frac{13}{5}$ عددًا عشريًا.'), expected: fraction(13, 5), hint: say('Zatitu 13 : 5.', 'Divide 13 : 5.', 'اقسم 13 : 5.'), explanation: say('$13:5=2{,}6$: hamartar zehatza (izendatzailea 5).', '$13:5=2{,}6$: decimal exacto (denominador 5).', '$13:5=2{,}6$: عشري منتهٍ (المقام 5).') },
    { id: 6, stage: 'decimals', prompt: say('Idatzi $0{,}0016$ zatiki laburtezin gisa.', 'Escribe $0{,}0016$ como fracción irreducible.', 'اكتب $0{,}0016$ كسرًا غير قابل للاختزال.'), expected: fraction(1, 625), answerForm: 'simplified', hint: say('Lau hamartar: izendatzailea 10 000.', 'Cuatro decimales: denominador 10 000.', 'أربع منازل: المقام 10 000.'), explanation: same('$\\frac{16}{10\\,000}=\\frac{1}{625}$') },
    { id: 7, stage: 'decimals', prompt: say('Idatzi $2{,}\\overline{4}$ zatiki gisa.', 'Escribe $2{,}\\overline{4}$ como fracción.', 'اكتب $2{,}\\overline{4}$ كسرًا.'), expected: fraction(22, 9), hint: say('Periodiko hutsa: (24 − 2) zati 9.', 'Periódico puro: (24 − 2) entre 9.', 'دوري بحت: (24 − 2) على 9.'), explanation: same('$\\frac{24-2}{9}=\\frac{22}{9}$') },
    { id: 8, stage: 'decimals', prompt: say('Idatzi $1{,}2\\overline{3}$ zatiki laburtezin gisa.', 'Escribe $1{,}2\\overline{3}$ como fracción irreducible.', 'اكتب $1{,}2\\overline{3}$ كسرًا غير قابل للاختزال.'), expected: fraction(37, 30), answerForm: 'simplified', hint: say('Mistoa: periodoa (3) → 9; aurreperiodoa (2) → 0: izendatzailea 90.', 'Mixto: periodo (3) → 9; anteperiodo (2) → 0: denominador 90.', 'مختلط: الدور (3) ← 9؛ ما قبله (2) ← 0: المقام 90.'), explanation: same('$\\frac{123-12}{90}=\\frac{111}{90}=\\frac{37}{30}$') },
    { id: 9, stage: 'reals', prompt: say('$\\sqrt{21}$ bi zenbaki osoren artean dago. Idatzi txikiena.', '$\\sqrt{21}$ está entre dos números enteros. Escribe el menor.', '$\\sqrt{21}$ يقع بين عددين صحيحين. اكتب الأصغر.'), expected: fraction(4), hint: say('Bilatu 21en inguruko karratuak.', 'Busca los cuadrados cercanos a 21.', 'ابحث عن المربعات القريبة من 21.'), explanation: same('$16<21<25\\ \\to\\ 4<\\sqrt{21}<5$') },
    { id: 10, stage: 'reals', prompt: say('Zenbat zenbaki oso daude $[-3,\\,7)$ tartean?', '¿Cuántos números enteros hay en el intervalo $[-3,\\,7)$?', 'كم عددًا صحيحًا في الفترة $[-3,\\,7)$؟'), expected: fraction(10), hint: say('−3 barne dago; 7 ez.', 'El −3 está incluido; el 7 no.', '−3 داخل و7 ليس داخلًا.'), explanation: say('$-3,\\,-2,\\ldots,\\,6$: 10 zenbaki.', '$-3,\\,-2,\\ldots,\\,6$: 10 números.', '$-3,\\,-2,\\ldots,\\,6$: 10 أعداد.'), line: { from: -4, to: 8, intervals: [{ value: interval(-3, 7, true, false) }] } },
    { id: 11, stage: 'reals', prompt: say('$A=[-3,\\,7)$ eta $B=(5,\\,+\\infty)$. Bien zenbaki komunak $(5,\\,a)$ tartea dira. Zenbat da $a$?', '$A=[-3,\\,7)$ y $B=(5,\\,+\\infty)$. Los números comunes a los dos forman el intervalo $(5,\\,a)$. ¿Cuánto vale $a$?', '$A=[-3,\\,7)$ و$B=(5,\\,+\\infty)$. الأعداد المشتركة بينهما تكوّن الفترة $(5,\\,a)$. كم تساوي $a$؟'), expected: fraction(7), hint: say('Begiratu non gainjartzen diren bi marrak.', 'Mira dónde se solapan las dos bandas.', 'انظر أين يتداخل الشريطان.'), explanation: same('$A\\cap B=(5,\\,7)$'), line: { from: -4, to: 10, intervals: [{ value: interval(-3, 7, true, false) }, { value: interval(5, null, false, false), color: 'second', lift: 22 }] } },
    { id: 12, stage: 'reals', prompt: say('Zenbat zenbaki oso dira $-2\\le x<3$ betetzen dutenak?', '¿Cuántos números enteros cumplen $-2\\le x<3$?', 'كم عددًا صحيحًا يحقق $-2\\le x<3$؟'), expected: fraction(5), hint: say('−2 barne, 3 ez.', '−2 incluido, 3 no.', '−2 داخل و3 لا.'), explanation: say('$-2,\\,-1,\\,0,\\,1,\\,2$: 5 zenbaki.', '$-2,\\,-1,\\,0,\\,1,\\,2$: 5 números.', '$-2,\\,-1,\\,0,\\,1,\\,2$: 5 أعداد.') },
    { id: 13, stage: 'approx', prompt: say('Biribildu $15{,}107$ ehunenetara.', 'Redondea $15{,}107$ a las centésimas.', 'قرّب $15{,}107$ إلى الأجزاء من مئة.'), expected: fraction(1511, 100), hint: say('Kentzen den lehen zifra 7 da.', 'La primera cifra suprimida es 7.', 'أول رقم محذوف هو 7.'), explanation: same('$15{,}107\\approx 15{,}11$') },
    { id: 14, stage: 'approx', prompt: say('1 m-ko hari bat 8 zati berdinetan moztu da, eta zati bakoitza 0,12 m dela esan da. Zein da errore absolutua (m)?', 'Un cable de 1 m se corta en 8 trozos iguales y se dice que cada trozo mide 0,12 m. ¿Cuál es el error absoluto (m)?', 'قُطع سلك طوله 1 م إلى 8 قطع متساوية وقيل إن كل قطعة 0.12 م. ما الخطأ المطلق (م)؟'), expected: fraction(1, 200), hint: say('Benetan, $\\frac{1}{8}=0{,}125$ m.', 'En realidad $\\frac{1}{8}=0{,}125$ m.', 'في الحقيقة $\\frac{1}{8}=0{,}125$ م.'), explanation: same('$E_a=|0{,}125-0{,}12|=0{,}005$') },
    { id: 15, stage: 'approx', prompt: say('$9\\,170\\,000\\,000=9{,}17\\cdot 10^{n}$. Zenbat da $n$?', '$9\\,170\\,000\\,000=9{,}17\\cdot 10^{n}$. ¿Cuánto vale $n$?', '$9\\,170\\,000\\,000=9{,}17\\cdot 10^{n}$. كم تساوي $n$؟'), expected: fraction(9), hint: say('Zenbatu komaren jauziak 9aren ondoraino.', 'Cuenta los saltos de la coma hasta detrás del 9.', 'عُدّ قفزات الفاصلة حتى بعد الرقم 9.'), explanation: same('$9\\,170\\,000\\,000=9{,}17\\cdot 10^{9}$') },
    { id: 16, stage: 'approx', prompt: say('$(4\\cdot 10^{-7})\\cdot(6{,}3\\cdot 10^{12})=2{,}52\\cdot 10^{n}$. Zenbat da $n$?', '$(4\\cdot 10^{-7})\\cdot(6{,}3\\cdot 10^{12})=2{,}52\\cdot 10^{n}$. ¿Cuánto vale $n$?', '$(4\\cdot 10^{-7})\\cdot(6{,}3\\cdot 10^{12})=2{,}52\\cdot 10^{n}$. كم تساوي $n$؟'), expected: fraction(6), hint: say('$4\\cdot 6{,}3=25{,}2$: komaren jauzi batek berretzaileari 1 gehitzen dio.', '$4\\cdot 6{,}3=25{,}2$: un salto de la coma suma 1 al exponente.', '$4\\cdot 6{,}3=25{,}2$: قفزة الفاصلة تضيف 1 إلى الأس.'), explanation: same('$25{,}2\\cdot 10^{5}=2{,}52\\cdot 10^{6}$') },
    { id: 17, stage: 'radicals', prompt: same('$\\sqrt[3]{343}$'), expected: fraction(7), hint: say('Zein zenbakiren kuboa da 343?', '¿De qué número es 343 el cubo?', '343 مكعب أي عدد؟'), explanation: same('$7^{3}=343\\ \\to\\ \\sqrt[3]{343}=7$') },
    { id: 18, stage: 'radicals', prompt: same('$16^{\\frac{3}{4}}$'), expected: fraction(8), hint: say('$16=2^{4}$.', '$16=2^{4}$.', '$16=2^{4}$.'), explanation: same('$(2^{4})^{\\frac{3}{4}}=2^{3}=8$') },
    { id: 19, stage: 'radicals', prompt: say('$\\sqrt{200}=a\\sqrt{2}$. Zenbat da $a$?', '$\\sqrt{200}=a\\sqrt{2}$. ¿Cuánto vale $a$?', '$\\sqrt{200}=a\\sqrt{2}$. كم تساوي $a$؟'), expected: fraction(10), hint: say('$200=2^{2}\\cdot 5^{2}\\cdot 2$.', '$200=2^{2}\\cdot 5^{2}\\cdot 2$.', '$200=2^{2}\\cdot 5^{2}\\cdot 2$.'), explanation: same('$\\sqrt{200}=2\\cdot 5\\sqrt{2}=10\\sqrt{2}$') },
    { id: 20, stage: 'radicals', prompt: say('$\\sqrt{12}+\\sqrt{75}-\\sqrt{27}=a\\sqrt{3}$. Zenbat da $a$?', '$\\sqrt{12}+\\sqrt{75}-\\sqrt{27}=a\\sqrt{3}$. ¿Cuánto vale $a$?', '$\\sqrt{12}+\\sqrt{75}-\\sqrt{27}=a\\sqrt{3}$. كم تساوي $a$؟'), expected: fraction(4), hint: say('Atera faktoreak: $\\sqrt{12}=2\\sqrt{3}$…', 'Extrae factores: $\\sqrt{12}=2\\sqrt{3}$…', 'أخرج العوامل: $\\sqrt{12}=2\\sqrt{3}$…'), explanation: same('$2\\sqrt{3}+5\\sqrt{3}-3\\sqrt{3}=4\\sqrt{3}$') }
]

export const realsChallenges: RealsChallengeItem[] = [
    { id: 101, stage: 'rational', context: 'starter', points: 10, prompt: say('Anek pizza baten $\\frac{3}{8}$ jan du eta Jonek gainerakoaren $\\frac{2}{5}$. Pizzaren zer zati geratzen da?', 'Ane se ha comido $\\frac{3}{8}$ de una pizza y Jon $\\frac{2}{5}$ de lo que quedaba. ¿Qué fracción de la pizza queda?', 'أكلت آنه $\\frac{3}{8}$ من بيتزا وأكل جون $\\frac{2}{5}$ مما بقي. ما الكسر الباقي من البيتزا؟'), expected: fraction(3, 8), hint: say('Anen ondoren $\\frac{5}{8}$ geratzen da; Jonek horren $\\frac{2}{5}$ jaten du.', 'Tras Ane quedan $\\frac{5}{8}$; Jon se come $\\frac{2}{5}$ de eso.', 'بعد آنه يبقى $\\frac{5}{8}$؛ يأكل جون $\\frac{2}{5}$ منه.'), explanation: same('$\\frac{2}{5}\\cdot\\frac{5}{8}=\\frac{1}{4}\\qquad \\frac{5}{8}-\\frac{1}{4}=\\frac{3}{8}$') },
    { id: 102, stage: 'rational', context: 'advanced', points: 20, prompt: same('$\\left(\\frac{2}{3}\\right)^{3}:\\left(\\frac{2}{3}\\right)^{-3}$'), expected: fraction(64, 729), hint: say('Oinarri bera zatitzean, kendu berretzaileak: $3-(-3)$.', 'Al dividir con la misma base, resta los exponentes: $3-(-3)$.', 'عند القسمة بالأساس نفسه اطرح الأسس: $3-(-3)$.'), explanation: same('$\\left(\\frac{2}{3}\\right)^{6}=\\frac{64}{729}$') },
    { id: 103, stage: 'decimals', context: 'starter', points: 10, prompt: same('$0{,}\\overline{15}+0{,}\\overline{45}$'), expected: fraction(20, 33), hint: say('Bihurtu biak zatiki: izendatzailea 99.', 'Pasa los dos a fracción: denominador 99.', 'حوّل العددين إلى كسرين: المقام 99.'), explanation: same('$\\frac{15}{99}+\\frac{45}{99}=\\frac{60}{99}=\\frac{20}{33}$') },
    { id: 104, stage: 'decimals', context: 'advanced', points: 20, prompt: say('Idatzi $3{,}7\\overline{5}$ zatiki laburtezin gisa.', 'Escribe $3{,}7\\overline{5}$ como fracción irreducible.', 'اكتب $3{,}7\\overline{5}$ كسرًا غير قابل للاختزال.'), expected: fraction(169, 45), answerForm: 'simplified', hint: say('$\\frac{375-37}{90}$', '$\\frac{375-37}{90}$', '$\\frac{375-37}{90}$'), explanation: same('$\\frac{338}{90}=\\frac{169}{45}$') },
    { id: 105, stage: 'decimals', context: 'master', points: 30, prompt: say('$x=0{,}\\overline{9}=0{,}999\\ldots$ Aplikatu zatiki sortzailearen araua. Zenbat da $x$?', '$x=0{,}\\overline{9}=0{,}999\\ldots$ Aplica la regla de la fracción generatriz. ¿Cuánto vale $x$?', '$x=0{,}\\overline{9}=0{,}999\\ldots$ طبّق قاعدة الكسر المولّد. كم تساوي $x$؟'), expected: fraction(1), hint: say('Periodiko hutsa, zifra bat: $\\frac{9}{9}$.', 'Periódico puro de una cifra: $\\frac{9}{9}$.', 'دوري بحت من رقم واحد: $\\frac{9}{9}$.'), explanation: say('$\\frac{9}{9}=1$: $0{,}\\overline{9}$ eta 1 zenbaki bera dira.', '$\\frac{9}{9}=1$: $0{,}\\overline{9}$ y 1 son el mismo número.', '$\\frac{9}{9}=1$: العددان $0{,}\\overline{9}$ و1 عدد واحد.') },
    { id: 106, stage: 'reals', context: 'starter', points: 10, prompt: say('$\\sqrt{50}$ bi zenbaki oso jarraituren artean dago. Idatzi handiena.', '$\\sqrt{50}$ está entre dos enteros consecutivos. Escribe el mayor.', '$\\sqrt{50}$ يقع بين عددين صحيحين متتاليين. اكتب الأكبر.'), expected: fraction(8), hint: say('$7^{2}=49$ eta $8^{2}=64$.', '$7^{2}=49$ y $8^{2}=64$.', '$7^{2}=49$ و$8^{2}=64$.'), explanation: same('$49<50<64\\ \\to\\ 7<\\sqrt{50}<8$') },
    { id: 107, stage: 'reals', context: 'advanced', points: 20, prompt: say('$A=[-2,\\,4]$ eta $B=(1,\\,6)$. Zenbat zenbaki oso daude bi tarteetan aldi berean?', '$A=[-2,\\,4]$ y $B=(1,\\,6)$. ¿Cuántos enteros están a la vez en los dos intervalos?', '$A=[-2,\\,4]$ و$B=(1,\\,6)$. كم عددًا صحيحًا في الفترتين معًا؟'), expected: fraction(3), hint: say('Ebakidura: $(1,\\,4]$.', 'La intersección: $(1,\\,4]$.', 'التقاطع: $(1,\\,4]$.'), explanation: say('$A\\cap B=(1,\\,4]$: 2, 3 eta 4.', '$A\\cap B=(1,\\,4]$: 2, 3 y 4.', '$A\\cap B=(1,\\,4]$: 2 و3 و4.'), line: { from: -3, to: 7, intervals: [{ value: interval(-2, 4, true, true) }, { value: interval(1, 6, false, false), color: 'second', lift: 22 }] } },
    { id: 108, stage: 'reals', context: 'master', points: 30, prompt: say('Karratu baten azalera 72 cm² da. Bere aldea irrazionala da, baina diagonala ez. Zenbat cm neurtzen du diagonalak?', 'Un cuadrado tiene 72 cm² de área. Su lado es irracional, pero su diagonal no. ¿Cuántos cm mide la diagonal?', 'مساحة مربع 72 سم². ضلعه غير نسبي لكن قطره نسبي. كم سم طول القطر؟'), expected: fraction(12), hint: say('Aldea $\\sqrt{72}$; diagonala $\\sqrt{l^{2}+l^{2}}$.', 'El lado mide $\\sqrt{72}$; la diagonal, $\\sqrt{l^{2}+l^{2}}$.', 'الضلع $\\sqrt{72}$ والقطر $\\sqrt{l^{2}+l^{2}}$.'), explanation: same('$d=\\sqrt{72+72}=\\sqrt{144}=12$') },
    { id: 109, stage: 'approx', context: 'starter', points: 10, prompt: say('22 loreko sorta batek 19 € balio du. Zenbat balio du lore batek, zentimoetara biribilduta?', 'Un ramo de 22 flores cuesta 19 €. ¿Cuánto cuesta una flor, redondeando a los céntimos?', 'باقة من 22 زهرة ثمنها 19 €. كم ثمن الزهرة مقرّبًا إلى السنت؟'), expected: fraction(43, 50), hint: say('$19:22=0{,}8636\\ldots$', '$19:22=0{,}8636\\ldots$', '$19:22=0{,}8636\\ldots$'), explanation: same('$19:22=0{,}8\\overline{63}\\approx 0{,}86$') },
    { id: 110, stage: 'approx', context: 'advanced', points: 20, prompt: say('Óscarren abiadura-neurgailuak 27 km/h adierazi ditu, baina benetako abiadura hori baino % 3 txikiagoa izan da. Zein izan da benetako abiadura (km/h)?', 'El velocímetro de Óscar ha marcado 27 km/h, pero la velocidad real ha sido un 3 % menor. ¿Cuál ha sido la velocidad real (km/h)?', 'أظهر عداد سرعة أوسكار 27 كم/س، لكن السرعة الحقيقية كانت أقل بـ 3 %. ما السرعة الحقيقية (كم/س)؟'), expected: fraction(2619, 100), hint: say('% 3 txikiagoa: erakutsitakoaren % 97.', 'Un 3 % menor: el 97 % de lo marcado.', 'أقل بـ 3 %: أي 97 % من المعروض.'), explanation: same('$0{,}97\\cdot 27=26{,}19$') },
    { id: 111, stage: 'approx', context: 'master', points: 30, prompt: say('Gizon batek $4{,}7\\cdot 10^{6}$ globulu gorri ditu mm³ bakoitzeko (1 L = $10^{6}$ mm³) eta 5,5 L odol. Guztira $2{,}585\\cdot 10^{n}$ globulu gorri. Zenbat da $n$?', 'Un hombre tiene $4{,}7\\cdot 10^{6}$ glóbulos rojos por mm³ (1 L = $10^{6}$ mm³) y 5,5 L de sangre. En total, $2{,}585\\cdot 10^{n}$ glóbulos rojos. ¿Cuánto vale $n$?', 'لدى رجل $4{,}7\\cdot 10^{6}$ كرية حمراء في كل مم³ (1 لتر = $10^{6}$ مم³) و5.5 لتر من الدم. المجموع $2{,}585\\cdot 10^{n}$ كرية حمراء. كم تساوي $n$؟'), expected: fraction(13), hint: say('Litro batean: $4{,}7\\cdot 10^{12}$. Gero bider 5,5.', 'En un litro: $4{,}7\\cdot 10^{12}$. Después por 5,5.', 'في لتر: $4{,}7\\cdot 10^{12}$. ثم في 5.5.'), explanation: same('$5{,}5\\cdot 4{,}7\\cdot 10^{12}=25{,}85\\cdot 10^{12}=2{,}585\\cdot 10^{13}$') },
    { id: 112, stage: 'radicals', context: 'starter', points: 10, prompt: same('$\\sqrt{2}\\cdot\\sqrt{3}\\cdot\\sqrt{6}$'), expected: fraction(6), hint: say('Indize bera: elkartu errokizunak.', 'Mismo índice: junta los radicandos.', 'الدليل نفسه: اجمع ما تحت الجذور.'), explanation: same('$\\sqrt{2\\cdot 3\\cdot 6}=\\sqrt{36}=6$') },
    { id: 113, stage: 'radicals', context: 'advanced', points: 20, prompt: say('5 cm-ko altuera duen zilindro baten bolumena $60\\pi$ cm³ da. Erradioa $r=a\\sqrt{3}$ cm da. Zenbat da $a$?', 'Un cilindro de 5 cm de altura tiene un volumen de $60\\pi$ cm³. Su radio es $r=a\\sqrt{3}$ cm. ¿Cuánto vale $a$?', 'أسطوانة ارتفاعها 5 سم وحجمها $60\\pi$ سم³. نصف قطرها $r=a\\sqrt{3}$ سم. كم تساوي $a$؟'), expected: fraction(2), hint: say('$\\pi r^{2}\\cdot 5=60\\pi\\ \\to\\ r^{2}=12$.', '$\\pi r^{2}\\cdot 5=60\\pi\\ \\to\\ r^{2}=12$.', '$\\pi r^{2}\\cdot 5=60\\pi\\ \\to\\ r^{2}=12$.'), explanation: same('$r=\\sqrt{12}=2\\sqrt{3}$') },
    { id: 114, stage: 'radicals', context: 'master', points: 30, prompt: say('$(3\\sqrt{2}+2)^{2}=p+q\\sqrt{2}$, $p$ eta $q$ osoak izanik. Zenbat da $p$?', '$(3\\sqrt{2}+2)^{2}=p+q\\sqrt{2}$, con $p$ y $q$ enteros. ¿Cuánto vale $p$?', '$(3\\sqrt{2}+2)^{2}=p+q\\sqrt{2}$ حيث $p$ و$q$ صحيحان. كم تساوي $p$؟'), expected: fraction(22), hint: say('$(a+b)^{2}=a^{2}+2ab+b^{2}$ eta $(3\\sqrt{2})^{2}=18$.', '$(a+b)^{2}=a^{2}+2ab+b^{2}$ y $(3\\sqrt{2})^{2}=18$.', '$(a+b)^{2}=a^{2}+2ab+b^{2}$ و$(3\\sqrt{2})^{2}=18$.'), explanation: same('$18+12\\sqrt{2}+4=22+12\\sqrt{2}$') }
]

export const realsExerciseBank: RealsExerciseSection[] = [
    {
        id: 'rational',
        title: say('Zenbaki arrazionalak', 'Números racionales', 'الأعداد النسبية'),
        items: [
            { id: 1, difficulty: 'easy', question: say('Arturok 80 ateren $\\frac{2}{5}$ margotu ditu eta Celiak $\\frac{1}{2}$. Zenbat ate margotu ditu bakoitzak eta zenbat geratzen dira?', 'Arturo ha pintado $\\frac{2}{5}$ de 80 puertas y Celia $\\frac{1}{2}$. ¿Cuántas ha pintado cada uno y cuántas quedan?', 'دهن أرتورو $\\frac{2}{5}$ من 80 بابًا ودهنت سيليا $\\frac{1}{2}$. كم دهن كل منهما وكم بقي؟'), solution: say('Arturo: $\\frac{2}{5}\\cdot 80=32$. Celia: $\\frac{1}{2}\\cdot 80=40$. Geratzen dira $80-72=8$.', 'Arturo: $\\frac{2}{5}\\cdot 80=32$. Celia: $\\frac{1}{2}\\cdot 80=40$. Quedan $80-72=8$.', 'أرتورو: $\\frac{2}{5}\\cdot 80=32$. سيليا: $\\frac{1}{2}\\cdot 80=40$. بقي $80-72=8$.') },
            { id: 2, difficulty: 'easy', question: say('Ordenatu: $\\frac{8}{5}$ eta $\\frac{3}{7}$; $\\frac{13}{18}$ eta $\\frac{5}{12}$.', 'Ordena: $\\frac{8}{5}$ y $\\frac{3}{7}$; $\\frac{13}{18}$ y $\\frac{5}{12}$.', 'رتّب: $\\frac{8}{5}$ و$\\frac{3}{7}$؛ $\\frac{13}{18}$ و$\\frac{5}{12}$.'), solution: same('$\\frac{56}{35}>\\frac{15}{35}\\to\\frac{8}{5}>\\frac{3}{7}\\qquad \\frac{26}{36}>\\frac{15}{36}\\to\\frac{13}{18}>\\frac{5}{12}$') },
            { id: 3, difficulty: 'easy', question: same('$\\frac{1}{8}+\\frac{3}{4}-\\frac{6}{5}$'), solution: same('$\\frac{5+30-48}{40}=-\\frac{13}{40}$'), answer: { expected: fraction(-13, 40) } },
            { id: 4, difficulty: 'medium', question: same('$\\left(\\frac{5}{4}-\\frac{1}{5}\\right)\\cdot\\left(\\frac{2}{7}+\\frac{1}{4}\\right)$'), solution: same('$\\frac{21}{20}\\cdot\\frac{15}{28}=\\frac{315}{560}=\\frac{9}{16}$'), answer: { expected: fraction(9, 16) } },
            { id: 5, difficulty: 'medium', question: same('$\\left(-\\frac{5}{2}\\right)^{4}$'), solution: same('$\\frac{5^{4}}{2^{4}}=\\frac{625}{16}$'), answer: { expected: fraction(625, 16) } },
            { id: 6, difficulty: 'medium', question: same('$\\left(\\frac{3}{8}\\right)^{9}:\\left(\\frac{3}{8}\\right)^{5}$'), solution: same('$\\left(\\frac{3}{8}\\right)^{4}=\\frac{81}{4096}$'), answer: { expected: fraction(81, 4096) } },
            { id: 7, difficulty: 'hard', question: same('$\\left(\\frac{1}{2}-\\frac{1}{3}\\right)^{-2}:\\left(1-\\frac{5}{6}\\right)^{-1}$'), solution: same('$\\left(\\frac{1}{6}\\right)^{-2}:\\left(\\frac{1}{6}\\right)^{-1}=36:6=6$'), answer: { expected: fraction(6) } },
            { id: 8, difficulty: 'hard', question: say('Andonik liburu baten $\\frac{1}{3}$ irakurri du astelehenean eta gainerakoaren $\\frac{1}{4}$ asteartean. 120 orri geratzen zaizkio. Zenbat orri ditu liburuak?', 'Andoni ha leído $\\frac{1}{3}$ de un libro el lunes y $\\frac{1}{4}$ del resto el martes. Le quedan 120 páginas. ¿Cuántas páginas tiene el libro?', 'قرأ أندوني $\\frac{1}{3}$ كتاب يوم الاثنين و$\\frac{1}{4}$ الباقي يوم الثلاثاء. بقيت له 120 صفحة. كم صفحة في الكتاب؟'), solution: same('$\\frac{1}{4}\\cdot\\frac{2}{3}=\\frac{1}{6}\\qquad \\frac{2}{3}-\\frac{1}{6}=\\frac{1}{2}\\qquad 120\\cdot 2=240$'), answer: { expected: fraction(240) } },
            { id: 9, difficulty: 'hard', question: same('$\\left(-\\frac{1}{7}\\right)^{-4}$'), solution: same('$(-7)^{4}=7^{4}=2401$'), answer: { expected: fraction(2401) } }
        ]
    },
    {
        id: 'decimals',
        title: say('Hamartarrak eta zatikiak', 'Decimales y fracciones', 'الأعداد العشرية والكسور'),
        items: [
            { id: 10, difficulty: 'easy', question: say('Idatzi hamartar gisa eta sailkatu: $\\frac{9}{5}$, $\\frac{11}{6}$, $\\frac{2}{3}$, $\\frac{8}{11}$.', 'Escribe como decimal y clasifica: $\\frac{9}{5}$, $\\frac{11}{6}$, $\\frac{2}{3}$, $\\frac{8}{11}$.', 'اكتب عددًا عشريًا وصنّف: $\\frac{9}{5}$ و$\\frac{11}{6}$ و$\\frac{2}{3}$ و$\\frac{8}{11}$.'), solution: say('$1{,}8$ zehatza · $1{,}8\\overline{3}$ mistoa · $0{,}\\overline{6}$ hutsa · $0{,}\\overline{72}$ hutsa.', '$1{,}8$ exacto · $1{,}8\\overline{3}$ mixto · $0{,}\\overline{6}$ puro · $0{,}\\overline{72}$ puro.', '$1{,}8$ منتهٍ · $1{,}8\\overline{3}$ مختلط · $0{,}\\overline{6}$ بحت · $0{,}\\overline{72}$ بحت.') },
            { id: 11, difficulty: 'easy', question: say('Idatzi $0{,}245$ zatiki laburtezin gisa.', 'Escribe $0{,}245$ como fracción irreducible.', 'اكتب $0{,}245$ كسرًا غير قابل للاختزال.'), solution: same('$\\frac{245}{1000}=\\frac{49}{200}$'), answer: { expected: fraction(49, 200), form: 'simplified' } },
            { id: 12, difficulty: 'easy', question: say('Idatzi $53{,}47$ zatiki gisa.', 'Escribe $53{,}47$ como fracción.', 'اكتب $53{,}47$ كسرًا.'), solution: same('$53{,}47=\\frac{5347}{100}$'), answer: { expected: fraction(5347, 100) } },
            { id: 13, difficulty: 'medium', question: say('Zatiketa egin gabe, esan zer hamartar mota emango duten: $\\frac{7}{40}$, $\\frac{5}{21}$, $\\frac{1}{15}$.', 'Sin dividir, di qué tipo de decimal darán: $\\frac{7}{40}$, $\\frac{5}{21}$, $\\frac{1}{15}$.', 'دون قسمة، قل ما نوع العدد العشري الناتج: $\\frac{7}{40}$ و$\\frac{5}{21}$ و$\\frac{1}{15}$.'), solution: say('$40=2^{3}\\cdot 5$: zehatza. $21=3\\cdot 7$: periodiko hutsa. $15=3\\cdot 5$: periodiko mistoa.', '$40=2^{3}\\cdot 5$: exacto. $21=3\\cdot 7$: periódico puro. $15=3\\cdot 5$: periódico mixto.', '$40=2^{3}\\cdot 5$: منتهٍ. $21=3\\cdot 7$: دوري بحت. $15=3\\cdot 5$: دوري مختلط.') },
            { id: 14, difficulty: 'medium', question: say('Idatzi $0{,}\\overline{72}$ zatiki laburtezin gisa.', 'Escribe $0{,}\\overline{72}$ como fracción irreducible.', 'اكتب $0{,}\\overline{72}$ كسرًا غير قابل للاختزال.'), solution: same('$\\frac{72}{99}=\\frac{8}{11}$'), answer: { expected: fraction(8, 11), form: 'simplified' } },
            { id: 15, difficulty: 'medium', question: say('Arrazionalak ala irrazionalak? a) $2{,}449489743\\ldots$ b) $3{,}16227766\\ldots$ c) $5{,}2487524875\\ldots$ d) $0{,}151515\\ldots$', '¿Racionales o irracionales? a) $2{,}449489743\\ldots$ b) $3{,}16227766\\ldots$ c) $5{,}2487524875\\ldots$ d) $0{,}151515\\ldots$', 'نسبية أم غير نسبية؟ أ) $2{,}449489743\\ldots$ ب) $3{,}16227766\\ldots$ ج) $5{,}2487524875\\ldots$ د) $0{,}151515\\ldots$'), solution: say('a) eta b) irrazionalak (periodorik ez). c) $5{,}\\overline{24875}$ eta d) $0{,}\\overline{15}$ arrazionalak.', 'a) y b) irracionales (sin periodo). c) $5{,}\\overline{24875}$ y d) $0{,}\\overline{15}$ racionales.', 'أ) وب) غير نسبيين (بلا دور). ج) $5{,}\\overline{24875}$ ود) $0{,}\\overline{15}$ نسبيان.') },
            { id: 16, difficulty: 'medium', question: say('Idatzi $-3{,}7\\overline{5}$ zatiki gisa.', 'Escribe $-3{,}7\\overline{5}$ como fracción.', 'اكتب $-3{,}7\\overline{5}$ كسرًا.'), solution: same('$-\\frac{375-37}{90}=-\\frac{338}{90}=-\\frac{169}{45}$'), answer: { expected: fraction(-169, 45) } },
            { id: 17, difficulty: 'hard', question: say('Idatzi $1{,}58\\overline{3}$ zatiki laburtezin gisa.', 'Escribe $1{,}58\\overline{3}$ como fracción irreducible.', 'اكتب $1{,}58\\overline{3}$ كسرًا غير قابل للاختزال.'), solution: same('$\\frac{1583-158}{900}=\\frac{1425}{900}=\\frac{19}{12}$'), answer: { expected: fraction(19, 12), form: 'simplified' } },
            { id: 18, difficulty: 'hard', question: say('Lore-sortak: 12 lore 10 €-tan, 16 lore 14 €-tan eta 22 lore 19 €-tan. Kalkulatu lore baten prezioa sorta bakoitzean (zer hamartar mota da?) eta esan zein den merkeena.', 'Ramos de flores: 12 flores por 10 €, 16 por 14 € y 22 por 19 €. Calcula el precio de una flor en cada ramo (¿qué tipo de decimal es?) y di cuál es el más barato.', 'باقات زهور: 12 زهرة بـ 10 € و16 بـ 14 € و22 بـ 19 €. احسب ثمن الزهرة في كل باقة (ما نوع العدد العشري؟) وقل أيها الأرخص.'), solution: say('$\\frac{10}{12}=0{,}8\\overline{3}$ (mistoa) · $\\frac{14}{16}=0{,}875$ (zehatza) · $\\frac{19}{22}=0{,}8\\overline{63}$ (mistoa). Merkeena: 10 €-ko sorta.', '$\\frac{10}{12}=0{,}8\\overline{3}$ (mixto) · $\\frac{14}{16}=0{,}875$ (exacto) · $\\frac{19}{22}=0{,}8\\overline{63}$ (mixto). El más barato: el ramo de 10 €.', '$\\frac{10}{12}=0{,}8\\overline{3}$ (مختلط) · $\\frac{14}{16}=0{,}875$ (منتهٍ) · $\\frac{19}{22}=0{,}8\\overline{63}$ (مختلط). الأرخص: باقة 10 €.') },
            { id: 19, difficulty: 'hard', question: same('$0{,}\\overline{3}+0{,}\\overline{6}$'), solution: same('$\\frac{3}{9}+\\frac{6}{9}=\\frac{9}{9}=1$'), answer: { expected: fraction(1) } }
        ]
    },
    {
        id: 'reals',
        title: say('Irrazionalak eta zuzen erreala', 'Irracionales y recta real', 'غير النسبية والمستقيم الحقيقي'),
        items: [
            { id: 20, difficulty: 'easy', question: say('Sailkatu $\\mathbb{N}$, $\\mathbb{Z}$, $\\mathbb{Q}$ edo irrazionaletan: $-4$, $\\frac{13}{6}$, $\\sqrt{5}$, $2{,}\\overline{7}$, $1+\\sqrt{3}$, $152$, $\\pi$.', 'Clasifica en $\\mathbb{N}$, $\\mathbb{Z}$, $\\mathbb{Q}$ o irracionales: $-4$, $\\frac{13}{6}$, $\\sqrt{5}$, $2{,}\\overline{7}$, $1+\\sqrt{3}$, $152$, $\\pi$.', 'صنّف في $\\mathbb{N}$ أو $\\mathbb{Z}$ أو $\\mathbb{Q}$ أو غير النسبية: $-4$ و$\\frac{13}{6}$ و$\\sqrt{5}$ و$2{,}\\overline{7}$ و$1+\\sqrt{3}$ و$152$ و$\\pi$.'), solution: say('$\\mathbb{N}$: 152. $\\mathbb{Z}$ (ez $\\mathbb{N}$): −4. $\\mathbb{Q}$ (ez osoak): $\\frac{13}{6}$, $2{,}\\overline{7}$. Irrazionalak: $\\sqrt{5}$, $1+\\sqrt{3}$, $\\pi$. Guztiak errealak.', '$\\mathbb{N}$: 152. $\\mathbb{Z}$ (no $\\mathbb{N}$): −4. $\\mathbb{Q}$ (no enteros): $\\frac{13}{6}$, $2{,}\\overline{7}$. Irracionales: $\\sqrt{5}$, $1+\\sqrt{3}$, $\\pi$. Todos son reales.', '$\\mathbb{N}$: 152. $\\mathbb{Z}$ (ليست في $\\mathbb{N}$): −4. $\\mathbb{Q}$ (غير صحيحة): $\\frac{13}{6}$ و$2{,}\\overline{7}$. غير نسبية: $\\sqrt{5}$ و$1+\\sqrt{3}$ و$\\pi$. وكلها حقيقية.') },
            { id: 21, difficulty: 'easy', question: say('Idatzi tarte edo zuzenerdi gisa: a) 2 baino handiagoak eta 7 baino txikiagoak; b) −1 eta 3 artean, biak barne; c) 5 edo handiagoak; d) 10 baino txikiagoak.', 'Escribe como intervalo o semirrecta: a) mayores que 2 y menores que 7; b) entre −1 y 3, ambos incluidos; c) mayores o iguales que 5; d) menores que 10.', 'اكتب على صورة فترة أو نصف مستقيم: أ) أكبر من 2 وأصغر من 7؛ ب) بين −1 و3 وكلاهما داخل؛ ج) أكبر من أو تساوي 5؛ د) أصغر من 10.'), solution: same('$a)\\ (2,\\,7)\\quad b)\\ [-1,\\,3]\\quad c)\\ [5,\\,+\\infty)\\quad d)\\ (-\\infty,\\,10)$') },
            { id: 22, difficulty: 'easy', question: say('Idatzi marraztutako bi multzoak tarte eta desberdintza gisa.', 'Escribe los dos conjuntos dibujados como intervalo y como desigualdad.', 'اكتب المجموعتين المرسومتين على صورة فترة ومتباينة.'), solution: say('Urdina: $(1,\\,5]$, $1<x\\le 5$. Gorria: $[-2,\\,+\\infty)$, $x\\ge -2$.', 'Azul: $(1,\\,5]$, $1<x\\le 5$. Rojo: $[-2,\\,+\\infty)$, $x\\ge -2$.', 'الأزرق: $(1,\\,5]$ أي $1<x\\le 5$. الأحمر: $[-2,\\,+\\infty)$ أي $x\\ge -2$.'), line: { from: -4, to: 7, intervals: [{ value: interval(1, 5, false, true) }, { value: interval(-2, null, true, false), color: 'second', lift: 22 }] } },
            { id: 23, difficulty: 'medium', question: say('$\\sqrt{40}$ bi zenbaki oso jarraituren artean dago. Idatzi txikiena.', '$\\sqrt{40}$ está entre dos enteros consecutivos. Escribe el menor.', '$\\sqrt{40}$ يقع بين عددين صحيحين متتاليين. اكتب الأصغر.'), solution: same('$36<40<49\\ \\to\\ 6<\\sqrt{40}<7$'), answer: { expected: fraction(6) } },
            { id: 24, difficulty: 'medium', question: say('Ordenatu txikienetik handienera: $\\sqrt{3}$, $\\frac{7}{4}$, $1{,}7$, $1{,}\\overline{7}$.', 'Ordena de menor a mayor: $\\sqrt{3}$, $\\frac{7}{4}$, $1{,}7$, $1{,}\\overline{7}$.', 'رتّب من الأصغر إلى الأكبر: $\\sqrt{3}$ و$\\frac{7}{4}$ و$1{,}7$ و$1{,}\\overline{7}$.'), solution: same('$1{,}7<\\sqrt{3}=1{,}732\\ldots<\\frac{7}{4}=1{,}75<1{,}777\\ldots$') },
            { id: 25, difficulty: 'medium', question: say('$A=[-3,\\,7)$ eta $B=(5,\\,+\\infty)$. Zein zenbaki daude $A$-n edo $B$-n? Eta bietan?', '$A=[-3,\\,7)$ y $B=(5,\\,+\\infty)$. ¿Qué números están en $A$ o en $B$? ¿Y en los dos?', '$A=[-3,\\,7)$ و$B=(5,\\,+\\infty)$. ما الأعداد التي في $A$ أو في $B$؟ وما التي فيهما معًا؟'), solution: same('$A\\cup B=[-3,\\,+\\infty)\\qquad A\\cap B=(5,\\,7)$'), line: { from: -4, to: 10, intervals: [{ value: interval(-3, 7, true, false) }, { value: interval(5, null, false, false), color: 'second', lift: 22 }] } },
            { id: 26, difficulty: 'medium', question: say('Zenbat zenbaki oso daude $[-2,\\,4]$ tartean?', '¿Cuántos números enteros hay en el intervalo $[-2,\\,4]$?', 'كم عددًا صحيحًا في الفترة $[-2,\\,4]$؟'), solution: say('$-2,\\,-1,\\,0,\\,1,\\,2,\\,3,\\,4$: 7 zenbaki (muturrak barne).', '$-2,\\,-1,\\,0,\\,1,\\,2,\\,3,\\,4$: 7 números (extremos incluidos).', '$-2,\\,-1,\\,0,\\,1,\\,2,\\,3,\\,4$: 7 أعداد (الطرفان داخلان).'), answer: { expected: fraction(7) } },
            { id: 27, difficulty: 'hard', question: say('Zein $x$-rentzat kalkula daitezke $\\sqrt{x-5}$ eta $\\sqrt{5-x}$? Idatzi tarte gisa.', '¿Para qué valores de $x$ se pueden calcular $\\sqrt{x-5}$ y $\\sqrt{5-x}$? Escríbelo como intervalo.', 'لأي قيم $x$ يمكن حساب $\\sqrt{x-5}$ و$\\sqrt{5-x}$؟ اكتب الجواب فترة.'), solution: same('$x-5\\ge 0\\to [5,\\,+\\infty)\\qquad 5-x\\ge 0\\to (-\\infty,\\,5]$') },
            { id: 28, difficulty: 'hard', question: say('Arrazionala ala irrazionala? a) 2 cm-ko aldeko karratuaren diagonala. b) 2 cm-ko erradioko zirkuluaren azalera. c) 24 cm-ko katetoa eta 25 cm-ko hipotenusa dituen triangeluaren beste katetoa.', '¿Racional o irracional? a) La diagonal de un cuadrado de lado 2 cm. b) El área de un círculo de radio 2 cm. c) El otro cateto de un triángulo rectángulo con un cateto de 24 cm e hipotenusa de 25 cm.', 'نسبي أم غير نسبي؟ أ) قطر مربع ضلعه 2 سم. ب) مساحة دائرة نصف قطرها 2 سم. ج) الضلع القائم الآخر لمثلث قائم فيه ضلع 24 سم ووتر 25 سم.'), solution: say('a) $\\sqrt{8}$: irrazionala. b) $4\\pi$: irrazionala. c) $\\sqrt{625-576}=\\sqrt{49}=7$: arrazionala.', 'a) $\\sqrt{8}$: irracional. b) $4\\pi$: irracional. c) $\\sqrt{625-576}=\\sqrt{49}=7$: racional.', 'أ) $\\sqrt{8}$: غير نسبي. ب) $4\\pi$: غير نسبي. ج) $\\sqrt{625-576}=\\sqrt{49}=7$: نسبي.') },
            { id: 29, difficulty: 'hard', question: say('$1-\\sqrt{3}$ eta $3+\\sqrt{2}$ zenbakietatik, zein da $x^{2}-6x+7=0$ ekuazioaren ebazpena?', 'De los números $1-\\sqrt{3}$ y $3+\\sqrt{2}$, ¿cuál es solución de $x^{2}-6x+7=0$?', 'من العددين $1-\\sqrt{3}$ و$3+\\sqrt{2}$، أيهما حل للمعادلة $x^{2}-6x+7=0$؟'), solution: same('$(3+\\sqrt{2})^{2}-6(3+\\sqrt{2})+7=11+6\\sqrt{2}-18-6\\sqrt{2}+7=0$') }
        ]
    },
    {
        id: 'approx',
        title: say('Hurbilketak eta idazkera zientifikoa', 'Aproximaciones y notación científica', 'التقريب والترميز العلمي'),
        items: [
            { id: 30, difficulty: 'easy', question: say('Trunkatu eta biribildu ehunenetara: $1{,}234$; $82{,}745$; $9{,}007$; $3{,}555$.', 'Trunca y redondea a las centésimas: $1{,}234$; $82{,}745$; $9{,}007$; $3{,}555$.', 'ابتر وقرّب إلى الأجزاء من مئة: $1{,}234$ و$82{,}745$ و$9{,}007$ و$3{,}555$.'), solution: same('$1{,}23\\,/\\,1{,}23\\quad 82{,}74\\,/\\,82{,}75\\quad 9{,}00\\,/\\,9{,}01\\quad 3{,}55\\,/\\,3{,}56$') },
            { id: 31, difficulty: 'easy', question: say('Biribildu $8{,}5292$ ehunenetara.', 'Redondea $8{,}5292$ a las centésimas.', 'قرّب $8{,}5292$ إلى الأجزاء من مئة.'), solution: same('$8{,}5292\\approx 8{,}53$'), answer: { expected: fraction(853, 100) } },
            { id: 32, difficulty: 'easy', question: say('Trunkatu $15{,}107$ ehunenetara.', 'Trunca $15{,}107$ a las centésimas.', 'ابتر $15{,}107$ إلى الأجزاء من مئة.'), solution: same('$15{,}107\\to 15{,}10$'), answer: { expected: fraction(151, 10) } },
            { id: 33, difficulty: 'medium', question: say('2,53 m-ko zuhaitz batek 2,5 m dituela esan da. Kalkulatu errore absolutua (m) eta erlatiboa.', 'Se dice que un árbol de 2,53 m mide 2,5 m. Calcula el error absoluto (m) y el relativo.', 'قيل إن شجرة طولها 2.53 م طولها 2.5 م. احسب الخطأ المطلق (م) والنسبي.'), solution: same('$E_a=|2{,}53-2{,}5|=0{,}03\\qquad E_r=\\frac{0{,}03}{2{,}53}\\approx 0{,}0119$'), answer: { expected: fraction(3, 100) } },
            { id: 34, difficulty: 'medium', question: say('Idatzi idazkera zientifikoan: a) $83\\,400\\,000\\,000\\,000\\,000$ b) $0{,}0000000001846$ c) $9\\,170\\,000\\,000$', 'Escribe en notación científica: a) $83\\,400\\,000\\,000\\,000\\,000$ b) $0{,}0000000001846$ c) $9\\,170\\,000\\,000$', 'اكتب بالترميز العلمي: أ) $83\\,400\\,000\\,000\\,000\\,000$ ب) $0{,}0000000001846$ ج) $9\\,170\\,000\\,000$'), solution: same('$8{,}34\\cdot 10^{16}\\qquad 1{,}846\\cdot 10^{-10}\\qquad 9{,}17\\cdot 10^{9}$') },
            { id: 35, difficulty: 'medium', question: say('Idatzi idazkera arruntean: a) $5{,}42\\cdot 10^{-9}$ b) $1{,}496\\cdot 10^{7}$ c) $-3{,}7\\cdot 10^{-6}$', 'Escribe en notación decimal: a) $5{,}42\\cdot 10^{-9}$ b) $1{,}496\\cdot 10^{7}$ c) $-3{,}7\\cdot 10^{-6}$', 'اكتب بالصورة العادية: أ) $5{,}42\\cdot 10^{-9}$ ب) $1{,}496\\cdot 10^{7}$ ج) $-3{,}7\\cdot 10^{-6}$'), solution: same('$0{,}00000000542\\qquad 14\\,960\\,000\\qquad -0{,}0000037$') },
            { id: 36, difficulty: 'medium', question: say('$(7{,}82\\cdot 10^{5})\\cdot(9{,}16\\cdot 10^{4})=a\\cdot 10^{10}$. Zenbat da $a$?', '$(7{,}82\\cdot 10^{5})\\cdot(9{,}16\\cdot 10^{4})=a\\cdot 10^{10}$. ¿Cuánto vale $a$?', '$(7{,}82\\cdot 10^{5})\\cdot(9{,}16\\cdot 10^{4})=a\\cdot 10^{10}$. كم تساوي $a$؟'), solution: same('$71{,}6312\\cdot 10^{9}=7{,}16312\\cdot 10^{10}$'), answer: { expected: fraction(716312, 100000) } },
            { id: 37, difficulty: 'hard', question: say('$(6{,}023\\cdot 10^{13}):(7{,}02\\cdot 10^{19})\\approx 8{,}58\\cdot 10^{n}$. Zenbat da $n$?', '$(6{,}023\\cdot 10^{13}):(7{,}02\\cdot 10^{19})\\approx 8{,}58\\cdot 10^{n}$. ¿Cuánto vale $n$?', '$(6{,}023\\cdot 10^{13}):(7{,}02\\cdot 10^{19})\\approx 8{,}58\\cdot 10^{n}$. كم تساوي $n$؟'), solution: same('$0{,}858\\cdot 10^{-6}=8{,}58\\cdot 10^{-7}$'), answer: { expected: fraction(-7) } },
            { id: 38, difficulty: 'hard', question: say('Igogailu batean 250 kg gehienez. Lau lagunek 51,65; 62,75; 81,82 eta 53,85 kg pisatzen dute. Unitateetara trunkatuta batzean, igo daitezke? Eta zehazki kalkulatuta?', 'Un ascensor admite 250 kg como máximo. Cuatro personas pesan 51,65; 62,75; 81,82 y 53,85 kg. Truncando a las unidades, ¿pueden subir? ¿Y con el cálculo exacto?', 'مصعد يتحمل 250 كغ على الأكثر. أوزان أربعة أشخاص 51.65 و62.75 و81.82 و53.85 كغ. هل يمكنهم الصعود إذا بترنا إلى الوحدات؟ وبالحساب الدقيق؟'), solution: say('Trunkatuta: $51+62+81+53=247$ kg (bai dirudi). Zehazki: $250{,}07$ kg → ez lirateke igo behar. Trunkatzeak beti behera hurbiltzen du.', 'Truncando: $51+62+81+53=247$ kg (parece que sí). Exacto: $250{,}07$ kg → no deberían subir. Truncar siempre aproxima por debajo.', 'بالبتر: $51+62+81+53=247$ كغ (يبدو ممكنًا). بالدقة: $250{,}07$ كغ ← لا ينبغي أن يصعدوا. البتر يقرّب دائمًا إلى الأدنى.') },
            { id: 39, difficulty: 'hard', question: say('Jesusek 200 €-ko aurrekontua egin zuen eta 200,90 € gastatu ditu. Zein da errore erlatiboa, ehunekotan?', 'Jesús hizo un presupuesto de 200 € y ha gastado 200,90 €. ¿Cuál es el error relativo, en porcentaje?', 'وضع خيسوس ميزانية 200 € وأنفق 200.90 €. ما الخطأ النسبي بالنسبة المئوية؟'), solution: same('$E_a=0{,}90\\qquad E_r=\\frac{0{,}90}{200}=0{,}0045\\to 0{,}45\\,\\%$'), answer: { expected: fraction(45, 100) } }
        ]
    },
    {
        id: 'radicals',
        title: say('Erroak eta erradikalak', 'Raíces y radicales', 'الجذور والجذريات'),
        items: [
            { id: 40, difficulty: 'easy', question: same('$\\sqrt[3]{-8}$'), solution: same('$(-2)^{3}=-8\\ \\to\\ \\sqrt[3]{-8}=-2$'), answer: { expected: fraction(-2) } },
            { id: 41, difficulty: 'easy', question: say('Idatzi berretura gisa: $\\sqrt[5]{x^{2}}$, $\\sqrt{2}$, $\\sqrt[3]{10^{6}}$, $\\sqrt[4]{a}$.', 'Escribe como potencia: $\\sqrt[5]{x^{2}}$, $\\sqrt{2}$, $\\sqrt[3]{10^{6}}$, $\\sqrt[4]{a}$.', 'اكتب على صورة قوة: $\\sqrt[5]{x^{2}}$ و$\\sqrt{2}$ و$\\sqrt[3]{10^{6}}$ و$\\sqrt[4]{a}$.'), solution: same('$x^{\\frac{2}{5}}\\qquad 2^{\\frac{1}{2}}\\qquad 10^{2}\\qquad a^{\\frac{1}{4}}$') },
            { id: 42, difficulty: 'easy', question: same('$125^{\\frac{2}{3}}$'), solution: same('$(5^{3})^{\\frac{2}{3}}=5^{2}=25$'), answer: { expected: fraction(25) } },
            { id: 43, difficulty: 'medium', question: say('$\\sqrt{300}=a\\sqrt{3}$. Zenbat da $a$?', '$\\sqrt{300}=a\\sqrt{3}$. ¿Cuánto vale $a$?', '$\\sqrt{300}=a\\sqrt{3}$. كم تساوي $a$؟'), solution: same('$300=2^{2}\\cdot 5^{2}\\cdot 3\\ \\to\\ 10\\sqrt{3}$'), answer: { expected: fraction(10) } },
            { id: 44, difficulty: 'medium', question: say('$\\sqrt[3]{16}=a\\sqrt[3]{2}$. Zenbat da $a$?', '$\\sqrt[3]{16}=a\\sqrt[3]{2}$. ¿Cuánto vale $a$?', '$\\sqrt[3]{16}=a\\sqrt[3]{2}$. كم تساوي $a$؟'), solution: same('$16=2^{3}\\cdot 2\\ \\to\\ 2\\sqrt[3]{2}$'), answer: { expected: fraction(2) } },
            { id: 45, difficulty: 'medium', question: say('$2\\sqrt{8}+4\\sqrt{72}-7\\sqrt{18}=a\\sqrt{2}$. Zenbat da $a$?', '$2\\sqrt{8}+4\\sqrt{72}-7\\sqrt{18}=a\\sqrt{2}$. ¿Cuánto vale $a$?', '$2\\sqrt{8}+4\\sqrt{72}-7\\sqrt{18}=a\\sqrt{2}$. كم تساوي $a$؟'), solution: same('$4\\sqrt{2}+24\\sqrt{2}-21\\sqrt{2}=7\\sqrt{2}$'), answer: { expected: fraction(7) } },
            { id: 46, difficulty: 'medium', question: same('$\\sqrt{5}\\cdot\\sqrt{10}\\cdot\\sqrt{8}$'), solution: same('$\\sqrt{5\\cdot 10\\cdot 8}=\\sqrt{400}=20$'), answer: { expected: fraction(20) } },
            { id: 47, difficulty: 'hard', question: say('Arrazionalizatu: $\\frac{12}{\\sqrt{2}}=a\\sqrt{2}$. Zenbat da $a$?', 'Racionaliza: $\\frac{12}{\\sqrt{2}}=a\\sqrt{2}$. ¿Cuánto vale $a$?', 'أنطِق المقام: $\\frac{12}{\\sqrt{2}}=a\\sqrt{2}$. كم تساوي $a$؟'), solution: same('$\\frac{12\\sqrt{2}}{\\sqrt{2}\\cdot\\sqrt{2}}=\\frac{12\\sqrt{2}}{2}=6\\sqrt{2}$'), answer: { expected: fraction(6) } },
            { id: 48, difficulty: 'hard', question: same('$(2+\\sqrt{3})(2-\\sqrt{3})$'), solution: same('$2^{2}-(\\sqrt{3})^{2}=4-3=1$'), answer: { expected: fraction(1) } },
            { id: 49, difficulty: 'hard', question: say('Laukizuzen baten aldeek $\\sqrt{18}$ cm eta $\\sqrt{8}$ cm neurtzen dute. Zenbat da azalera (cm²)?', 'Los lados de un rectángulo miden $\\sqrt{18}$ cm y $\\sqrt{8}$ cm. ¿Cuánto mide su área (cm²)?', 'ضلعا مستطيل $\\sqrt{18}$ سم و$\\sqrt{8}$ سم. كم مساحته (سم²)؟'), solution: same('$\\sqrt{18}\\cdot\\sqrt{8}=\\sqrt{144}=12$'), answer: { expected: fraction(12) } },
            { id: 50, difficulty: 'hard', question: say('$(2\\sqrt{5}-3)^{2}=p-q\\sqrt{5}$. Zenbat da $p$?', '$(2\\sqrt{5}-3)^{2}=p-q\\sqrt{5}$. ¿Cuánto vale $p$?', '$(2\\sqrt{5}-3)^{2}=p-q\\sqrt{5}$. كم تساوي $p$؟'), solution: same('$20-12\\sqrt{5}+9=29-12\\sqrt{5}$'), answer: { expected: fraction(29) } }
        ]
    }
]
